/**
 * Centralized error code registry for EngineerOS.
 * All error codes follow UPPER_SNAKE_CASE convention.
 *
 * Usage:
 *   throw new AppError({ code: ErrorCodes.AUTH_UNAUTHORIZED, message: '...' });
 */

export const ErrorCodes = {
  // Auth errors (1xx)
  AUTH_UNAUTHORIZED: 'AUTH_UNAUTHORIZED',
  AUTH_FORBIDDEN: 'AUTH_FORBIDDEN',
  AUTH_TOKEN_EXPIRED: 'AUTH_TOKEN_EXPIRED',
  AUTH_INVALID_CREDENTIALS: 'AUTH_INVALID_CREDENTIALS',
  AUTH_SESSION_NOT_FOUND: 'AUTH_SESSION_NOT_FOUND',

  // API errors (2xx)
  API_BAD_REQUEST: 'API_BAD_REQUEST',
  API_NOT_FOUND: 'API_NOT_FOUND',
  API_RATE_LIMITED: 'API_RATE_LIMITED',
  API_INTERNAL_ERROR: 'API_INTERNAL_ERROR',
  API_SERVICE_UNAVAILABLE: 'API_SERVICE_UNAVAILABLE',

  // AI errors (3xx)
  AI_PROVIDER_UNAVAILABLE: 'AI_PROVIDER_UNAVAILABLE',
  AI_RESPONSE_INVALID: 'AI_RESPONSE_INVALID',
  AI_RATE_LIMITED: 'AI_RATE_LIMITED',
  AI_CONTEXT_TOO_LONG: 'AI_CONTEXT_TOO_LONG',

  // Billing errors (4xx)
  BILLING_PAYMENT_FAILED: 'BILLING_PAYMENT_FAILED',
  BILLING_SUBSCRIPTION_EXPIRED: 'BILLING_SUBSCRIPTION_EXPIRED',
  BILLING_INVOICE_NOT_FOUND: 'BILLING_INVOICE_NOT_FOUND',
  BILLING_WEBHOOK_INVALID: 'BILLING_WEBHOOK_INVALID',

  // Data errors (5xx)
  DATA_VALIDATION_FAILED: 'DATA_VALIDATION_FAILED',
  DATA_NOT_FOUND: 'DATA_NOT_FOUND',
  DATA_CONFLICT: 'DATA_CONFLICT',
  DATA_SYNC_FAILED: 'DATA_SYNC_FAILED',

  // Storage errors (6xx)
  STORAGE_QUOTA_EXCEEDED: 'STORAGE_QUOTA_EXCEEDED',
  STORAGE_READ_FAILED: 'STORAGE_READ_FAILED',
  STORAGE_WRITE_FAILED: 'STORAGE_WRITE_FAILED',

  // Network errors (7xx)
  NETWORK_OFFLINE: 'NETWORK_OFFLINE',
  NETWORK_TIMEOUT: 'NETWORK_TIMEOUT',
  NETWORK_REQUEST_FAILED: 'NETWORK_REQUEST_FAILED',

  // Generic errors (9xx)
  UNKNOWN_ERROR: 'UNKNOWN_ERROR',
  NOT_IMPLEMENTED: 'NOT_IMPLEMENTED',
  CONFIGURATION_ERROR: 'CONFIGURATION_ERROR',
} as const;

export type ErrorCode = (typeof ErrorCodes)[keyof typeof ErrorCodes];
