export {
  SKILL_NAMES,
  type SkillName,
  type SkillElo,
  type LearningGoal,
  type ProfessionId,
  type IndustryId,
  type CommunicationGoal,
  type SelfReportedCefr,
  type InterfaceLanguage,
  type ExperienceLevel,
  type ProfessionalTrack,
  type ElectricalSubdomain,
  type CefrBand,
  type SkillTrend,
  type PromotionState,
  type SkillProfile,
  type UserLearningProfile,
  type VocabularyMemorySummary,
  type MissionType,
  type MissionDifficulty,
  type DailyMission,
  type AdaptivePaceInput,
  type AdaptivePaceDecision,
  type ProfileBadge,
} from '@/shared/types/domain.types';
