import type { SupportedInterfaceLanguage } from '@/features/localization/localization.types';

export interface SidebarCopy {
  dashboard: string;
  learningPath: string;
  lessons: string;
  vocabulary: string;
  grammar: string;
  reading: string;
  writing: string;
  listening: string;
  speaking: string;
  ai: string;
  tools: string;
  progress: string;
  curriculum: string;
  team: string;
  admin: string;
  profile: string;
  billing: string;
  settings: string;
  logout: string;
  login: string;
  upgrade: string;
  freePlan: string;
  proPlan: string;
  enterprisePlan: string;
  version: string;
  betaNotice: string;
  appName: string;
  poweredBy: string;
  feedback: string;
  help: string;
  privacy: string;
  terms: string;
  contact: string;
  [key: string]: string;
}

export const SIDEBAR_COPY: Record<SupportedInterfaceLanguage, SidebarCopy> = {
  en: {
    dashboard: 'Dashboard',
    learningPath: 'Learning Path',
    lessons: 'Lessons',
    vocabulary: 'Vocabulary',
    grammar: 'Grammar',
    reading: 'Reading',
    writing: 'Writing',
    listening: 'Listening',
    speaking: 'Speaking',
    ai: 'AI Coach',
    tools: 'Tools',
    progress: 'Progress',
    curriculum: 'Curriculum',
    team: 'Team',
    admin: 'Admin',
    profile: 'Profile',
    billing: 'Billing',
    settings: 'Settings',
    logout: 'Log out',
    login: 'Log in',
    upgrade: 'Upgrade',
    freePlan: 'Free',
    proPlan: 'Pro',
    enterprisePlan: 'Enterprise',
    version: 'Version',
    betaNotice: 'Beta',
    appName: 'EngVox',
    poweredBy: 'Powered by',
    feedback: 'Feedback',
    help: 'Help',
    privacy: 'Privacy',
    terms: 'Terms',
    contact: 'Contact',
  },
  tr: {
    dashboard: 'Kontrol Paneli',
    learningPath: 'Öğrenme Yolu',
    lessons: 'Dersler',
    vocabulary: 'Kelime Hazinesi',
    grammar: 'Dilbilgisi',
    reading: 'Okuma',
    writing: 'Yazma',
    listening: 'Dinleme',
    speaking: 'Konuşma',
    ai: 'AI Koç',
    tools: 'Araçlar',
    progress: 'İlerleme',
    curriculum: 'Müfredat',
    team: 'Takım',
    admin: 'Yönetim',
    profile: 'Profil',
    billing: 'Faturalandırma',
    settings: 'Ayarlar',
    logout: 'Çıkış Yap',
    login: 'Giriş Yap',
    upgrade: 'Yükselt',
    freePlan: 'Ücretsiz',
    proPlan: 'Pro',
    enterprisePlan: 'Kurumsal',
    version: 'Sürüm',
    betaNotice: 'Beta',
    appName: 'EngVox',
    poweredBy: 'Geliştiren',
    feedback: 'Geri Bildirim',
    help: 'Yardım',
    privacy: 'Gizlilik',
    terms: 'Şartlar',
    contact: 'İletişim',
  },
  ar: {
    dashboard: 'لوحة التحكم',
    learningPath: 'مسار التعلم',
    lessons: 'الدروس',
    vocabulary: 'المفردات',
    grammar: 'القواعد',
    reading: 'القراءة',
    writing: 'الكتابة',
    listening: 'الاستماع',
    speaking: 'التحدث',
    ai: 'مدرب AI',
    tools: 'الأدوات',
    progress: 'التقدم',
    curriculum: 'المنهج',
    team: 'الفريق',
    admin: 'الإدارة',
    profile: 'الملف الشخصي',
    billing: 'الفوترة',
    settings: 'الإعدادات',
    logout: 'تسجيل الخروج',
    login: 'تسجيل الدخول',
    upgrade: 'ترقية',
    freePlan: 'مجاني',
    proPlan: 'محترف',
    enterprisePlan: 'مؤسسي',
    version: 'الإصدار',
    betaNotice: 'بيتا',
    appName: 'EngVox',
    poweredBy: 'مدعوم من',
    feedback: 'ملاحظات',
    help: 'مساعدة',
    privacy: 'الخصوصية',
    terms: 'الشروط',
    contact: 'اتصل بنا',
  },
  de: {
    dashboard: 'Dashboard',
    learningPath: 'Lernpfad',
    lessons: 'Lektionen',
    vocabulary: 'Wortschatz',
    grammar: 'Grammatik',
    reading: 'Lesen',
    writing: 'Schreiben',
    listening: 'Hören',
    speaking: 'Sprechen',
    ai: 'KI-Coach',
    tools: 'Tools',
    progress: 'Fortschritt',
    curriculum: 'Lehrplan',
    team: 'Team',
    admin: 'Admin',
    profile: 'Profil',
    billing: 'Abrechnung',
    settings: 'Einstellungen',
    logout: 'Abmelden',
    login: 'Anmelden',
    upgrade: 'Upgrade',
    freePlan: 'Kostenlos',
    proPlan: 'Pro',
    enterprisePlan: 'Enterprise',
    version: 'Version',
    betaNotice: 'Beta',
    appName: 'EngVox',
    poweredBy: 'Entwickelt von',
    feedback: 'Feedback',
    help: 'Hilfe',
    privacy: 'Datenschutz',
    terms: 'AGB',
    contact: 'Kontakt',
  },
  es: {
    dashboard: 'Panel',
    learningPath: 'Ruta de Aprendizaje',
    lessons: 'Lecciones',
    vocabulary: 'Vocabulario',
    grammar: 'Gramática',
    reading: 'Lectura',
    writing: 'Escritura',
    listening: 'Escucha',
    speaking: 'Hablar',
    ai: 'Coach IA',
    tools: 'Herramientas',
    progress: 'Progreso',
    curriculum: 'Currículo',
    team: 'Equipo',
    admin: 'Admin',
    profile: 'Perfil',
    billing: 'Facturación',
    settings: 'Ajustes',
    logout: 'Cerrar sesión',
    login: 'Iniciar sesión',
    upgrade: 'Actualizar',
    freePlan: 'Gratis',
    proPlan: 'Pro',
    enterprisePlan: 'Empresa',
    version: 'Versión',
    betaNotice: 'Beta',
    appName: 'EngVox',
    poweredBy: 'Desarrollado por',
    feedback: 'Comentarios',
    help: 'Ayuda',
    privacy: 'Privacidad',
    terms: 'Términos',
    contact: 'Contacto',
  },
  fr: {
    dashboard: 'Tableau de bord',
    learningPath: "Parcours d'apprentissage",
    lessons: 'Leçons',
    vocabulary: 'Vocabulaire',
    grammar: 'Grammaire',
    reading: 'Lecture',
    writing: 'Écriture',
    listening: 'Écoute',
    speaking: 'Expression orale',
    ai: 'Coach IA',
    tools: 'Outils',
    progress: 'Progrès',
    curriculum: 'Programme',
    team: 'Équipe',
    admin: 'Admin',
    profile: 'Profil',
    billing: 'Facturation',
    settings: 'Paramètres',
    logout: 'Déconnexion',
    login: 'Connexion',
    upgrade: 'Mettre à niveau',
    freePlan: 'Gratuit',
    proPlan: 'Pro',
    enterprisePlan: 'Entreprise',
    version: 'Version',
    betaNotice: 'Beta',
    appName: 'EngVox',
    poweredBy: 'Développé par',
    feedback: 'Commentaires',
    help: 'Aide',
    privacy: 'Confidentialité',
    terms: 'Conditions',
    contact: 'Contact',
  },
  pt: {
    dashboard: 'Painel',
    learningPath: 'Caminho de Aprendizado',
    lessons: 'Lições',
    vocabulary: 'Vocabulário',
    grammar: 'Gramática',
    reading: 'Leitura',
    writing: 'Escrita',
    listening: 'Escuta',
    speaking: 'Fala',
    ai: 'Coach IA',
    tools: 'Ferramentas',
    progress: 'Progresso',
    curriculum: 'Currículo',
    team: 'Equipe',
    admin: 'Admin',
    profile: 'Perfil',
    billing: 'Faturamento',
    settings: 'Configurações',
    logout: 'Sair',
    login: 'Entrar',
    upgrade: 'Atualizar',
    freePlan: 'Grátis',
    proPlan: 'Pro',
    enterprisePlan: 'Empresarial',
    version: 'Versão',
    betaNotice: 'Beta',
    appName: 'EngVox',
    poweredBy: 'Desenvolvido por',
    feedback: 'Feedback',
    help: 'Ajuda',
    privacy: 'Privacidade',
    terms: 'Termos',
    contact: 'Contato',
  },
  ru: {
    dashboard: 'Панель',
    learningPath: 'Путь обучения',
    lessons: 'Уроки',
    vocabulary: 'Словарный запас',
    grammar: 'Грамматика',
    reading: 'Чтение',
    writing: 'Письмо',
    listening: 'Аудирование',
    speaking: 'Говорение',
    ai: 'AI Тренер',
    tools: 'Инструменты',
    progress: 'Прогресс',
    curriculum: 'Программа',
    team: 'Команда',
    admin: 'Админ',
    profile: 'Профиль',
    billing: 'Оплата',
    settings: 'Настройки',
    logout: 'Выйти',
    login: 'Войти',
    upgrade: 'Обновить',
    freePlan: 'Бесплатно',
    proPlan: 'Про',
    enterprisePlan: 'Корпоративный',
    version: 'Версия',
    betaNotice: 'Бета',
    appName: 'EngVox',
    poweredBy: 'Разработано',
    feedback: 'Отзыв',
    help: 'Помощь',
    privacy: 'Конфиденциальность',
    terms: 'Условия',
    contact: 'Контакты',
  },
  zh: {
    dashboard: '仪表盘',
    learningPath: '学习路径',
    lessons: '课程',
    vocabulary: '词汇',
    grammar: '语法',
    reading: '阅读',
    writing: '写作',
    listening: '听力',
    speaking: '口语',
    ai: 'AI教练',
    tools: '工具',
    progress: '进度',
    curriculum: '课程表',
    team: '团队',
    admin: '管理员',
    profile: '个人资料',
    billing: '计费',
    settings: '设置',
    logout: '退出',
    login: '登录',
    upgrade: '升级',
    freePlan: '免费',
    proPlan: '专业版',
    enterprisePlan: '企业版',
    version: '版本',
    betaNotice: '测试版',
    appName: 'EngVox',
    poweredBy: '开发者',
    feedback: '反馈',
    help: '帮助',
    privacy: '隐私',
    terms: '条款',
    contact: '联系我们',
  },
  ja: {
    dashboard: 'ダッシュボード',
    learningPath: '学習パス',
    lessons: 'レッスン',
    vocabulary: '語彙',
    grammar: '文法',
    reading: '読解',
    writing: '作文',
    listening: 'リスニング',
    speaking: 'スピーキング',
    ai: 'AIコーチ',
    tools: 'ツール',
    progress: '進捗',
    curriculum: 'カリキュラム',
    team: 'チーム',
    admin: '管理',
    profile: 'プロフィール',
    billing: '請求',
    settings: '設定',
    logout: 'ログアウト',
    login: 'ログイン',
    upgrade: 'アップグレード',
    freePlan: '無料',
    proPlan: 'プロ',
    enterprisePlan: 'エンタープライズ',
    version: 'バージョン',
    betaNotice: 'ベータ',
    appName: 'EngVox',
    poweredBy: '開発元',
    feedback: 'フィードバック',
    help: 'ヘルプ',
    privacy: 'プライバシー',
    terms: '利用規約',
    contact: 'お問い合わせ',
  },
  it: {
    dashboard: 'Dashboard',
    learningPath: 'Percorso di Apprendimento',
    lessons: 'Lezioni',
    vocabulary: 'Vocabolario',
    grammar: 'Grammatica',
    reading: 'Lettura',
    writing: 'Scrittura',
    listening: 'Ascolto',
    speaking: 'Parlato',
    ai: 'Coach IA',
    tools: 'Strumenti',
    progress: 'Progresso',
    curriculum: 'Curriculum',
    team: 'Team',
    admin: 'Admin',
    profile: 'Profilo',
    billing: 'Fatturazione',
    settings: 'Impostazioni',
    logout: 'Esci',
    login: 'Accedi',
    upgrade: 'Aggiorna',
    freePlan: 'Gratuito',
    proPlan: 'Pro',
    enterprisePlan: 'Enterprise',
    version: 'Versione',
    betaNotice: 'Beta',
    appName: 'EngVox',
    poweredBy: 'Sviluppato da',
    feedback: 'Feedback',
    help: 'Aiuto',
    privacy: 'Privacy',
    terms: 'Termini',
    contact: 'Contatto',
  },
  vi: {
    dashboard: 'Bảng điều khiển',
    learningPath: 'Lộ trình học tập',
    lessons: 'Bài học',
    vocabulary: 'Từ vựng',
    grammar: 'Ngữ pháp',
    reading: 'Đọc',
    writing: 'Viết',
    listening: 'Nghe',
    speaking: 'Nói',
    ai: 'Huấn luyện viên AI',
    tools: 'Công cụ',
    progress: 'Tiến độ',
    curriculum: 'Chương trình',
    team: 'Nhóm',
    admin: 'Quản trị',
    profile: 'Hồ sơ',
    billing: 'Thanh toán',
    settings: 'Cài đặt',
    logout: 'Đăng xuất',
    login: 'Đăng nhập',
    upgrade: 'Nâng cấp',
    freePlan: 'Miễn phí',
    proPlan: 'Pro',
    enterprisePlan: 'Doanh nghiệp',
    version: 'Phiên bản',
    betaNotice: 'Beta',
    appName: 'EngVox',
    poweredBy: 'Phát triển bởi',
    feedback: 'Phản hồi',
    help: 'Trợ giúp',
    privacy: 'Quyền riêng tư',
    terms: 'Điều khoản',
    contact: 'Liên hệ',
  },
  pl: {
    dashboard: 'Pulpit',
    learningPath: 'Ścieżka nauki',
    lessons: 'Lekcje',
    vocabulary: 'Słownictwo',
    grammar: 'Gramatyka',
    reading: 'Czytanie',
    writing: 'Pisanie',
    listening: 'Słuchanie',
    speaking: 'Mówienie',
    ai: 'Trener AI',
    tools: 'Narzędzia',
    progress: 'Postęp',
    curriculum: 'Kurriculum',
    team: 'Zespół',
    admin: 'Admin',
    profile: 'Profil',
    billing: 'Rozliczenia',
    settings: 'Ustawienia',
    logout: 'Wyloguj',
    login: 'Zaloguj',
    upgrade: 'Aktualizuj',
    freePlan: 'Darmowy',
    proPlan: 'Pro',
    enterprisePlan: 'Enterprise',
    version: 'Wersja',
    betaNotice: 'Beta',
    appName: 'EngVox',
    poweredBy: 'Rozwinięte przez',
    feedback: 'Opinia',
    help: 'Pomoc',
    privacy: 'Prywatność',
    terms: 'Warunki',
    contact: 'Kontakt',
  },
  nl: {
    dashboard: 'Dashboard',
    learningPath: 'Leerpad',
    lessons: 'Lessen',
    vocabulary: 'Woordenschat',
    grammar: 'Grammatica',
    reading: 'Lezen',
    writing: 'Schrijven',
    listening: 'Luisteren',
    speaking: 'Spreken',
    ai: 'AI Coach',
    tools: 'Hulpmiddelen',
    progress: 'Voortgang',
    curriculum: 'Curriculum',
    team: 'Team',
    admin: 'Beheerder',
    profile: 'Profiel',
    billing: 'Facturatie',
    settings: 'Instellingen',
    logout: 'Afmelden',
    login: 'Aanmelden',
    upgrade: 'Upgraden',
    freePlan: 'Gratis',
    proPlan: 'Pro',
    enterprisePlan: 'Enterprise',
    version: 'Versie',
    betaNotice: 'Beta',
    appName: 'EngVox',
    poweredBy: 'Ontwikkeld door',
    feedback: 'Feedback',
    help: 'Hulp',
    privacy: 'Privacy',
    terms: 'Voorwaarden',
    contact: 'Contact',
  },
  id: {
    dashboard: 'Dasbor',
    learningPath: 'Jalur Belajar',
    lessons: 'Pelajaran',
    vocabulary: 'Kosa Kata',
    grammar: 'Tata Bahasa',
    reading: 'Membaca',
    writing: 'Menulis',
    listening: 'Mendengar',
    speaking: 'Berbicara',
    ai: 'Pelatih AI',
    tools: 'Alat',
    progress: 'Kemajuan',
    curriculum: 'Kurikulum',
    team: 'Tim',
    admin: 'Admin',
    profile: 'Profil',
    billing: 'Penagihan',
    settings: 'Pengaturan',
    logout: 'Keluar',
    login: 'Masuk',
    upgrade: 'Upgrade',
    freePlan: 'Gratis',
    proPlan: 'Pro',
    enterprisePlan: 'Enterprise',
    version: 'Versi',
    betaNotice: 'Beta',
    appName: 'EngVox',
    poweredBy: 'Dikembangkan oleh',
    feedback: 'Umpan Balik',
    help: 'Bantuan',
    privacy: 'Privasi',
    terms: 'Syarat',
    contact: 'Kontak',
  },
};
