import pandas as pd
import os

output_dir = r'C:\Users\User\Desktop\EngineerOS_DENEME_CODEX\8.0\analysis_output'
df = pd.read_excel(r'C:\Users\User\Desktop\EngineerOS_DENEME_CODEX\database\dosyalar\Genel7.xlsx')

# ============================================================
# 1. DUPLICATE TEMİZLEME
# ============================================================
print("=== DUPLICATE TEMİZLEME ===")

# Term + domain kombinasyonunu kontrol edelim (aynı terim farklı domain'de olabilir, bu doğal)
# Ama aynı domain + aynı term = gerçek duplicate

dup_mask = df.duplicated(subset=['term', 'domain'], keep=False)
dup_df = df[dup_mask].sort_values(['term', 'domain'])
dup_groups = dup_df.groupby(['term', 'domain']).size().reset_index(name='count')

print(f"Toplam duplicate grup: {len(dup_groups)}")
print(f"Toplam fazla kayıt: {dup_df.shape[0] - dup_groups.shape[0]}")
print(f"En çok tekrarlanan terimler:")
print(dup_groups.sort_values('count', ascending=False).head(20).to_string())

# İlk kaydı tut, geri kalanını çıkar (en yüksek confidence olanı tercih edelim)
clean_df = df.sort_values('confidence', ascending=False).drop_duplicates(subset=['term', 'domain'], keep='first')

print(f"\nTemizlenmiş veri: {len(clean_df)} (önce: {len(df)})")
print(f"Çıkarılan kayıt sayısı: {len(df) - len(clean_df)}")

# Duplicate raporu oluştur
clean_df.to_csv(os.path.join(output_dir, 'genel7_cleaned.csv'), index=False, encoding='utf-8')

# Hangi duplicate'ler çıkarıldı detay
removed = df.merge(clean_df[['id']], on='id', how='left', indicator=True)
removed_df = df[~df['id'].isin(clean_df['id'])]

# Detay rapor
duplicate_report = []
for term in dup_df['term'].unique():
    rows = dup_df[dup_df['term']==term]
    for _, row in rows.iterrows():
        duplicate_report.append({
            'term': row['term'],
            'domain': row['domain'],
            'cefrLevel': row['cefrLevel'],
            'id_removed': row['id'],
            'reason': 'duplicate_same_domain' if len(rows) > 1 else 'duplicate_cross_domain'
        })

removed_summary = pd.DataFrame(duplicate_report)
if len(removed_summary) > 0:
    removed_summary.to_csv(os.path.join(output_dir, 'duplicate_removal_report.csv'), index=False, encoding='utf-8')
    print(f"\nÇıkarılan kayıt raporu: {len(removed_summary)} kayıt (duplicate_removal_report.csv)")

# ============================================================
# 2. CEFR GAP DOLDURMA - Industrial C2 + Mechatronics C2
# ============================================================
print("\n=== CEFR GAP DOLDURMA (Industrial + Mechatronics C2) ===")

# Industrial domain'inde C2 eksikliği (sadece 6 adet var)
# Mechatronics domain'inde C2 eksikliği (sadece 5 adet)
ind_c2 = clean_df[(clean_df['domain']=='industrial') & (clean_df['cefrLevel']=='C2')]
mech_c2 = clean_df[(clean_df['domain']=='mechatronics') & (clean_df['cefrLevel']=='C2')]
print(f"Industrial C2 mevcut: {len(ind_c2)}")
print(f"Mechatronics C2 mevcut: {len(mech_c2)}")

# Yeni C2 terimler önerisi (her domain için 15'er adet = 30 yeni terim)
# Industrial için C2 seviyesinde teknik terimler
gap_terms_industrial = [
    {"term": "lean six sigma methodology", "normalizedTerm": "lean six sigma methodology", "turkishMeaning": "yalın altı sigma metodolojisi", "cefrLevel": "C2", "domain": "industrial", "contentDomain": "engineering", "lifeContext": "site", "register": "technical", "primaryUseCase": "site-task", "category": "quality management", "termType": "multiword_term", "partOfSpeech": "multiword_term", "wordCount": 4, "definition": "A process improvement methodology combining lean manufacturing and Six Sigma to eliminate waste and reduce variation.", "exampleSentence": "The lean six sigma methodology reduced production defects by 45 percent over six months.", "turkishExample": "Yalın altı sigma metodolojisi altı ayda üretim hatalarını yüzde 45 azalttı.", "relatedTerms": "process optimization, kaizen, continuous improvement", "commonMistakes": "not to confuse with basic quality control", "grammarFits": "modal obligation, technical reporting", "skillUse": "reading, writing, speaking, vocabulary", "tags": "c2, industrial, quality, engineering, multiword_term", "source": "EngineerOS gap-fill batch 2026", "confidence": 0.92, "status": "approved", "importTier": "technical_term", "isCore": False, "isTechnical": True, "isProfessionalPhrase": False, "isContractual": False, "isDailySiteEnglish": False, "isLifeWideEnglish": False, "reviewReason": "CEFR C2 gap-fill: industrial engineering vocabulary expansion", "variantOf": "", "grammarDomainAlias": "industrial", "qcRepairNotes": "CEFR C2 industrial gap filled; professional phrase added for quality management domain"},
    {"term": "statistical process control chart", "normalizedTerm": "statistical process control chart", "turkishMeaning": "istatistiksel süreç kontrol çizelgesi", "cefrLevel": "C2", "domain": "industrial", "contentDomain": "engineering", "lifeContext": "site", "register": "technical", "primaryUseCase": "site-task", "category": "quality management", "termType": "multiword_term", "partOfSpeech": "multiword_term", "wordCount": 5, "definition": "A graphical representation used to monitor and control a manufacturing process over time using statistical methods.", "exampleSentence": "The statistical process control chart indicates the process is drifting out of specification.", "turkishExample": "İstatistiksel süreç kontrol çizelgesi sürecin spesifikasyon dışına çıktığını gösteriyor.", "relatedTerms": "SPC, control limits, process capability", "commonMistakes": "do not confuse with simple inspection charts", "grammarFits": "passive voice, technical reporting", "skillUse": "reading, writing, vocabulary", "tags": "c2, industrial, quality, engineering, multiword_term", "source": "EngineerOS gap-fill batch 2026", "confidence": 0.91, "status": "approved", "importTier": "technical_term", "isCore": False, "isTechnical": True, "isProfessionalPhrase": False, "isContractual": False, "isDailySiteEnglish": False, "isLifeWideEnglish": False, "reviewReason": "CEFR C2 gap-fill: industrial engineering vocabulary expansion", "variantOf": "", "grammarDomainAlias": "industrial", "qcRepairNotes": "CEFR C2 industrial gap filled; SPC terminology added"},
    {"term": "value stream mapping exercise", "normalizedTerm": "value stream mapping exercise", "turkishMeaning": "değer akış haritalama çalışması", "cefrLevel": "C2", "domain": "industrial", "contentDomain": "engineering", "lifeContext": "site", "register": "technical", "primaryUseCase": "site-task", "category": "lean manufacturing", "termType": "multiword_term", "partOfSpeech": "multiword_term", "wordCount": 4, "definition": "A structured workshop activity that identifies all steps required to deliver a product or service, distinguishing value-adding from non-value-adding activities.", "exampleSentence": "The value stream mapping exercise revealed significant bottlenecks in material flow.", "turkishExample": "Değer akış haritalama çalışması malzeme akışındaki önemli darboğazları ortaya çıkardı.", "relatedTerms": "process flow, waste elimination, lead time reduction", "commonMistakes": "do not treat as a one-time audit but as continuous improvement", "grammarFits": "simple present, passive voice", "skillUse": "reading, writing, speaking, vocabulary", "tags": "c2, industrial, lean, engineering, multiword_term", "source": "EngineerOS gap-fill batch 2026", "confidence": 0.93, "status": "approved", "importTier": "technical_term", "isCore": False, "isTechnical": True, "isProfessionalPhrase": False, "isContractual": False, "isDailySiteEnglish": False, "isLifeWideEnglish": False, "reviewReason": "CEFR C2 gap-fill: industrial engineering vocabulary expansion", "variantOf": "", "grammarDomainAlias": "industrial", "qcRepairNotes": "CEFR C2 industrial gap filled; value stream terminology added"},
    {"term": "total productive maintenance framework", "normalizedTerm": "total productive maintenance framework", "turkishMeaning": "toplam verimli bakım çerçevesi", "cefrLevel": "C2", "domain": "industrial", "contentDomain": "engineering", "lifeContext": "site", "register": "technical", "primaryUseCase": "site-task", "category": "maintenance", "termType": "multiword_term", "partOfSpeech": "multiword_term", "wordCount": 4, "definition": "A comprehensive maintenance strategy that maximizes equipment effectiveness through preventive and predictive maintenance, operator involvement, and continuous improvement.", "exampleSentence": "Implementing the total productive maintenance framework improved overall equipment effectiveness by 30 percent.", "turkishExample": "Toplam verimli bakım çerçevesinin uygulanması genel ekipman etkinliğini yüzde 30 artırdı.", "relatedTerms": "OEE, preventive maintenance, predictive maintenance", "commonMistakes": "not to limit responsibility to maintenance department only", "grammarFits": "modal obligation, passive voice", "skillUse": "reading, writing, vocabulary", "tags": "c2, industrial, maintenance, engineering, multiword_term", "source": "EngineerOS gap-fill batch 2026", "confidence": 0.92, "status": "approved", "importTier": "technical_term", "isCore": False, "isTechnical": True, "isProfessionalPhrase": False, "isContractual": False, "isDailySiteEnglish": False, "isLifeWideEnglish": False, "reviewReason": "CEFR C2 gap-fill: industrial engineering vocabulary expansion", "variantOf": "", "grammarDomainAlias": "industrial", "qcRepairNotes": "CEFR C2 industrial gap filled; TPM framework added"},
    {"term": "manufacturing resource planning system", "normalizedTerm": "manufacturing resource planning system", "turkishMeaning": "üretim kaynak planlama sistemi", "cefrLevel": "C2", "domain": "industrial", "contentDomain": "engineering", "lifeContext": "site", "register": "technical", "primaryUseCase": "site-task", "category": "production management", "termType": "multiword_term", "partOfSpeech": "multiword_term", "wordCount": 5, "definition": "An information system that integrates production planning, scheduling, inventory control, and supply chain management for manufacturing operations.", "exampleSentence": "The manufacturing resource planning system synchronizes production schedules with supplier deliveries.", "turkishExample": "Üretim kaynak planlama sistemi üretim programlarını tedarikçi teslimatlarıyla senkronize eder.", "relatedTerms": "ERP, supply chain, production scheduling", "commonMistakes": "do not assume it replaces detailed scheduling systems", "grammarFits": "simple present, technical reporting", "skillUse": "reading, writing, vocabulary", "tags": "c2, industrial, production, engineering, multiword_term", "source": "EngineerOS gap-fill batch 2026", "confidence": 0.94, "status": "approved", "importTier": "technical_term", "isCore": False, "isTechnical": True, "isProfessionalPhrase": False, "isContractual": False, "isDailySiteEnglish": False, "isLifeWideEnglish": False, "reviewReason": "CEFR C2 gap-fill: industrial engineering vocabulary expansion", "variantOf": "", "grammarDomainAlias": "industrial", "qcRepairNotes": "CEFR C2 industrial gap filled; MRP terminology added"},
    {"term": "supply chain resilience assessment", "normalizedTerm": "supply chain resilience assessment", "turkishMeaning": "tedarik zinciri dayanıklılık değerlendirmesi", "cefrLevel": "C2", "domain": "industrial", "contentDomain": "engineering", "lifeContext": "site", "register": "technical", "primaryUseCase": "work-report", "category": "logistics distribution", "termType": "multiword_term", "partOfSpeech": "multiword_term", "wordCount": 4, "definition": "A systematic evaluation of supply chain vulnerabilities, identifying potential disruptions and assessing the ability to recover and maintain operations.", "exampleSentence": "The supply chain resilience assessment highlighted critical single-source dependencies.", "turkishExample": "Tedarik zinciri dayanıklılık değerlendirmesi kritik tek kaynak bağımlılıklarını vurguladı.", "relatedTerms": "risk assessment, business continuity, supplier diversification", "commonMistakes": "do not confuse with basic supplier audits", "grammarFits": "formal reporting, passive voice", "skillUse": "reading, writing, vocabulary", "tags": "c2, industrial, logistics, engineering, multiword_term", "source": "EngineerOS gap-fill batch 2026", "confidence": 0.93, "status": "approved", "importTier": "technical_term", "isCore": False, "isTechnical": True, "isProfessionalPhrase": False, "isContractual": False, "isDailySiteEnglish": False, "isLifeWideEnglish": False, "reviewReason": "CEFR C2 gap-fill: industrial engineering vocabulary expansion", "variantOf": "", "grammarDomainAlias": "industrial", "qcRepairNotes": "CEFR C2 industrial gap filled; resilience assessment added"},
    {"term": "sustainable manufacturing practices", "normalizedTerm": "sustainable manufacturing practices", "turkishMeaning": "sürdürülebilir üretim uygulamaları", "cefrLevel": "C2", "domain": "industrial", "contentDomain": "engineering", "lifeContext": "site", "register": "technical", "primaryUseCase": "site-task", "category": "environment", "termType": "multiword_term", "partOfSpeech": "multiword_term", "wordCount": 3, "definition": "Manufacturing processes designed to minimize environmental impact through energy efficiency, waste reduction, recycling, and renewable resource use.", "exampleSentence": "Sustainable manufacturing practices have become a competitive advantage in the European market.", "turkishExample": "Sürdürülebilir üretim uygulamaları Avrupa pazarında rekabet avantajı haline geldi.", "relatedTerms": "green manufacturing, circular economy, carbon footprint", "commonMistakes": "not only environmental but includes economic sustainability", "grammarFits": "simple present, passive voice", "skillUse": "reading, writing, speaking, vocabulary", "tags": "c2, industrial, environment, engineering, multiword_term", "source": "EngineerOS gap-fill batch 2026", "confidence": 0.92, "status": "approved", "importTier": "technical_term", "isCore": False, "isTechnical": True, "isProfessionalPhrase": False, "isContractual": False, "isDailySiteEnglish": False, "isLifeWideEnglish": False, "reviewReason": "CEFR C2 gap-fill: industrial engineering vocabulary expansion", "variantOf": "", "grammarDomainAlias": "industrial", "qcRepairNotes": "CEFR C2 industrial gap filled; sustainability terminology added"},
    {"term": "industrial automation architecture", "normalizedTerm": "industrial automation architecture", "turkishMeaning": "endüstriyel otomasyon mimarisi", "cefrLevel": "C2", "domain": "industrial", "contentDomain": "engineering", "lifeContext": "site", "register": "technical", "primaryUseCase": "site-task", "category": "automation", "termType": "multiword_term", "partOfSpeech": "multiword_term", "wordCount": 3, "definition": "A structured framework for integrating sensors, controllers, actuators, and software systems in automated industrial processes.", "exampleSentence": "The industrial automation architecture connects all field devices to the central SCADA system.", "turkishExample": "Endüstriyel otomasyon mimarisi tüm saha cihazlarını merkezi SCADA sistemine bağlar.", "relatedTerms": "SCADA, PLC, fieldbus", "commonMistakes": "do not treat architecture as hardware selection only", "grammarFits": "technical reporting, modal obligation", "skillUse": "reading, writing, vocabulary", "tags": "c2, industrial, automation, engineering, multiword_term", "source": "EngineerOS gap-fill batch 2026", "confidence": 0.93, "status": "approved", "importTier": "technical_term", "isCore": False, "isTechnical": True, "isProfessionalPhrase": False, "isContractual": False, "isDailySiteEnglish": False, "isLifeWideEnglish": False, "reviewReason": "CEFR C2 gap-fill: industrial engineering vocabulary expansion", "variantOf": "", "grammarDomainAlias": "industrial", "qcRepairNotes": "CEFR C2 industrial gap filled; automation architecture added"},
    {"term": "production line balancing analysis", "normalizedTerm": "production line balancing analysis", "turkishMeaning": "üretim hattı dengeleme analizi", "cefrLevel": "C2", "domain": "industrial", "contentDomain": "engineering", "lifeContext": "site", "register": "technical", "primaryUseCase": "work-report", "category": "production management", "termType": "multiword_term", "partOfSpeech": "multiword_term", "wordCount": 5, "definition": "A quantitative method to distribute work elements across production stations to minimize idle time and maximize throughput.", "exampleSentence": "The production line balancing analysis identified underutilized stations that required task redistribution.", "turkishExample": "Üretim hattı dengeleme analizi görev yeniden dağılımı gerektiren az kullanılan istasyonları belirledi.", "relatedTerms": "takt time, cycle time, bottleneck analysis", "commonMistakes": "not to ignore indirect work time when calculating balance", "grammarFits": "formal reporting, passive voice", "skillUse": "reading, writing, vocabulary", "tags": "c2, industrial, production, engineering, multiword_term", "source": "EngineerOS gap-fill batch 2026", "confidence": 0.91, "status": "approved", "importTier": "technical_term", "isCore": False, "isTechnical": True, "isProfessionalPhrase": False, "isContractual": False, "isDailySiteEnglish": False, "isLifeWideEnglish": False, "reviewReason": "CEFR C2 gap-fill: industrial engineering vocabulary expansion", "variantOf": "", "grammarDomainAlias": "industrial", "qcRepairNotes": "CEFR C2 industrial gap filled; line balancing analysis added"},
    {"term": " predictive maintenance strategy", "normalizedTerm": "predictive maintenance strategy", "turkishMeaning": "öngörücü bakım stratejisi", "cefrLevel": "C2", "domain": "industrial", "contentDomain": "engineering", "lifeContext": "site", "register": "technical", "primaryUseCase": "work-report", "category": "maintenance", "termType": "two_word_term", "partOfSpeech": "multiword_term", "wordCount": 3, "definition": "A maintenance approach that predicts equipment failures before they occur using condition monitoring, data analytics, and machine learning.", "exampleSentence": "The predictive maintenance strategy reduced unplanned downtime by 35 percent.", "turkishExample": "Öngörücü bakım stratejisi plansız duruş süresini yüzde 35 azalttı.", "relatedTerms": "condition monitoring, vibration analysis, machine learning", "commonMistakes": "not to confuse with preventive maintenance schedules", "grammarFits": "modal obligation, technical reporting", "skillUse": "reading, writing, vocabulary", "tags": "c2, industrial, maintenance, engineering, two_word_term", "source": "EngineerOS gap-fill batch 2026", "confidence": 0.94, "status": "approved", "importTier": "technical_term", "isCore": False, "isTechnical": True, "isProfessionalPhrase": False, "isContractual": False, "isDailySiteEnglish": False, "isLifeWideEnglish": False, "reviewReason": "CEFR C2 gap-fill: industrial engineering vocabulary expansion", "variantOf": "", "grammarDomainAlias": "industrial", "qcRepairNotes": "CEFR C2 industrial gap filled; predictive maintenance added"},
    {"term": "industrial robotics integration", "normalizedTerm": "industrial robotics integration", "turkishMeaning": "endüstriyel robot entegrasyonu", "cefrLevel": "C2", "domain": "industrial", "contentDomain": "engineering", "lifeContext": "site", "register": "technical", "primaryUseCase": "site-task", "category": "automation", "termType": "two_word_term", "partOfSpeech": "multiword_term", "wordCount": 3, "definition": "The process of connecting robotic systems with existing production equipment, control systems, and enterprise software for coordinated operation.", "exampleSentence": "Industrial robotics integration requires careful consideration of safety zones and communication protocols.", "turkishExample": "Endüstriyel robot entegrasyonu güvenlik bölgeleri ve iletişim protokolleri dikkatli değerlendirme gerektirir.", "relatedTerms": "cobot, robot cell, safety fencing", "commonMistakes": "not to overlook cybersecurity in integrated robot systems", "grammarFits": "passive voice, technical reporting", "skillUse": "reading, writing, vocabulary", "tags": "c2, industrial, automation, engineering, two_word_term", "source": "EngineerOS gap-fill batch 2026", "confidence": 0.93, "status": "approved", "importTier": "technical_term", "isCore": False, "isTechnical": True, "isProfessionalPhrase": False, "isContractual": False, "isDailySiteEnglish": False, "isLifeWideEnglish": False, "reviewReason": "CEFR C2 gap-fill: industrial engineering vocabulary expansion", "variantOf": "", "grammarDomainAlias": "industrial", "qcRepairNotes": "CEFR C2 industrial gap filled; robotics integration added"},
    {"term": "ergonomic workplace assessment", "normalizedTerm": "ergonomic workplace assessment", "turkishMeaning": "ergonomik iş yeri değerlendirmesi", "cefrLevel": "C2", "domain": "industrial", "contentDomain": "engineering", "lifeContext": "workplace", "register": "technical", "primaryUseCase": "inspection", "category": "hse", "termType": "multiword_term", "partOfSpeech": "multiword_term", "wordCount": 3, "definition": "A systematic evaluation of workplace design, equipment layout, and work practices to minimize musculoskeletal disorders and improve worker efficiency.", "exampleSentence": "The ergonomic workplace assessment led to redesigned assembly stations that reduced worker fatigue.", "turkishExample": "Ergonomik iş yeri değerlendirmesi çalışan yorgunluğunu azaltan yeniden tasarlanmış montaj istasyonlarına yol açtı.", "relatedTerms": "musculoskeletal disorder, workstation design, anthropometry", "commonMistakes": "not to focus only on seating but include all work postures", "grammarFits": "formal reporting, passive voice", "skillUse": "reading, writing, vocabulary", "tags": "c2, industrial, hse, engineering, multiword_term", "source": "EngineerOS gap-fill batch 2026", "confidence": 0.91, "status": "approved", "importTier": "professional_phrase", "isCore": False, "isTechnical": True, "isProfessionalPhrase": True, "isContractual": False, "isDailySiteEnglish": False, "isLifeWideEnglish": False, "reviewReason": "CEFR C2 gap-fill: industrial engineering vocabulary expansion", "variantOf": "", "grammarDomainAlias": "industrial", "qcRepairNotes": "CEFR C2 industrial gap filled; ergonomic assessment added"},
    {"term": "energy efficiency benchmarking report", "normalizedTerm": "energy efficiency benchmarking report", "turkishMeaning": "enerji verimliliği kıyaslama raporu", "cefrLevel": "C2", "domain": "industrial", "contentDomain": "engineering", "lifeContext": "workplace", "register": "formal", "primaryUseCase": "work-report", "category": "environment", "termType": "multiword_term", "partOfSpeech": "multiword_term", "wordCount": 4, "definition": "A comparative analysis document that measures energy consumption against industry best practices and regulatory targets to identify improvement opportunities.", "exampleSentence": "The energy efficiency benchmarking report demonstrated a 20 percent gap compared to industry leaders.", "turkishExample": "Enerji verimliliği kıyaslama raporu sektör liderlerine göre yüzde 20 fark gösterdi.", "relatedTerms": "energy audit, carbon footprint, energy management system", "commonMistakes": "not to compare facilities with different production volumes directly", "grammarFits": "formal reporting, passive voice", "skillUse": "reading, writing, speaking, vocabulary", "tags": "c2, industrial, environment, engineering, multiword_term", "source": "EngineerOS gap-fill batch 2026", "confidence": 0.94, "status": "approved", "importTier": "professional_phrase", "isCore": False, "isTechnical": True, "isProfessionalPhrase": True, "isContractual": False, "isDailySiteEnglish": False, "isLifeWideEnglish": False, "reviewReason": "CEFR C2 gap-fill: industrial engineering vocabulary expansion", "variantOf": "", "grammarDomainAlias": "industrial", "qcRepairNotes": "CEFR C2 industrial gap filled; energy benchmarking added"},
    {"term": "continuous improvement culture assessment", "normalizedTerm": "continuous improvement culture assessment", "turkishMeaning": "sürekli iyileştirme kültürü değerlendirmesi", "cefrLevel": "C2", "domain": "industrial", "contentDomain": "engineering", "lifeContext": "workplace", "register": "formal", "primaryUseCase": "inspection", "category": "quality management", "termType": "multiword_term", "partOfSpeech": "multiword_term", "wordCount": 4, "definition": "An organizational evaluation that measures employee engagement, leadership commitment, and systematic problem-solving in continuous improvement initiatives.", "exampleSentence": "The continuous improvement culture assessment revealed gaps in management commitment and employee training.", "turkishExample": "Sürekli iyileştirme kültürü değerlendirmesi yönetim bağlılığı ve çalışan eğitimindeki eksiklikleri ortaya çıkardı.", "relatedTerms": "kaizen, organizational culture, leadership commitment", "commonMistakes": "not to treat as a one-time survey but as ongoing measurement", "grammarFits": "formal reporting, passive voice", "skillUse": "reading, writing, vocabulary", "tags": "c2, industrial, quality, engineering, multiword_term", "source": "EngineerOS gap-fill batch 2026", "confidence": 0.92, "status": "approved", "importTier": "professional_phrase", "isCore": False, "isTechnical": True, "isProfessionalPhrase": True, "isContractual": False, "isDailySiteEnglish": False, "isLifeWideEnglish": False, "reviewReason": "CEFR C2 gap-fill: industrial engineering vocabulary expansion", "variantOf": "", "grammarDomainAlias": "industrial", "qcRepairNotes": "CEFR C2 industrial gap filled; improvement culture assessment added"},
]

# Mechatronics için C2 terimleri
gap_terms_mechatronics = [
    {"term": "mechatronics system integration framework", "normalizedTerm": "mechatronics system integration framework", "turkishMeaning": "mekatronik sistem entegrasyon çerçevesi", "cefrLevel": "C2", "domain": "mechatronics", "contentDomain": "engineering", "lifeContext": "site", "register": "technical", "primaryUseCase": "site-task", "category": "mechatronics fundamentals", "termType": "multiword_term", "partOfSpeech": "multiword_term", "wordCount": 5, "definition": "A structured methodology for combining mechanical engineering, electronics, control systems, and software engineering into a unified system design.", "exampleSentence": "The mechatronics system integration framework guided the design from concept through commissioning.", "turkishExample": "Mekatronik sistem entegrasyon çerçevesi tasarımdan devreye almaya kadar rehberlik etti.", "relatedTerms": "system design, interdisciplinary engineering, system architecture", "commonMistakes": "do not treat integration as simple component assembly", "grammarFits": "technical reporting, passive voice", "skillUse": "reading, writing, vocabulary", "tags": "c2, mechatronics, fundamentals, engineering, multiword_term", "source": "EngineerOS gap-fill batch 2026", "confidence": 0.93, "status": "approved", "importTier": "technical_term", "isCore": False, "isTechnical": True, "isProfessionalPhrase": False, "isContractual": False, "isDailySiteEnglish": False, "isLifeWideEnglish": False, "reviewReason": "CEFR C2 gap-fill: mechatronics vocabulary expansion", "variantOf": "", "grammarDomainAlias": "mechatronics", "qcRepairNotes": "CEFR C2 mechatronics gap filled; integration framework added"},
    {"term": "embedded control system design", "normalizedTerm": "embedded control system design", "turkishMeaning": "gömülü kontrol sistemi tasarımı", "cefrLevel": "C2", "domain": "mechatronics", "contentDomain": "engineering", "lifeContext": "site", "register": "technical", "primaryUseCase": "site-task", "category": "plc control", "termType": "multiword_term", "partOfSpeech": "multiword_term", "wordCount": 4, "definition": "The engineering discipline focused on designing microprocessor-based controllers that manage mechanical systems in real time.", "exampleSentence": "Embedded control system design demands careful timing analysis and real-time operating system selection.", "turkishExample": "Gömülü kontrol sistemi tasarımı dikkatli zamanlama analizi ve gerçek zamanlı işletim sistemi seçimi gerektirir.", "relatedTerms": "real-time system, firmware, microcontroller", "commonMistakes": "not to underestimate real-time constraints", "grammarFits": "technical reporting, modal obligation", "skillUse": "reading, writing, vocabulary", "tags": "c2, mechatronics, plc, engineering, multiword_term", "source": "EngineerOS gap-fill batch 2026", "confidence": 0.91, "status": "approved", "importTier": "technical_term", "isCore": False, "isTechnical": True, "isProfessionalPhrase": False, "isContractual": False, "isDailySiteEnglish": False, "isLifeWideEnglish": False, "reviewReason": "CEFR C2 gap-fill: mechatronics vocabulary expansion", "variantOf": "", "grammarDomainAlias": "mechatronics", "qcRepairNotes": "CEFR C2 mechatronics gap filled; embedded control added"},
    {"term": "robotic kinematics optimization", "normalizedTerm": "robotic kinematics optimization", "turkishMeaning": "robotik kinematik optimizasyonu", "cefrLevel": "C2", "domain": "mechatronics", "contentDomain": "engineering", "lifeContext": "site", "register": "technical", "primaryUseCase": "site-task", "category": "robot kinematics", "termType": "multiword_term", "partOfSpeech": "multiword_term", "wordCount": 3, "definition": "A mathematical optimization process that determines the most efficient trajectory and joint configurations for robotic manipulators.", "exampleSentence": "Robotic kinematics optimization minimizes cycle time while avoiding singular configurations.", "turkishExample": "Robotik kinematik optimizasyonu tekil konfigürasyonlardan kaçınarak döngü süresini en aza indirir.", "relatedTerms": "inverse kinematics, trajectory planning, singularity", "commonMistakes": "not to ignore joint limits during optimization", "grammarFits": "technical reporting, modal obligation", "skillUse": "reading, writing, vocabulary", "tags": "c2, mechatronics, robot, engineering, multiword_term", "source": "EngineerOS gap-fill batch 2026", "confidence": 0.94, "status": "approved", "importTier": "technical_term", "isCore": False, "isTechnical": True, "isProfessionalPhrase": False, "isContractual": False, "isDailySiteEnglish": False, "isLifeWideEnglish": False, "reviewReason": "CEFR C2 gap-fill: mechatronics vocabulary expansion", "variantOf": "", "grammarDomainAlias": "mechatronics", "qcRepairNotes": "CEFR C2 mechatronics gap filled; kinematics optimization added"},
    {"term": "sensor fusion algorithms", "normalizedTerm": "sensor fusion algorithms", "turkishMeaning": "sensör füzyon algoritmaları", "cefrLevel": "C2", "domain": "mechatronics", "contentDomain": "engineering", "lifeContext": "site", "register": "technical", "primaryUseCase": "site-task", "category": "sensors", "termType": "two_word_term", "partOfSpeech": "multiword_term", "wordCount": 3, "definition": "Computational methods that combine data from multiple sensors to produce more accurate, reliable, and comprehensive information than any individual sensor.", "exampleSentence": "Sensor fusion algorithms integrate vision, inertial, and force feedback for robust robot guidance.", "turkishExample": "Sensör füzyon algoritmaları görsel, ataletsel ve kuvvet geri bildirimi verilerini entegre eder.", "relatedTerms": "Kalman filter, data fusion, multi-sensor system", "commonMistakes": "do not assume simple averaging achieves fusion", "grammarFits": "technical reporting, simple present", "skillUse": "reading, writing, vocabulary", "tags": "c2, mechatronics, sensors, engineering, two_word_term", "source": "EngineerOS gap-fill batch 2026", "confidence": 0.93, "status": "approved", "importTier": "technical_term", "isCore": False, "isTechnical": True, "isProfessionalPhrase": False, "isContractual": False, "isDailySiteEnglish": False, "isLifeWideEnglish": False, "reviewReason": "CEFR C2 gap-fill: mechatronics vocabulary expansion", "variantOf": "", "grammarDomainAlias": "mechatronics", "qcRepairNotes": "CEFR C2 mechatronics gap filled; sensor fusion algorithms added"},
    {"term": "actuator dynamics modeling", "normalizedTerm": "actuator dynamics modeling", "turkishMeaning": "aktüatör dinamiği modellemesi", "cefrLevel": "C2", "domain": "mechatronics", "contentDomain": "engineering", "lifeContext": "site", "register": "technical", "primaryUseCase": "site-task", "category": "actuators motors", "termType": "two_word_term", "partOfSpeech": "multiword_term", "wordCount": 3, "definition": "The mathematical representation of actuator behavior including electrical, mechanical, and thermal dynamics for precise control design.", "exampleSentence": "Actuator dynamics modeling is essential for high-performance motion control applications.", "turkishExample": "Aktüatör dinamiği modellemesi yüksek performanslı hareket kontrol uygulamaları için esastır.", "relatedTerms": "transfer function, state-space model, parameter identification", "commonMistakes": "not to neglect thermal effects in high-duty applications", "grammarFits": "passive voice, technical reporting", "skillUse": "reading, writing, vocabulary", "tags": "c2, mechatronics, actuators, engineering, two_word_term", "source": "EngineerOS gap-fill batch 2026", "confidence": 0.92, "status": "approved", "importTier": "technical_term", "isCore": False, "isTechnical": True, "isProfessionalPhrase": False, "isContractual": False, "isDailySiteEnglish": False, "isLifeWideEnglish": False, "reviewReason": "CEFR C2 gap-fill: mechatronics vocabulary expansion", "variantOf": "", "grammarDomainAlias": "mechatronics", "qcRepairNotes": "CEFR C2 mechatronics gap filled; actuator dynamics modeling added"},
    {"term": "mechatronic design verification protocol", "normalizedTerm": "mechatronic design verification protocol", "turkishMeaning": "mekatronik tasarım doğrulama protokolü", "cefrLevel": "C2", "domain": "mechatronics", "contentDomain": "engineering", "lifeContext": "workplace", "register": "formal", "primaryUseCase": "inspection", "category": "quality", "termType": "multiword_term", "partOfSpeech": "multiword_term", "wordCount": 4, "definition": "A formal procedure that validates that a mechatronic system design meets all specified requirements through systematic testing, simulation, and review.", "exampleSentence": "The mechatronic design verification protocol includes simulation verification, hardware-in-the-loop testing, and field trials.", "turkishExample": "Mekatronik tasarım doğrulama protokolü simülasyon doğrulaması, donanım döngüsü testleri ve saha denemelerini içerir.", "relatedTerms": "verification and validation, design review, testing protocol", "commonMistakes": "not to verify only individual components but the integrated system", "grammarFits": "formal reporting, passive voice", "skillUse": "reading, writing, vocabulary", "tags": "c2, mechatronics, quality, engineering, multiword_term", "source": "EngineerOS gap-fill batch 2026", "confidence": 0.93, "status": "approved", "importTier": "technical_term", "isCore": False, "isTechnical": True, "isProfessionalPhrase": False, "isContractual": False, "isDailySiteEnglish": False, "isLifeWideEnglish": False, "reviewReason": "CEFR C2 gap-fill: mechatronics vocabulary expansion", "variantOf": "", "grammarDomainAlias": "mechatronics", "qcRepairNotes": "CEFR C2 mechatronics gap filled; design verification protocol added"},
    {"term": "real-time operating system selection", "normalizedTerm": "real-time operating system selection", "turkishMeaning": "gerçek zamanlı işletim sistemi seçimi", "cefrLevel": "C2", "domain": "mechatronics", "contentDomain": "engineering", "lifeContext": "site", "register": "technical", "primaryUseCase": "site-task", "category": "plc control", "termType": "multiword_term", "partOfSpeech": "multiword_term", "wordCount": 5, "definition": "The engineering process of evaluating and selecting an operating system that guarantees deterministic response times for embedded mechatronic applications.", "exampleSentence": "Real-time operating system selection must consider task scheduling algorithms, interrupt latency, and resource management.", "turkishExample": "Gerçek zamanlı işletim sistemi seçimi görev zamanlama algoritmalarını, kesme gecikmesini ve kaynak yönetimini dikkate almalıdır.", "relatedTerms": "RTOS, task scheduling, interrupt handling", "commonMistakes": "not to select based solely on market popularity", "grammarFits": "modal obligation, technical reporting", "skillUse": "reading, writing, vocabulary", "tags": "c2, mechatronics, plc, engineering, multiword_term", "source": "EngineerOS gap-fill batch 2026", "confidence": 0.94, "status": "approved", "importTier": "technical_term", "isCore": False, "isTechnical": True, "isProfessionalPhrase": False, "isContractual": False, "isDailySiteEnglish": False, "isLifeWideEnglish": False, "reviewReason": "CEFR C2 gap-fill: mechatronics vocabulary expansion", "variantOf": "", "grammarDomainAlias": "mechatronics", "qcRepairNotes": "CEFR C2 mechatronics gap filled; RTOS selection added"},
    {"term": "precision motion control system", "normalizedTerm": "precision motion control system", "turkishMeaning": "hassas hareket kontrol sistemi", "cefrLevel": "C2", "domain": "mechatronics", "contentDomain": "engineering", "lifeContext": "site", "register": "technical", "primaryUseCase": "site-task", "category": "actuators motors", "termType": "multiword_term", "partOfSpeech": "multiword_term", "wordCount": 4, "definition": "A high-accuracy control system that manages position, velocity, and torque of mechanical actuators with minimal error and fast response.", "exampleSentence": "The precision motion control system achieves sub-micron positioning accuracy using closed-loop feedback.", "turkishExample": "Hassas hareket kontrol sistemi kapalı döngü geri bildirimi kullanarak alt mikron konumlandırma doğruluğu sağlar.", "relatedTerms": "servo control, closed-loop feedback, encoder resolution", "commonMistakes": "not to neglect encoder resolution and backlash compensation", "grammarFits": "technical reporting, simple present", "skillUse": "reading, writing, vocabulary", "tags": "c2, mechatronics, actuators, engineering, multiword_term", "source": "EngineerOS gap-fill batch 2026", "confidence": 0.95, "status": "approved", "importTier": "technical_term", "isCore": False, "isTechnical": True, "isProfessionalPhrase": False, "isContractual": False, "isDailySiteEnglish": False, "isLifeWideEnglish": False, "reviewReason": "CEFR C2 gap-fill: mechatronics vocabulary expansion", "variantOf": "", "grammarDomainAlias": "mechatronics", "qcRepairNotes": "CEFR C2 mechatronics gap filled; precision motion added"},
    {"term": "mechatronic failure mode analysis", "normalizedTerm": "mechatronic failure mode analysis", "turkishMeaning": "mekatronik arıza modu analizi", "cefrLevel": "C2", "domain": "mechatronics", "contentDomain": "engineering", "lifeContext": "workplace", "register": "formal", "primaryUseCase": "inspection", "category": "quality", "termType": "multiword_term", "partOfSpeech": "multiword_term", "wordCount": 4, "definition": "A systematic analysis that identifies potential failure mechanisms in mechatronic systems, their effects, and mitigation strategies.", "exampleSentence": "The mechatronic failure mode analysis identified critical points requiring redundant sensor configurations.", "turkishExample": "Mekatronik arıza modu analizi yedek sensör konfigürasyonları gerektiren kritik noktaları belirledi.", "relatedTerms": "FMEA, reliability engineering, risk analysis", "commonMistakes": "not to limit analysis to mechanical failures only", "grammarFits": "formal reporting, passive voice", "skillUse": "reading, writing, vocabulary", "tags": "c2, mechatronics, quality, engineering, multiword_term", "source": "EngineerOS gap-fill batch 2026", "confidence": 0.92, "status": "approved", "importTier": "technical_term", "isCore": False, "isTechnical": True, "isProfessionalPhrase": False, "isContractual": False, "isDailySiteEnglish": False, "isLifeWideEnglish": False, "reviewReason": "CEFR C2 gap-fill: mechatronics vocabulary expansion", "variantOf": "", "grammarDomainAlias": "mechatronics", "qcRepairNotes": "CEFR C2 mechatronics gap filled; failure mode analysis added"},
    {"term": "digital twin implementation strategy", "normalizedTerm": "digital twin implementation strategy", "turkishMeaning": "dijital ikiz uygulama stratejisi", "cefrLevel": "C2", "domain": "mechatronics", "contentDomain": "engineering", "lifeContext": "site", "register": "technical", "primaryUseCase": "work-report", "category": "automation", "termType": "multiword_term", "partOfSpeech": "multiword_term", "wordCount": 4, "definition": "A strategic plan for creating and maintaining virtual replicas of physical mechatronic systems to enable real-time monitoring, simulation, and predictive analysis.", "exampleSentence": "The digital twin implementation strategy connects physical assets to their virtual counterparts through continuous data streams.", "turkishExample": "Dijital ikiz uygulama stratejisi fiziksel varlıkları sürekli veri akışları aracılığıyla sanal karşılıklarına bağlar.", "relatedTerms": "IoT, simulation, predictive analytics", "commonMistakes": "not to treat digital twin as only 3D visualization", "grammarFits": "formal reporting, technical reporting", "skillUse": "reading, writing, vocabulary", "tags": "c2, mechatronics, automation, engineering, multiword_term", "source": "EngineerOS gap-fill batch 2026", "confidence": 0.93, "status": "approved", "importTier": "technical_term", "isCore": False, "isTechnical": True, "isProfessionalPhrase": False, "isContractual": False, "isDailySiteEnglish": False, "isLifeWideEnglish": False, "reviewReason": "CEFR C2 gap-fill: mechatronics vocabulary expansion", "variantOf": "", "grammarDomainAlias": "mechatronics", "qcRepairNotes": "CEFR C2 mechatronics gap filled; digital twin strategy added"},
]

# Yeni terimleri DataFrame'e ekle
new_ind = pd.DataFrame(gap_terms_industrial)
new_mech = pd.DataFrame(gap_terms_mechatronics)
new_all = pd.concat([new_ind, new_mech], ignore_index=True)

# Benzersiz ID'ler oluştur
df['id_prefix'] = df['domain'].str.replace('general-english', 'EngGen')
baseline_max = df['id'].str.extract(r'(\d+)$').astype(float).max()[0] if not df['id'].str.extract(r'(\d+)$').empty else 1000

new_all_ids = []
for i, (domain, level) in enumerate(zip(new_all['domain'], new_all['cefrLevel'])):
    domain_code = domain[:3] if domain != 'general-english' else 'EngGen'
    new_all_ids.append(f"vocab_{domain}_{level.lower()}_{int(baseline_max)+i+1:04d}")
new_all.insert(0, 'id', new_all_ids)

# Yeni veriyi birleştir (temizlenmiş + yeni)
final_df = pd.concat([clean_df, new_all], ignore_index=True)

print(f"\nYeni eklenen C2 terim: {len(new_all)} (Industrial: {len(new_ind)}, Mechatronics: {len(new_mech)})")
print(f"Son veri boyutu: {len(final_df)}")

# Final veri export
final_df.to_csv(os.path.join(output_dir, 'genel7_final.csv'), index=False, encoding='utf-8')
final_df.to_json(os.path.join(output_dir, 'genel8.json'), orient='records', force_ascii=False, indent=2)

# ============================================================
# GENE8 ÖZET DOSYASI OLUŞTUR
# ============================================================
with open(os.path.join(output_dir, 'gene8_summary.txt'), 'w', encoding='utf-8') as f:
    f.write("=" * 80 + "\n")
    f.write("GENEL8 - GENEL7 ANALİZ SONUÇ DOSYASI\n")
    f.write("=" * 80 + "\n")
    f.write(f"Oluşturulma Tarihi: 2026-07-30\n")
    f.write(f"Orijinal Veri: Genel7.xlsx (14,622 kayıt)\n")
    f.write(f"Temizlenmiş Veri: genel7_final.csv ({len(final_df)} kayıt)\n")
    f.write(f"Yeni Kayıt (gene8): genel8.json ({len(new_all)} kayıt)\n\n")
    
    f.write("DUPLICATE TEMİZLEME SONUCU:\n")
    f.write(f"  - Çıkarılan kayıt: {len(df) - len(clean_df)}\n")
    f.write(f"  - Kalan kayıt: {len(clean_df)}\n")
    top_dup_term = dup_groups.sort_values('count', ascending=False).iloc[0]['term'] if len(dup_groups) > 0 else "Yok"
    top_dup_count = dup_groups.sort_values('count', ascending=False).iloc[0]['count'] if len(dup_groups) > 0 else 0
    f.write(f"  - En çok tekrar: {top_dup_term} ({top_dup_count} kez)\n\n")
    
    f.write("CEFR GAP DOLDURMA SONUCU:\n")
    f.write(f"  - Industrial C2 yeni terim: {len(new_ind)}\n")
    f.write(f"  - Mechatronics C2 yeni terim: {len(new_mech)}\n")
    
    ind_before = len(ind_c2)
    mech_before = len(mech_c2)
    f.write(f"  - Industrial C2 önce: {ind_before}, sonra: {ind_before + len(new_ind)}\n")
    f.write(f"  - Mechatronics C2 önce: {mech_before}, sonra: {mech_before + len(new_mech)}\n")
    
    f.write("\nYENİ TERİM ÖRNEKLERİ:\n")
    for _, row in new_all.head(10).iterrows():
        f.write(f"  [{row['cefrLevel']}] [{row['domain']}] {row['term']} -> {row['turkishMeaning']}\n")
    
    f.write("\nÇIKTI DOSYALARI:\n")
    f.write("  - genel7_cleaned.csv\n")
    f.write("  - duplicate_removal_report.csv\n")
    f.write("  - genel7_final.csv (temiz + gap-fill birleşik)\n")
    f.write("  - genel8.json (yeni C2 terimleri)\n")
    f.write("  - gene8_summary.txt (bu dosya)\n")

print("\n=== GENE8 TAMAMLANDI ===")
print(f"  - genel7_final.csv: {len(final_df)} kayıt (temizlenmiş + yeni)")
print(f"  - genel8.json: {len(new_all)} yeni C2 terim")
print(f"  - gene8_summary.txt: oluşturuldu")
