export default {
  extends: ['@commitlint/config-conventional'],
  rules: {
    'type-enum': [
      2,
      'always',
      [
        'feat',
        'fix',
        'refactor',
        'docs',
        'test',
        'chore',
        'style',
        'perf',
        'ci',
        'build',
        'revert',
      ],
    ],
    'scope-enum': [
      1,
      'always',
      [
        'frontend',
        'backend',
        'auth',
        'billing',
        'ai',
        'vocabulary',
        'grammar',
        'reading',
        'writing',
        'listening',
        'speaking',
        'profile',
        'dashboard',
        'progress',
        'curriculum',
        'placement',
        'gamification',
        'team',
        'analytics',
        'work-tools',
        'level-system',
        'learning-orchestrator',
        'learning-intelligence',
        'ui',
        'config',
        'deps',
        'security',
      ],
    ],
    'subject-case': [0],
    'body-max-line-length': [0],
    'header-max-length': [2, 'always', 100],
  },
};
