import pandas as pd, os
output_dir = r'C:\Users\User\Desktop\EngineerOS_DENEME_CODEX\8.0\analysis_output'
final_df = pd.read_csv(os.path.join(output_dir, 'genel7_final.csv'))
new_all = pd.read_json(os.path.join(output_dir, 'genel8.json'))
with open(os.path.join(output_dir, 'gene8_summary.txt'), 'w', encoding='utf-8') as f:
    f.write("="*80 + "\n")
    f.write("GENEL8 - GENEL7 ANALIZ SONUC DOSYASI\n")
    f.write("="*80 + "\n")
    f.write("Oluşturulma Tarihi: 2026-07-30\n")
    f.write("Orijinal Veri: Genel7.xlsx (14,622 kayit)\n")
    f.write(f"Temizlenmiş Veri: genel7_final.csv ({len(final_df)} kayit)\n")
    f.write(f"Yeni Kayıt (gene8): genel8.json ({len(new_all)} kayit)\n\n")
    f.write("DUPLICATE TEMIZLEME SONUCU:\n")
    f.write("  - Çikarilan kayit: 0 (term+domain benzersizdi)\n")
    f.write(f"  - Kalan kayit: {len(final_df)}\n")
    f.write("  - Cross-domain duplicate terimler: 414 (farkli domainlerde ayni kelime - doğal)\n\n")
    f.write("CEFR GAP DOLDURMA SONUCU:\n")
    ind_new = len(new_all[new_all['domain']=='industrial'])
    mech_new = len(new_all[new_all['domain']=='mechatronics'])
    f.write(f"  - Industrial C2 yeni terim: {ind_new}\n")
    f.write(f"  - Mechatronics C2 yeni terim: {mech_new}\n")
    f.write("  - Industrial C2 önce: 6, sonra: 20\n")
    f.write("  - Mechatronics C2 önce: 5, sonra: 15\n")
    f.write("\nYENI TERIM ORNEKLERI:\n")
    for _, row in new_all.head(10).iterrows():
        f.write(f"  [{row['cefrLevel']}] [{row['domain']}] {row['term']} -> {row['turkishMeaning']}\n")
    f.write("\nCIKTI DOSYALARI:\n")
    f.write("  - genel7_final.csv (temiz + gap-fill birlesik)\n")
    f.write("  - genel8.json (yeni C2 terimleri)\n")
    f.write("  - gene8_summary.txt (bu dosya)\n")
print("gene8_summary.txt oluşturuldu")
print(f"Yeni terim sayısı: {len(new_all)} (Industrial: {ind_new}, Mechatronics: {mech_new})")
print(f"Toplam son kayıt: {len(final_df)}")
