/** @type {import('@stryker-mutator/api/core').PartialStrykerOptions} */
const config = {
  testRunner: 'vitest',
  coverageAnalysis: 'perTest',
  mutator: {
    plugins: ['typescript', 'javascript'],
    excludedMutations: ['BooleanLiteral', 'StringLiteral'],
  },
  reporters: ['clear-text', 'html'],
  htmlReporter: {
    fileName: 'reports/mutation-report.html',
  },
  thresholds: {
    high: 80,
    low: 60,
    break: null,
  },
  mutate: [
    'src/shared/utils/cn.ts',
    'src/shared/hooks/useFocusTrap.ts',
    'src/shared/hooks/useKeyboardNavigation.ts',
    'src/config/navigation.config.ts',
    'src/config/product.config.ts',
    'src/config/feature-flags.config.ts',
    'src/core/result/result.helpers.ts',
    'src/core/validation/validation.helpers.ts',
    'src/core/ids/id.service.ts',
    'src/core/learning/spaced-repetition.helpers.ts',
    'src/core/events/event-bus.ts',
    'src/core/learning/learning.store.ts',
    'src/features/vocabulary/vocabulary.helpers.ts',
    'src/features/vocabulary/vocabulary.spaced-repetition.ts',
    'src/features/vocabulary/services/vocabulary.progress.ts',
    'src/features/vocabulary/services/vocabulary.search.ts',
    'src/features/billing/billing.helpers.ts',
    'src/features/billing/billing.entitlements.ts',
    'src/features/billing/billing.catalog.ts',
    'src/features/auth/auth.adapter.ts',
    'src/features/auth/conflict-resolver.ts',
    'src/features/grammar/grammar.progress.ts',
    'src/features/learning-orchestrator/learning-path-advisor.ts',
    'src/features/learning-intelligence/knowledge-capture.service.ts',
    'src/features/ai/ai-teacher.service.ts',
    'src/features/speaking/speaking.service.ts',
    'src/features/assessment/assessment.helpers.ts',
    'src/features/profile/profile.engine.ts',
    'src/features/profile/profile.preferences.ts',
    'src/features/offline/offline.service.ts',
    'src/features/gamification/gamification.service.ts',
    'src/features/placement/placement.service.ts',
    'src/features/localization/localization.service.ts',
    'src/features/writing/writing.service.ts',
    'src/features/reading/reading.service.ts',
    'src/features/listening/listening.service.ts',
    'src/features/analytics/analytics.service.ts',
    'src/features/team/team.service.ts',
    'src/features/level-system/content-gating.ts',
  ],
  ignorePatterns: [
    '**/*.test.ts',
    '**/*.test.tsx',
    '**/*.d.ts',
    '**/node_modules/**',
    '**/dist/**',
  ],
  timeoutMS: 30000,
  concurrency: 1,
};

export default config;
