/** @type {import('@stryker-mutator/api/core').PartialStrykerOptions} */
const config = {
  testRunner: 'vitest',
  coverageAnalysis: 'perTest',
  mutator: {
    plugins: ['typescript', 'javascript'],
    excludedMutations: ['BooleanLiteral', 'StringLiteral'],
  },
  reporters: ['clear-text', 'html'],
  htmlReporter: {
    fileName: 'reports/mutation-report.html',
  },
  thresholds: {
    high: 80,
    low: 60,
    break: null,
  },
  mutate: [
    'src/shared/utils/*.ts',
    'src/shared/hooks/*.ts',
    'src/config/*.ts',
    'src/core/**/*.ts',
    'src/features/vocabulary/**/*.ts',
    'src/features/billing/**/*.ts',
    'src/features/auth/**/*.ts',
    'src/features/grammar/**/*.ts',
    'src/features/learning-orchestrator/**/*.ts',
    'src/features/learning-intelligence/**/*.ts',
    'src/features/ai/**/*.ts',
    'src/features/speaking/**/*.ts',
    'src/features/assessment/**/*.ts',
    'src/features/profile/**/*.ts',
    'src/features/offline/**/*.ts',
    'src/features/gamification/**/*.ts',
    'src/features/placement/**/*.ts',
    'src/features/localization/**/*.ts',
    'src/features/writing/**/*.ts',
    'src/features/reading/**/*.ts',
    'src/features/listening/**/*.ts',
    'src/features/analytics/**/*.ts',
    'src/features/team/**/*.ts',
    'src/features/level-system/**/*.ts',
  ],
  ignorePatterns: [
    '**/*.test.ts',
    '**/*.test.tsx',
    '**/*.d.ts',
    '**/node_modules/**',
    '**/dist/**',
  ],
  timeoutMS: 30000,
  concurrency: 4,
};

export default config;
