import type {
  ListeningLessonDefinition,
  RoleplayScenarioDefinition,
  WritingTaskDefinition,
} from './content-library.types';

const listeningSeeds = [
  [
    'Morning Site Access',
    'A1',
    'Daily site communication',
    'A supervisor confirms the work area and access time.',
    'The electrical team can enter Room A at eight. Wear your helmet and sign the access sheet before you start.',
    ['access sheet', 'helmet'],
    'What must the team sign?',
    'The access sheet',
  ],
  [
    'Tool Delivery Check',
    'A1',
    'Procurement/delivery',
    'A storekeeper checks a small delivery.',
    'The delivery has six cable drums and two boxes of glands. One box is wet, so keep it separate.',
    ['cable drum', 'gland'],
    'Which item must be kept separate?',
    'The wet box',
  ],
  [
    'Safe Work Area',
    'A1',
    'Safety',
    'A safety officer gives a simple instruction.',
    'The floor is dry and the emergency exit is clear. Put the warning sign near the open panel.',
    ['emergency exit', 'warning sign'],
    'Where should the warning sign go?',
    'Near the open panel',
  ],
  [
    'Daily Progress Call',
    'A2',
    'Daily site communication',
    'A foreman reports completed work.',
    'We installed twelve metres of conduit on Level Two. The last section is waiting for a wall opening.',
    ['conduit', 'wall opening'],
    'Why is the last section waiting?',
    'It needs a wall opening',
  ],
  [
    'Inspection Time Change',
    'A2',
    'Inspection',
    'The consultant changes an inspection time.',
    'The panel inspection will start at three instead of two. Please finish the labels and bring the approved drawing.',
    ['panel inspection', 'approved drawing'],
    'What must the contractor bring?',
    'The approved drawing',
  ],
  [
    'Missing Delivery Note',
    'A2',
    'Procurement/delivery',
    'A receiver explains a document problem.',
    'The pumps arrived this morning, but the driver did not provide the delivery note. We cannot accept the shipment yet.',
    ['delivery note', 'shipment'],
    'Why can the shipment not be accepted?',
    'The delivery note is missing',
  ],
  [
    'Cable Tray Coordination',
    'B1',
    'Design coordination',
    'Two engineers coordinate ceiling services.',
    'The cable tray conflicts with the chilled-water pipe above Corridor C. Move the tray 150 millimetres south and update the coordination drawing.',
    ['conflict', 'coordination drawing'],
    'What change is required?',
    'Move the tray 150 millimetres south',
  ],
  [
    'Inspection Observation',
    'B1',
    'QA/QC',
    'A consultant records a quality observation.',
    'Three supports exceed the approved spacing. Correct the spacing, photograph each location and request reinspection before closing the ceiling.',
    ['approved spacing', 'reinspection'],
    'What evidence is requested?',
    'Photographs of each corrected location',
  ],
  [
    'Generator Pre-Start',
    'B1',
    'Commissioning',
    'A commissioning engineer reviews prerequisites.',
    'Before the generator starts, confirm the fuel level, battery voltage and emergency-stop reset. Record each value on the pre-start sheet.',
    ['pre-start sheet', 'emergency stop'],
    'Where should the values be recorded?',
    'On the pre-start sheet',
  ],
  [
    'Weekly Progress Risk',
    'B1',
    'Progress meeting',
    'A planner highlights a schedule risk.',
    'Containment installation is two days behind because the access platform arrived late. The recovery plan adds a second evening crew.',
    ['recovery plan', 'evening crew'],
    'How will the team recover time?',
    'By adding a second evening crew',
  ],
  [
    'Permit Suspension',
    'B1',
    'Safety',
    'A permit holder stops work safely.',
    'Stop cable pulling in Zone Four. The gas detector alarmed during the check, so the permit is suspended until HSE clears the area.',
    ['permit suspension', 'gas detector'],
    'Who must clear the area?',
    'HSE',
  ],
  [
    'Client Room Walkdown',
    'B1',
    'Client/consultant communication',
    'A client requests closeout evidence.',
    'During tomorrow’s walkdown, show the corrected labels, test certificates and signed punch-list closure for each electrical room.',
    ['walkdown', 'punch-list closure'],
    'Which closure record is needed?',
    'The signed punch-list closure',
  ],
  [
    'Fire Alarm Interface Test',
    'B2',
    'Commissioning',
    'The team reviews an interface failure.',
    'The fire alarm command reached the BMS, but the smoke-control fan did not start. Check the interlock matrix and repeat the cause-and-effect test.',
    ['interlock matrix', 'cause-and-effect test'],
    'Which document should be checked?',
    'The interlock matrix',
  ],
  [
    'NCR Corrective Action',
    'B2',
    'QA/QC',
    'A quality manager reviews an NCR response.',
    'The response identifies the wrong cable lug as the immediate cause, but it does not explain how stores will prevent recurrence. Add a controlled material-verification step.',
    ['corrective action', 'prevent recurrence'],
    'What is missing from the response?',
    'A prevention control for stores',
  ],
  [
    'Consultant RFI Review',
    'B2',
    'Client/consultant communication',
    'A consultant discusses an incomplete RFI.',
    'The RFI describes the ceiling conflict but gives no preferred solution. Attach the coordinated section and state the programme impact of each option.',
    ['preferred solution', 'programme impact'],
    'What drawing should be attached?',
    'The coordinated section',
  ],
  [
    'Transformer Energization Brief',
    'B2',
    'Commissioning',
    'A lead engineer briefs the energization team.',
    'Energization can proceed after protection settings, earthing continuity and phase rotation are independently witnessed. Any open hold point stops the sequence.',
    ['hold point', 'phase rotation'],
    'What stops the energization sequence?',
    'Any open hold point',
  ],
  [
    'Material Submittal Status',
    'B2',
    'Procurement/delivery',
    'Procurement explains a submittal delay.',
    'The revised switchgear data are with the manufacturer, but the type-test certificates remain outstanding. Delivery cannot be released without consultant approval.',
    ['type-test certificate', 'delivery release'],
    'Why can delivery not be released?',
    'Consultant approval is still missing',
  ],
  [
    'Method Statement Concern',
    'B2',
    'Safety',
    'HSE challenges a lifting method.',
    'The method statement defines the crane capacity but omits the exclusion-zone layout and communication signals. Revise both sections before the toolbox talk.',
    ['exclusion zone', 'communication signal'],
    'What two sections must be revised?',
    'The exclusion-zone layout and communication signals',
  ],
  [
    'Integrated Systems Test',
    'C1',
    'Commissioning',
    'Stakeholders analyse an integrated test result.',
    'The sequence passed functionally, yet the timestamp variance between fire alarm and access control prevents reliable event reconstruction. Synchronize both systems to the approved time source.',
    ['timestamp variance', 'event reconstruction'],
    'Why must the systems be synchronized?',
    'To enable reliable event reconstruction',
  ],
  [
    'Delay Entitlement Discussion',
    'C1',
    'Progress meeting',
    'A project manager distinguishes cause and entitlement.',
    'Late design information affected procurement, but entitlement depends on contemporaneous notice and demonstrated critical-path impact. The chronology alone is insufficient.',
    ['contemporaneous notice', 'critical path'],
    'What evidence is required in addition to chronology?',
    'Notice and demonstrated critical-path impact',
  ],
  [
    'FAT Deviation Review',
    'C1',
    'QA/QC',
    'A team decides how to handle a FAT deviation.',
    'The protection relay passed functional injection, but the firmware differs from the approved schedule. Record the deviation and obtain written acceptance before shipment.',
    ['functional injection', 'written acceptance'],
    'What must happen before shipment?',
    'Written acceptance of the deviation',
  ],
  [
    'Handover Documentation Gap',
    'C1',
    'Handover',
    'The client reviews incomplete handover files.',
    'The O&M manuals are indexed, but asset tags do not reconcile with the final equipment schedule. Handover remains conditional until the register is corrected.',
    ['asset register', 'conditional handover'],
    'Why is handover conditional?',
    'Asset tags do not match the final schedule',
  ],
  [
    'Design Responsibility Boundary',
    'C1',
    'Design coordination',
    'Contractor and consultant clarify responsibility.',
    'The specification assigns performance design to the specialist, while spatial coordination remains with the main contractor. The interface schedule must reflect both obligations.',
    ['performance design', 'interface schedule'],
    'Who retains spatial coordination?',
    'The main contractor',
  ],
  [
    'Commissioning Trend Analysis',
    'C1',
    'Commissioning',
    'An engineer interprets unstable operating data.',
    'The pressure oscillation appears only during low-load operation and correlates with rapid valve hunting. Extend the trend interval before changing the control parameters.',
    ['valve hunting', 'trend interval'],
    'What should happen before parameters change?',
    'Extend the trend interval',
  ],
  [
    'Contractual Notice Wording',
    'C1',
    'Client/consultant communication',
    'A manager reviews a draft notice.',
    'The draft explains disruption but does not reserve contractual rights or identify the relevant instruction. Strengthen the notice without overstating unproven cost.',
    ['reserve rights', 'relevant instruction'],
    'What should the notice avoid overstating?',
    'Unproven cost',
  ],
  [
    'Root Cause Challenge',
    'C2',
    'QA/QC',
    'A review board challenges a superficial root cause.',
    'Operator error describes the event, not the system weakness that permitted it. Examine supervision, procedure design and verification controls before closing the investigation.',
    ['system weakness', 'verification control'],
    'Why is operator error insufficient?',
    'It does not identify the enabling system weakness',
  ],
  [
    'Commissioning Governance',
    'C2',
    'Commissioning',
    'Leaders resolve authority during a complex test.',
    'The test director controls sequence execution, while discipline leads retain authority to stop unsafe or noncompliant activity. The protocol must remove any ambiguity between those powers.',
    ['test director', 'stop-work authority'],
    'What ambiguity must the protocol remove?',
    'The boundary between sequence control and stop-work authority',
  ],
  [
    'Programme Narrative Audit',
    'C2',
    'Progress meeting',
    'A planner critiques a recovery narrative.',
    'The narrative attributes recovery to additional labour, yet the updated logic shows float consumption rather than critical-path improvement. Reconcile the claim with the programme evidence.',
    ['float consumption', 'programme logic'],
    'Why is the recovery claim questionable?',
    'The logic shows no critical-path improvement',
  ],
  [
    'Client Acceptance Strategy',
    'C2',
    'Handover',
    'A director plans phased acceptance.',
    'Phased acceptance can reduce operational risk only if residual obligations, access rights and defect responsibility remain explicit for every transferred area.',
    ['phased acceptance', 'residual obligation'],
    'What must remain explicit?',
    'Residual obligations, access rights and defect responsibility',
  ],
  [
    'Ethical Escalation',
    'C2',
    'Safety',
    'A senior engineer handles pressure to proceed.',
    'Commercial urgency does not justify bypassing a safety hold point. Document the instruction, escalate through governance and protect the team from retaliatory pressure.',
    ['safety hold point', 'governance escalation'],
    'What should the engineer document?',
    'The instruction to bypass the hold point',
  ],
] as const;

export const PROFESSIONAL_LISTENING_LESSONS: ListeningLessonDefinition[] =
  listeningSeeds.map((seed, index) => {
    const [
      title,
      cefrLevel,
      domain,
      scenario,
      transcript,
      vocabularyTargets,
      question,
      answer,
    ] = seed;
    return {
      id: `prc-listening-${String(index + 1).padStart(2, '0')}`,
      title,
      cefrLevel,
      domain,
      scenario,
      transcript,
      vocabularyTargets: [...vocabularyTargets],
      vocabularyIds: [],
      comprehensionQuestions: [
        {
          id: `prc-listening-${index + 1}-q1`,
          prompt: question,
          choices: [answer],
        },
      ],
      answerKey: [answer],
      status: 'script_ready',
    };
  });

const roleplaySeeds = [
  [
    'Confirm Site Access',
    'A1',
    'Site engineer',
    'A security guard asks where your team will work.',
    'State the room, team size and start time.',
    ['access', 'work area'],
    ['Omitting the room number'],
  ],
  [
    'Ask for a Tool',
    'A1',
    'Technician',
    'You need a torque wrench from the store.',
    'Request the tool and say when you will return it.',
    ['torque wrench', 'return'],
    ['Using only one-word requests'],
  ],
  [
    'Report a Safe Condition',
    'A1',
    'Supervisor',
    'A worker asks whether the room is safe.',
    'Confirm the isolation and give one instruction.',
    ['isolation', 'safe'],
    ['Giving no action instruction'],
  ],
  [
    'Give a Progress Update',
    'A2',
    'Foreman',
    'The coordinator asks what your team completed.',
    'Report quantity, location and next action.',
    ['installed', 'remaining'],
    ['Mixing completed and planned work'],
  ],
  [
    'Request Reinspection',
    'A2',
    'QA/QC engineer',
    'A minor defect has been corrected.',
    'Ask the consultant for a new inspection time.',
    ['rectified', 'reinspection'],
    ['Not identifying the location'],
  ],
  [
    'Clarify a Delivery',
    'A2',
    'Site engineer',
    'A driver has the wrong unloading gate.',
    'Give the correct gate and contact person.',
    ['delivery gate', 'contact person'],
    ['Giving unclear directions'],
  ],
  [
    'Explain a Ceiling Conflict',
    'B1',
    'MEP coordinator',
    'Cable tray conflicts with a pipe.',
    'Describe the conflict and propose one coordinated move.',
    ['clearance', 'offset'],
    ['Blaming another discipline'],
  ],
  [
    'Lead a Toolbox Talk',
    'B1',
    'Safety engineer',
    'The team will work near energized equipment.',
    'Explain the hazard, control and stop-work rule.',
    ['hazard', 'control measure'],
    ['Using vague safety language'],
  ],
  [
    'Respond to an Observation',
    'B1',
    'QA/QC engineer',
    'The consultant identifies missing labels.',
    'Acknowledge, state correction and promise evidence.',
    ['observation', 'evidence'],
    ['Arguing before confirming facts'],
  ],
  [
    'Update a Progress Meeting',
    'B1',
    'Project engineer',
    'An activity is two days late.',
    'State cause, impact and recovery action.',
    ['delay', 'recovery action'],
    ['Giving a cause without impact'],
  ],
  [
    'Prepare Generator Testing',
    'B1',
    'Commissioning engineer',
    'The client asks if testing can start.',
    'Confirm prerequisites and identify one open point.',
    ['prerequisite', 'open point'],
    ['Saying ready while an item is open'],
  ],
  [
    'Handle a Missing Document',
    'B1',
    'Procurement engineer',
    'Materials arrived without certificates.',
    'Explain the hold and request the missing records.',
    ['certificate', 'on hold'],
    ['Accepting materials conditionally without authority'],
  ],
  [
    'Defend an RFI Solution',
    'B2',
    'Design coordinator',
    'The consultant asks why your routing option is preferred.',
    'Compare options using clearance, access and programme impact.',
    ['preferred solution', 'programme impact'],
    ['Describing only one option'],
  ],
  [
    'Close an NCR Meeting',
    'B2',
    'Quality manager',
    'Corrective action is complete but prevention is unclear.',
    'Separate correction, root cause and recurrence prevention.',
    ['root cause', 'prevent recurrence'],
    ['Calling correction a root cause'],
  ],
  [
    'Explain a Commissioning Failure',
    'B2',
    'Commissioning lead',
    'An interface test failed at the BMS output.',
    'Explain observed result, boundary and next diagnostic step.',
    ['interface', 'diagnostic'],
    ['Claiming a cause before testing'],
  ],
  [
    'Negotiate Inspection Timing',
    'B2',
    'Site manager',
    'The consultant proposes a time before work is ready.',
    'Request a realistic time and explain readiness evidence.',
    ['readiness', 'inspection window'],
    ['Sounding dismissive'],
  ],
  [
    'Present a Delay Notice',
    'B2',
    'Project engineer',
    'Late information affected procurement.',
    'Explain chronology, impact and requested response professionally.',
    ['notice', 'critical activity'],
    ['Making unsupported cost claims'],
  ],
  [
    'Challenge an Unsafe Instruction',
    'B2',
    'Site supervisor',
    'A manager asks the team to bypass a hold point.',
    'Refuse professionally, cite the control and escalate.',
    ['hold point', 'escalate'],
    ['Using confrontational language'],
  ],
  [
    'Chair a Coordination Meeting',
    'C1',
    'MEP manager',
    'Three disciplines disagree on service priority.',
    'Summarize constraints, assign actions and confirm deadlines.',
    ['interface', 'action owner'],
    ['Ending without decisions'],
  ],
  [
    'Present FAT Deviation',
    'C1',
    'Vendor engineer',
    'Firmware differs from the approved schedule.',
    'Explain functional result, deviation risk and approval request.',
    ['deviation', 'written acceptance'],
    ['Hiding the deviation behind test success'],
  ],
  [
    'Respond to Client Escalation',
    'C1',
    'Project manager',
    'The client questions repeated late closures.',
    'Acknowledge trend, explain controls and commit measurable actions.',
    ['escalation', 'measurable action'],
    ['Offering generic reassurance'],
  ],
  [
    'Negotiate Conditional Handover',
    'C1',
    'Handover manager',
    'Documentation is mostly complete with controlled gaps.',
    'Define residual obligations and propose conditional acceptance.',
    ['residual obligation', 'conditional acceptance'],
    ['Leaving responsibility ambiguous'],
  ],
  [
    'Explain Design Responsibility',
    'C1',
    'Technical manager',
    'The specialist and contractor dispute scope.',
    'Interpret the responsibility boundary without making legal conclusions.',
    ['performance design', 'coordination responsibility'],
    ['Overstating contractual authority'],
  ],
  [
    'Defend a Recovery Plan',
    'C1',
    'Planning manager',
    'The client doubts added labour will recover delay.',
    'Link resources to logic, productivity and critical-path movement.',
    ['recovery plan', 'critical path'],
    ['Using headcount as the only evidence'],
  ],
  [
    'Challenge a Superficial Root Cause',
    'C2',
    'Quality director',
    'The team records operator error as the final cause.',
    'Probe system controls, supervision and procedure design.',
    ['systemic cause', 'control failure'],
    ['Personalizing the investigation'],
  ],
  [
    'Govern an Integrated Test',
    'C2',
    'Test director',
    'Two discipline leads dispute stop-work authority.',
    'Clarify decision rights and preserve safety escalation.',
    ['test governance', 'stop-work authority'],
    ['Prioritizing schedule over safety'],
  ],
  [
    'Brief Executive Risk',
    'C2',
    'Project director',
    'Leadership needs a concise view of handover exposure.',
    'Separate fact, uncertainty, consequence and decision required.',
    ['residual risk', 'decision required'],
    ['Overloading the briefing with detail'],
  ],
  [
    'Airport Equipment Explanation',
    'A2',
    'Travelling engineer',
    'Airport security asks about a test instrument.',
    'Explain its purpose simply and show the supporting document.',
    ['test instrument', 'calibration certificate'],
    ['Using unexplained technical jargon'],
  ],
  [
    'Hotel Maintenance Request',
    'A2',
    'Guest engineer',
    'Your room has no power at one socket.',
    'Describe the fault, location and safe temporary action.',
    ['socket', 'power supply'],
    ['Attempting unauthorized repair'],
  ],
  [
    'Pharmacy Safety Question',
    'B1',
    'International assignee',
    'You need medicine but have an allergy.',
    'Explain the symptom, allergy and ask about safe use.',
    ['allergy', 'dosage'],
    ['Failing to mention the allergy'],
  ],
] as const;

export const PROFESSIONAL_ROLEPLAY_SCENARIOS: RoleplayScenarioDefinition[] =
  roleplaySeeds.map((seed, index) => {
    const [
      title,
      level,
      role,
      situation,
      userTask,
      vocabularyTargets,
      commonMistakes,
    ] = seed;
    return {
      id: `prc-roleplay-${String(index + 1).padStart(2, '0')}`,
      title,
      level,
      role,
      situation,
      userTask,
      expectedResponseStyle:
        'Clear, professional, evidence-based and appropriate to the CEFR level.',
      evaluationRubric: [
        'Task completion',
        'Clarity and structure',
        'Professional tone',
        'Target vocabulary',
      ],
      commonMistakes: [...commonMistakes],
      vocabularyTargets: [...vocabularyTargets],
      vocabularyIds: [],
    };
  });

const writingSeeds = [
  [
    'Daily Site Update',
    'A1',
    'Your supervisor needs a short update on today’s cable work.',
    'Write three clear sentences covering location, completed work and next action.',
    'Short site update',
    ['location', 'completed'],
    ['Writing fragments only'],
  ],
  [
    'Tool Request Email',
    'A1',
    'Your team needs a drill tomorrow morning.',
    'Write a short request with item, quantity and required time.',
    'Short email',
    ['quantity', 'required by'],
    ['Missing the deadline'],
  ],
  [
    'Safety Sign Note',
    'A1',
    'A warning sign is missing near an open panel.',
    'Write a simple safety note and required action.',
    'Safety note',
    ['warning sign', 'open panel'],
    ['Not stating the action'],
  ],
  [
    'Cable Tray Progress',
    'A2',
    'Ten metres are installed and one support is missing.',
    'Write a concise progress message with the open issue.',
    'Progress message',
    ['installed', 'support'],
    ['Mixing past and future actions'],
  ],
  [
    'Inspection Request',
    'A2',
    'Panel labels are complete and ready for review.',
    'Draft a request with location, scope and preferred time.',
    'Inspection request',
    ['ready for inspection', 'preferred time'],
    ['Omitting the exact location'],
  ],
  [
    'Delivery Follow-up',
    'A2',
    'A cable delivery did not arrive on the confirmed date.',
    'Ask the supplier for status and a revised arrival time.',
    'Procurement email',
    ['confirmed date', 'revised delivery'],
    ['Using an aggressive tone'],
  ],
  [
    'Site Instruction',
    'B1',
    'A contractor installed supports at the wrong spacing.',
    'Write an instruction describing the issue, correction and evidence required.',
    'Site instruction',
    ['approved spacing', 'rectify'],
    ['Giving no reference or evidence request'],
  ],
  [
    'Inspection Comment Response',
    'B1',
    'The consultant found two missing circuit labels.',
    'Acknowledge the comment and confirm correction and reinspection.',
    'Consultant response',
    ['observation', 'reinspection'],
    ['Disputing a valid comment'],
  ],
  [
    'Delay Explanation',
    'B1',
    'Access equipment arrived two days late.',
    'Explain cause, impact and recovery action in a progress email.',
    'Delay email',
    ['schedule impact', 'recovery action'],
    ['Stating cause without mitigation'],
  ],
  [
    'RFI Draft',
    'B1',
    'A cable tray conflicts with a chilled-water pipe.',
    'Draft an RFI with location, constraint and proposed solution.',
    'Request for information',
    ['coordination conflict', 'proposed solution'],
    ['Asking a question without a proposal'],
  ],
  [
    'Method Statement Comment',
    'B1',
    'A lifting method omits the exclusion-zone layout.',
    'Write a review comment identifying the gap and resubmission requirement.',
    'Review comment',
    ['exclusion zone', 'resubmit'],
    ['Using vague wording'],
  ],
  [
    'Commissioning Issue Report',
    'B1',
    'A fan did not start after the fire alarm command.',
    'Record expected result, actual result and immediate next check.',
    'Issue report',
    ['expected result', 'interlock'],
    ['Claiming an untested root cause'],
  ],
  [
    'Handover Email',
    'B1',
    'The client walkdown is planned and documents are ready.',
    'Confirm arrangements and list the documents available.',
    'Handover email',
    ['walkdown', 'handover file'],
    ['No clear meeting details'],
  ],
  [
    'Weekly Progress Update',
    'B1',
    'Containment progress is 70 percent with one area blocked.',
    'Write completed work, constraint and next-week plan.',
    'Weekly report',
    ['constraint', 'look-ahead'],
    ['Reporting percentages without context'],
  ],
  [
    'NCR Response',
    'B2',
    'Incorrect cable lugs were installed on three feeders.',
    'Separate correction, root cause, corrective action and prevention.',
    'NCR response',
    ['root cause', 'prevent recurrence'],
    ['Confusing correction with corrective action'],
  ],
  [
    'Procurement Escalation',
    'B2',
    'Type-test certificates remain outstanding and affect release.',
    'Escalate the document gap with impact, owner and deadline.',
    'Escalation email',
    ['outstanding document', 'delivery release'],
    ['Escalating without a requested action'],
  ],
  [
    'FAT Report',
    'B2',
    'Functional tests passed but firmware differs from approval.',
    'Summarize results, deviation and disposition required.',
    'FAT report',
    ['deviation', 'disposition'],
    ['Calling the FAT fully passed'],
  ],
  [
    'SAT Report',
    'B2',
    'Site tests passed after one wiring correction.',
    'Document sequence, correction, retest and final status.',
    'SAT report',
    ['retest', 'final status'],
    ['Hiding the initial failure'],
  ],
  [
    'Generator Load Test',
    'B2',
    'Frequency recovered within limits but fuel pressure dipped.',
    'Write an evidence-based test summary and next action.',
    'Test report',
    ['transient response', 'pressure dip'],
    ['Ignoring a secondary abnormal result'],
  ],
  [
    'Design Revision Notice',
    'B2',
    'Coordinated routing changes affect two drawings.',
    'Notify stakeholders of revision, reason and superseded documents.',
    'Design notice',
    ['superseded', 'revision'],
    ['Failing to identify affected drawings'],
  ],
  [
    'Meeting Minutes',
    'B2',
    'A coordination meeting assigned five actions.',
    'Write decisions, action owners and deadlines without transcript-style detail.',
    'Meeting minutes',
    ['action owner', 'due date'],
    ['Recording discussion without decisions'],
  ],
  [
    'Punch List Closure',
    'B2',
    'Three items were corrected and photographed.',
    'Submit closure evidence and request acceptance.',
    'Closure submission',
    ['closure evidence', 'acceptance'],
    ['Attaching evidence without mapping items'],
  ],
  [
    'Contractor Instruction',
    'B2',
    'Unapproved work started in a restricted zone.',
    'Issue a controlled stop instruction and conditions for restart.',
    'Formal instruction',
    ['suspend work', 'restart condition'],
    ['Using emotional or accusatory language'],
  ],
  [
    'Technical Clarification',
    'C1',
    'A specification clause conflicts with a drawing note.',
    'Present both requirements, risk and requested interpretation neutrally.',
    'Technical clarification',
    ['interpretation', 'precedence'],
    ['Selecting a contractual precedence without authority'],
  ],
  [
    'Commissioning Summary',
    'C1',
    'Integrated testing passed with two residual observations.',
    'Summarize scope, evidence, residual risk and closure plan.',
    'Commissioning summary',
    ['residual observation', 'closure plan'],
    ['Describing open observations as complete'],
  ],
  [
    'Conditional Handover Proposal',
    'C1',
    'Operations needs early access while documents are incomplete.',
    'Define transferred scope, exclusions, responsibilities and expiry conditions.',
    'Handover proposal',
    ['conditional handover', 'residual obligation'],
    ['Leaving liability boundaries vague'],
  ],
  [
    'Extension Notice',
    'C1',
    'Late design information affects a critical procurement item.',
    'Write a factual notice reserving rights and identifying records.',
    'Contract notice',
    ['contemporaneous notice', 'critical path'],
    ['Quantifying unproven entitlement'],
  ],
  [
    'Root Cause Review',
    'C2',
    'An investigation concludes only that an operator made an error.',
    'Rewrite the conclusion to address systemic controls and verification weaknesses.',
    'Root cause review',
    ['systemic cause', 'control weakness'],
    ['Assigning blame instead of analysing controls'],
  ],
  [
    'Executive Risk Brief',
    'C2',
    'Leadership must decide whether to proceed with phased acceptance.',
    'Write a one-page brief separating evidence, uncertainty, options and recommendation.',
    'Executive brief',
    ['decision criteria', 'residual risk'],
    ['Burying the decision beneath technical detail'],
  ],
  [
    'Governance Escalation',
    'C2',
    'A commercial instruction conflicts with a safety hold point.',
    'Document the conflict, authority boundary and required escalation without inflammatory language.',
    'Governance memorandum',
    ['authority boundary', 'safety hold point'],
    ['Making personal accusations'],
  ],
] as const;

export const PROFESSIONAL_WRITING_TASKS: WritingTaskDefinition[] =
  writingSeeds.map((seed, index) => {
    const [
      title,
      level,
      scenario,
      userTask,
      targetFormat,
      vocabularyTargets,
      commonMistakes,
    ] = seed;
    return {
      id: `prc-writing-${String(index + 1).padStart(2, '0')}`,
      title,
      level,
      scenario,
      userTask,
      targetFormat,
      rubric: [
        'Required information',
        'Logical structure',
        'Professional tone',
        'Grammar and target vocabulary',
      ],
      vocabularyTargets: [...vocabularyTargets],
      vocabularyIds: [],
      commonMistakes: [...commonMistakes],
    };
  });
