import type { ListeningLessonDefinition } from './content-library.types';

const listeningSeeds = [
  [
    'Morning Site Access',
    'A1',
    'Daily site communication',
    'A supervisor confirms the work area and access time.',
    'The electrical team can enter Room A at eight. Wear your helmet and sign the access sheet before you start.',
    ['access sheet', 'helmet'],
    'What must the team sign?',
    'The access sheet',
  ],
  [
    'Tool Delivery Check',
    'A1',
    'Procurement/delivery',
    'A storekeeper checks a small delivery.',
    'The delivery has six cable drums and two boxes of glands. One box is wet, so keep it separate.',
    ['cable drum', 'gland'],
    'Which item must be kept separate?',
    'The wet box',
  ],
  [
    'Safe Work Area',
    'A1',
    'Safety',
    'A safety officer gives a simple instruction.',
    'The floor is dry and the emergency exit is clear. Put the warning sign near the open panel.',
    ['emergency exit', 'warning sign'],
    'Where should the warning sign go?',
    'Near the open panel',
  ],
  [
    'Daily Progress Call',
    'A2',
    'Daily site communication',
    'A foreman reports completed work.',
    'We installed twelve metres of conduit on Level Two. The last section is waiting for a wall opening.',
    ['conduit', 'wall opening'],
    'Why is the last section waiting?',
    'It needs a wall opening',
  ],
  [
    'Inspection Time Change',
    'A2',
    'Inspection',
    'The consultant changes an inspection time.',
    'The panel inspection will start at three instead of two. Please finish the labels and bring the approved drawing.',
    ['panel inspection', 'approved drawing'],
    'What must the contractor bring?',
    'The approved drawing',
  ],
  [
    'Missing Delivery Note',
    'A2',
    'Procurement/delivery',
    'A receiver explains a document problem.',
    'The pumps arrived this morning, but the driver did not provide the delivery note. We cannot accept the shipment yet.',
    ['delivery note', 'shipment'],
    'Why can the shipment not be accepted?',
    'The delivery note is missing',
  ],
  [
    'Cable Tray Coordination',
    'B1',
    'Design coordination',
    'Two engineers coordinate ceiling services.',
    'The cable tray conflicts with the chilled-water pipe above Corridor C. Move the tray 150 millimetres south and update the coordination drawing.',
    ['conflict', 'coordination drawing'],
    'What change is required?',
    'Move the tray 150 millimetres south',
  ],
  [
    'Inspection Observation',
    'B1',
    'QA/QC',
    'A consultant records a quality observation.',
    'Three supports exceed the approved spacing. Correct the spacing, photograph each location and request reinspection before closing the ceiling.',
    ['approved spacing', 'reinspection'],
    'What evidence is requested?',
    'Photographs of each corrected location',
  ],
  [
    'Generator Pre-Start',
    'B1',
    'Commissioning',
    'A commissioning engineer reviews prerequisites.',
    'Before the generator starts, confirm the fuel level, battery voltage and emergency-stop reset. Record each value on the pre-start sheet.',
    ['pre-start sheet', 'emergency stop'],
    'Where should the values be recorded?',
    'On the pre-start sheet',
  ],
  [
    'Weekly Progress Risk',
    'B1',
    'Progress meeting',
    'A planner highlights a schedule risk.',
    'Containment installation is two days behind because the access platform arrived late. The recovery plan adds a second evening crew.',
    ['recovery plan', 'evening crew'],
    'How will the team recover time?',
    'By adding a second evening crew',
  ],
  [
    'Permit Suspension',
    'B1',
    'Safety',
    'A permit holder stops work safely.',
    'Stop cable pulling in Zone Four. The gas detector alarmed during the check, so the permit is suspended until HSE clears the area.',
    ['permit suspension', 'gas detector'],
    'Who must clear the area?',
    'HSE',
  ],
  [
    'Client Room Walkdown',
    'B1',
    'Client/consultant communication',
    'A client requests closeout evidence.',
    "During tomorrow's walkdown, show the corrected labels, test certificates and signed punch-list closure for each electrical room.",
    ['walkdown', 'punch-list closure'],
    'Which closure record is needed?',
    'The signed punch-list closure',
  ],
  [
    'Fire Alarm Interface Test',
    'B2',
    'Commissioning',
    'The team reviews an interface failure.',
    'The fire alarm command reached the BMS, but the smoke-control fan did not start. Check the interlock matrix and repeat the cause-and-effect test.',
    ['interlock matrix', 'cause-and-effect test'],
    'Which document should be checked?',
    'The interlock matrix',
  ],
  [
    'NCR Corrective Action',
    'B2',
    'QA/QC',
    'A quality manager reviews an NCR response.',
    'The response identifies the wrong cable lug as the immediate cause, but it does not explain how stores will prevent recurrence. Add a controlled material-verification step.',
    ['corrective action', 'prevent recurrence'],
    'What is missing from the response?',
    'A prevention control for stores',
  ],
  [
    'Consultant RFI Review',
    'B2',
    'Client/consultant communication',
    'A consultant discusses an incomplete RFI.',
    'The RFI describes the ceiling conflict but gives no preferred solution. Attach the coordinated section and state the programme impact of each option.',
    ['preferred solution', 'programme impact'],
    'What drawing should be attached?',
    'The coordinated section',
  ],
  [
    'Transformer Energization Brief',
    'B2',
    'Commissioning',
    'A lead engineer briefs the energization team.',
    'Energization can proceed after protection settings, earthing continuity and phase rotation are independently witnessed. Any open hold point stops the sequence.',
    ['hold point', 'phase rotation'],
    'What stops the energization sequence?',
    'Any open hold point',
  ],
  [
    'Material Submittal Status',
    'B2',
    'Procurement/delivery',
    'Procurement explains a submittal delay.',
    'The revised switchgear data are with the manufacturer, but the type-test certificates remain outstanding. Delivery cannot be released without consultant approval.',
    ['type-test certificate', 'delivery release'],
    'Why can delivery not be released?',
    'Consultant approval is still missing',
  ],
  [
    'Method Statement Concern',
    'B2',
    'Safety',
    'HSE challenges a lifting method.',
    'The method statement defines the crane capacity but omits the exclusion-zone layout and communication signals. Revise both sections before the toolbox talk.',
    ['exclusion zone', 'communication signal'],
    'What two sections must be revised?',
    'The exclusion-zone layout and communication signals',
  ],
  [
    'Integrated Systems Test',
    'C1',
    'Commissioning',
    'Stakeholders analyse an integrated test result.',
    'The sequence passed functionally, yet the timestamp variance between fire alarm and access control prevents reliable event reconstruction. Synchronize both systems to the approved time source.',
    ['timestamp variance', 'event reconstruction'],
    'Why must the systems be synchronized?',
    'To enable reliable event reconstruction',
  ],
  [
    'Delay Entitlement Discussion',
    'C1',
    'Progress meeting',
    'A project manager distinguishes cause and entitlement.',
    'Late design information affected procurement, but entitlement depends on contemporaneous notice and demonstrated critical-path impact. The chronology alone is insufficient.',
    ['contemporaneous notice', 'critical path'],
    'What evidence is required in addition to chronology?',
    'Notice and demonstrated critical-path impact',
  ],
  [
    'FAT Deviation Review',
    'C1',
    'QA/QC',
    'A team decides how to handle a FAT deviation.',
    'The protection relay passed functional injection, but the firmware differs from the approved schedule. Record the deviation and obtain written acceptance before shipment.',
    ['functional injection', 'written acceptance'],
    'What must happen before shipment?',
    'Written acceptance of the deviation',
  ],
  [
    'Handover Documentation Gap',
    'C1',
    'Handover',
    'The client reviews incomplete handover files.',
    'The O&M manuals are indexed, but asset tags do not reconcile with the final equipment schedule. Handover remains conditional until the register is corrected.',
    ['asset register', 'conditional handover'],
    'Why is handover conditional?',
    'Asset tags do not match the final schedule',
  ],
  [
    'Design Responsibility Boundary',
    'C1',
    'Design coordination',
    'Contractor and consultant clarify responsibility.',
    'The specification assigns performance design to the specialist, while spatial coordination remains with the main contractor. The interface schedule must reflect both obligations.',
    ['performance design', 'interface schedule'],
    'Who retains spatial coordination?',
    'The main contractor',
  ],
  [
    'Commissioning Trend Analysis',
    'C1',
    'Commissioning',
    'An engineer interprets unstable operating data.',
    'The pressure oscillation appears only during low-load operation and correlates with rapid valve hunting. Extend the trend interval before changing the control parameters.',
    ['valve hunting', 'trend interval'],
    'What should happen before parameters change?',
    'Extend the trend interval',
  ],
  [
    'Contractual Notice Wording',
    'C1',
    'Client/consultant communication',
    'A manager reviews a draft notice.',
    'The draft explains disruption but does not reserve contractual rights or identify the relevant instruction. Strengthen the notice without overstating unproven cost.',
    ['reserve rights', 'relevant instruction'],
    'What should the notice avoid overstating?',
    'Unproven cost',
  ],
  [
    'Root Cause Challenge',
    'C2',
    'QA/QC',
    'A review board challenges a superficial root cause.',
    'Operator error describes the event, not the system weakness that permitted it. Examine supervision, procedure design and verification controls before closing the investigation.',
    ['system weakness', 'verification control'],
    'Why is operator error insufficient?',
    'It does not identify the enabling system weakness',
  ],
  [
    'Commissioning Governance',
    'C2',
    'Commissioning',
    'Leaders resolve authority during a complex test.',
    'The test director controls sequence execution, while discipline leads retain authority to stop unsafe or noncompliant activity. The protocol must remove any ambiguity between those powers.',
    ['test director', 'stop-work authority'],
    'What ambiguity must the protocol remove?',
    'The boundary between sequence control and stop-work authority',
  ],
  [
    'Programme Narrative Audit',
    'C2',
    'Progress meeting',
    'A planner critiques a recovery narrative.',
    'The narrative attributes recovery to additional labour, yet the updated logic shows float consumption rather than critical-path improvement. Reconcile the claim with the programme evidence.',
    ['float consumption', 'programme logic'],
    'Why is the recovery claim questionable?',
    'The logic shows no critical-path improvement',
  ],
  [
    'Client Acceptance Strategy',
    'C2',
    'Handover',
    'A director plans phased acceptance.',
    'Phased acceptance can reduce operational risk only if residual obligations, access rights and defect responsibility remain explicit for every transferred area.',
    ['phased acceptance', 'residual obligation'],
    'What must remain explicit?',
    'Residual obligations, access rights and defect responsibility',
  ],
  [
    'Ethical Escalation',
    'C2',
    'Safety',
    'A senior engineer handles pressure to proceed.',
    'Commercial urgency does not justify bypassing a safety hold point. Document the instruction, escalate through governance and protect the team from retaliatory pressure.',
    ['safety hold point', 'governance escalation'],
    'What should the engineer document?',
    'The instruction to bypass the hold point',
  ],
] as const;

export const PROFESSIONAL_LISTENING_LESSONS: ListeningLessonDefinition[] =
  listeningSeeds.map((seed, index) => {
    const [
      title,
      cefrLevel,
      domain,
      scenario,
      transcript,
      vocabularyTargets,
      question,
      answer,
    ] = seed;
    return {
      id: `prc-listening-${String(index + 1).padStart(2, '0')}`,
      title,
      cefrLevel,
      domain,
      scenario,
      transcript,
      vocabularyTargets: [...vocabularyTargets],
      vocabularyIds: [],
      comprehensionQuestions: [
        {
          id: `prc-listening-${index + 1}-q1`,
          prompt: question,
          choices: [answer],
        },
      ],
      answerKey: [answer],
      status: 'script_ready',
    };
  });
