import type { RoleplayScenarioDefinition } from './content-library.types';

const roleplaySeeds = [
  [
    'Confirm Site Access',
    'A1',
    'Site engineer',
    'A security guard asks where your team will work.',
    'State the room, team size and start time.',
    ['access', 'work area'],
    ['Omitting the room number'],
  ],
  [
    'Ask for a Tool',
    'A1',
    'Technician',
    'You need a torque wrench from the store.',
    'Request the tool and say when you will return it.',
    ['torque wrench', 'return'],
    ['Using only one-word requests'],
  ],
  [
    'Report a Safe Condition',
    'A1',
    'Supervisor',
    'A worker asks whether the room is safe.',
    'Confirm the isolation and give one instruction.',
    ['isolation', 'safe'],
    ['Giving no action instruction'],
  ],
  [
    'Give a Progress Update',
    'A2',
    'Foreman',
    'The coordinator asks what your team completed.',
    'Report quantity, location and next action.',
    ['installed', 'remaining'],
    ['Mixing completed and planned work'],
  ],
  [
    'Request Reinspection',
    'A2',
    'QA/QC engineer',
    'A minor defect has been corrected.',
    'Ask the consultant for a new inspection time.',
    ['rectified', 'reinspection'],
    ['Not identifying the location'],
  ],
  [
    'Clarify a Delivery',
    'A2',
    'Site engineer',
    'A driver has the wrong unloading gate.',
    'Give the correct gate and contact person.',
    ['delivery gate', 'contact person'],
    ['Giving unclear directions'],
  ],
  [
    'Explain a Ceiling Conflict',
    'B1',
    'MEP coordinator',
    'Cable tray conflicts with a pipe.',
    'Describe the conflict and propose one coordinated move.',
    ['clearance', 'offset'],
    ['Blaming another discipline'],
  ],
  [
    'Lead a Toolbox Talk',
    'B1',
    'Safety engineer',
    'The team will work near energized equipment.',
    'Explain the hazard, control and stop-work rule.',
    ['hazard', 'control measure'],
    ['Using vague safety language'],
  ],
  [
    'Respond to an Observation',
    'B1',
    'QA/QC engineer',
    'The consultant identifies missing labels.',
    'Acknowledge, state correction and promise evidence.',
    ['observation', 'evidence'],
    ['Arguing before confirming facts'],
  ],
  [
    'Update a Progress Meeting',
    'B1',
    'Project engineer',
    'An activity is two days late.',
    'State cause, impact and recovery action.',
    ['delay', 'recovery action'],
    ['Giving a cause without impact'],
  ],
  [
    'Prepare Generator Testing',
    'B1',
    'Commissioning engineer',
    'The client asks if testing can start.',
    'Confirm prerequisites and identify one open point.',
    ['prerequisite', 'open point'],
    ['Saying ready while an item is open'],
  ],
  [
    'Handle a Missing Document',
    'B1',
    'Procurement engineer',
    'Materials arrived without certificates.',
    'Explain the hold and request the missing records.',
    ['certificate', 'on hold'],
    ['Accepting materials conditionally without authority'],
  ],
  [
    'Defend an RFI Solution',
    'B2',
    'Design coordinator',
    'The consultant asks why your routing option is preferred.',
    'Compare options using clearance, access and programme impact.',
    ['preferred solution', 'programme impact'],
    ['Describing only one option'],
  ],
  [
    'Close an NCR Meeting',
    'B2',
    'Quality manager',
    'Corrective action is complete but prevention is unclear.',
    'Separate correction, root cause and recurrence prevention.',
    ['root cause', 'prevent recurrence'],
    ['Calling correction a root cause'],
  ],
  [
    'Explain a Commissioning Failure',
    'B2',
    'Commissioning lead',
    'An interface test failed at the BMS output.',
    'Explain observed result, boundary and next diagnostic step.',
    ['interface', 'diagnostic'],
    ['Claiming a cause before testing'],
  ],
  [
    'Negotiate Inspection Timing',
    'B2',
    'Site manager',
    'The consultant proposes a time before work is ready.',
    'Request a realistic time and explain readiness evidence.',
    ['readiness', 'inspection window'],
    ['Sounding dismissive'],
  ],
  [
    'Present a Delay Notice',
    'B2',
    'Project engineer',
    'Late information affected procurement.',
    'Explain chronology, impact and requested response professionally.',
    ['notice', 'critical activity'],
    ['Making unsupported cost claims'],
  ],
  [
    'Challenge an Unsafe Instruction',
    'B2',
    'Site supervisor',
    'A manager asks the team to bypass a hold point.',
    'Refuse professionally, cite the control and escalate.',
    ['hold point', 'escalate'],
    ['Using confrontational language'],
  ],
  [
    'Chair a Coordination Meeting',
    'C1',
    'MEP manager',
    'Three disciplines disagree on service priority.',
    'Summarize constraints, assign actions and confirm deadlines.',
    ['interface', 'action owner'],
    ['Ending without decisions'],
  ],
  [
    'Present FAT Deviation',
    'C1',
    'Vendor engineer',
    'Firmware differs from the approved schedule.',
    'Explain functional result, deviation risk and approval request.',
    ['deviation', 'written acceptance'],
    ['Hiding the deviation behind test success'],
  ],
  [
    'Respond to Client Escalation',
    'C1',
    'Project manager',
    'The client questions repeated late closures.',
    'Acknowledge trend, explain controls and commit measurable actions.',
    ['escalation', 'measurable action'],
    ['Offering generic reassurance'],
  ],
  [
    'Negotiate Conditional Handover',
    'C1',
    'Handover manager',
    'Documentation is mostly complete with controlled gaps.',
    'Define residual obligations and propose conditional acceptance.',
    ['residual obligation', 'conditional acceptance'],
    ['Leaving responsibility ambiguous'],
  ],
  [
    'Explain Design Responsibility',
    'C1',
    'Technical manager',
    'The specialist and contractor dispute scope.',
    'Interpret the responsibility boundary without making legal conclusions.',
    ['performance design', 'coordination responsibility'],
    ['Overstating contractual authority'],
  ],
  [
    'Defend a Recovery Plan',
    'C1',
    'Planning manager',
    'The client doubts added labour will recover delay.',
    'Link resources to logic, productivity and critical-path movement.',
    ['recovery plan', 'critical path'],
    ['Using headcount as the only evidence'],
  ],
  [
    'Challenge a Superficial Root Cause',
    'C2',
    'Quality director',
    'The team records operator error as the final cause.',
    'Probe system controls, supervision and procedure design.',
    ['systemic cause', 'control failure'],
    ['Personalizing the investigation'],
  ],
  [
    'Govern an Integrated Test',
    'C2',
    'Test director',
    'Two discipline leads dispute stop-work authority.',
    'Clarify decision rights and preserve safety escalation.',
    ['test governance', 'stop-work authority'],
    ['Prioritizing schedule over safety'],
  ],
  [
    'Brief Executive Risk',
    'C2',
    'Project director',
    'Leadership needs a concise view of handover exposure.',
    'Separate fact, uncertainty, consequence and decision required.',
    ['residual risk', 'decision required'],
    ['Overloading the briefing with detail'],
  ],
  [
    'Airport Equipment Explanation',
    'A2',
    'Travelling engineer',
    'Airport security asks about a test instrument.',
    'Explain its purpose simply and show the supporting document.',
    ['test instrument', 'calibration certificate'],
    ['Using unexplained technical jargon'],
  ],
  [
    'Hotel Maintenance Request',
    'A2',
    'Guest engineer',
    'Your room has no power at one socket.',
    'Describe the fault, location and safe temporary action.',
    ['socket', 'power supply'],
    ['Attempting unauthorized repair'],
  ],
  [
    'Pharmacy Safety Question',
    'B1',
    'International assignee',
    'You need medicine but have an allergy.',
    'Explain the symptom, allergy and ask about safe use.',
    ['allergy', 'dosage'],
    ['Failing to mention the allergy'],
  ],
] as const;

export const PROFESSIONAL_ROLEPLAY_SCENARIOS: RoleplayScenarioDefinition[] =
  roleplaySeeds.map((seed, index) => {
    const [
      title,
      level,
      role,
      situation,
      userTask,
      vocabularyTargets,
      commonMistakes,
    ] = seed;
    return {
      id: `prc-roleplay-${String(index + 1).padStart(2, '0')}`,
      title,
      level,
      role,
      situation,
      userTask,
      expectedResponseStyle:
        'Clear, professional, evidence-based and appropriate to the CEFR level.',
      evaluationRubric: [
        'Task completion',
        'Clarity and structure',
        'Professional tone',
        'Target vocabulary',
      ],
      commonMistakes: [...commonMistakes],
      vocabularyTargets: [...vocabularyTargets],
      vocabularyIds: [],
    };
  });
