import type { WritingTaskDefinition } from './content-library.types';

const writingSeeds = [
  [
    'Daily Site Update',
    'A1',
    "Your supervisor needs a short update on today's cable work.",
    'Write three clear sentences covering location, completed work and next action.',
    'Short site update',
    ['location', 'completed'],
    ['Writing fragments only'],
  ],
  [
    'Tool Request Email',
    'A1',
    'Your team needs a drill tomorrow morning.',
    'Write a short request with item, quantity and required time.',
    'Short email',
    ['quantity', 'required by'],
    ['Missing the deadline'],
  ],
  [
    'Safety Sign Note',
    'A1',
    'A warning sign is missing near an open panel.',
    'Write a simple safety note and required action.',
    'Safety note',
    ['warning sign', 'open panel'],
    ['Not stating the action'],
  ],
  [
    'Cable Tray Progress',
    'A2',
    'Ten metres are installed and one support is missing.',
    'Write a concise progress message with the open issue.',
    'Progress message',
    ['installed', 'support'],
    ['Mixing past and future actions'],
  ],
  [
    'Inspection Request',
    'A2',
    'Panel labels are complete and ready for review.',
    'Draft a request with location, scope and preferred time.',
    'Inspection request',
    ['ready for inspection', 'preferred time'],
    ['Omitting the exact location'],
  ],
  [
    'Delivery Follow-up',
    'A2',
    'A cable delivery did not arrive on the confirmed date.',
    'Ask the supplier for status and a revised arrival time.',
    'Procurement email',
    ['confirmed date', 'revised delivery'],
    ['Using an aggressive tone'],
  ],
  [
    'Site Instruction',
    'B1',
    'A contractor installed supports at the wrong spacing.',
    'Write an instruction describing the issue, correction and evidence required.',
    'Site instruction',
    ['approved spacing', 'rectify'],
    ['Giving no reference or evidence request'],
  ],
  [
    'Inspection Comment Response',
    'B1',
    'The consultant found two missing circuit labels.',
    'Acknowledge the comment and confirm correction and reinspection.',
    'Consultant response',
    ['observation', 'reinspection'],
    ['Disputing a valid comment'],
  ],
  [
    'Delay Explanation',
    'B1',
    'Access equipment arrived two days late.',
    'Explain cause, impact and recovery action in a progress email.',
    'Delay email',
    ['schedule impact', 'recovery action'],
    ['Stating cause without mitigation'],
  ],
  [
    'RFI Draft',
    'B1',
    'A cable tray conflicts with a chilled-water pipe.',
    'Draft an RFI with location, constraint and proposed solution.',
    'Request for information',
    ['coordination conflict', 'proposed solution'],
    ['Asking a question without a proposal'],
  ],
  [
    'Method Statement Comment',
    'B1',
    'A lifting method omits the exclusion-zone layout.',
    'Write a review comment identifying the gap and resubmission requirement.',
    'Review comment',
    ['exclusion zone', 'resubmit'],
    ['Using vague wording'],
  ],
  [
    'Commissioning Issue Report',
    'B1',
    'A fan did not start after the fire alarm command.',
    'Record expected result, actual result and immediate next check.',
    'Issue report',
    ['expected result', 'interlock'],
    ['Claiming an untested root cause'],
  ],
  [
    'Handover Email',
    'B1',
    'The client walkdown is planned and documents are ready.',
    'Confirm arrangements and list the documents available.',
    'Handover email',
    ['walkdown', 'handover file'],
    ['No clear meeting details'],
  ],
  [
    'Weekly Progress Update',
    'B1',
    'Containment progress is 70 percent with one area blocked.',
    'Write completed work, constraint and next-week plan.',
    'Weekly report',
    ['constraint', 'look-ahead'],
    ['Reporting percentages without context'],
  ],
  [
    'NCR Response',
    'B2',
    'Incorrect cable lugs were installed on three feeders.',
    'Separate correction, root cause, corrective action and prevention.',
    'NCR response',
    ['root cause', 'prevent recurrence'],
    ['Confusing correction with corrective action'],
  ],
  [
    'Procurement Escalation',
    'B2',
    'Type-test certificates remain outstanding and affect release.',
    'Escalate the document gap with impact, owner and deadline.',
    'Escalation email',
    ['outstanding document', 'delivery release'],
    ['Escalating without a requested action'],
  ],
  [
    'FAT Report',
    'B2',
    'Functional tests passed but firmware differs from approval.',
    'Summarize results, deviation and disposition required.',
    'FAT report',
    ['deviation', 'disposition'],
    ['Calling the FAT fully passed'],
  ],
  [
    'SAT Report',
    'B2',
    'Site tests passed after one wiring correction.',
    'Document sequence, correction, retest and final status.',
    'SAT report',
    ['retest', 'final status'],
    ['Hiding the initial failure'],
  ],
  [
    'Generator Load Test',
    'B2',
    'Frequency recovered within limits but fuel pressure dipped.',
    'Write an evidence-based test summary and next action.',
    'Test report',
    ['transient response', 'pressure dip'],
    ['Ignoring a secondary abnormal result'],
  ],
  [
    'Design Revision Notice',
    'B2',
    'Coordinated routing changes affect two drawings.',
    'Notify stakeholders of revision, reason and superseded documents.',
    'Design notice',
    ['superseded', 'revision'],
    ['Failing to identify affected drawings'],
  ],
  [
    'Meeting Minutes',
    'B2',
    'A coordination meeting assigned five actions.',
    'Write decisions, action owners and deadlines without transcript-style detail.',
    'Meeting minutes',
    ['action owner', 'due date'],
    ['Recording discussion without decisions'],
  ],
  [
    'Punch List Closure',
    'B2',
    'Three items were corrected and photographed.',
    'Submit closure evidence and request acceptance.',
    'Closure submission',
    ['closure evidence', 'acceptance'],
    ['Attaching evidence without mapping items'],
  ],
  [
    'Contractor Instruction',
    'B2',
    'Unapproved work started in a restricted zone.',
    'Issue a controlled stop instruction and conditions for restart.',
    'Formal instruction',
    ['suspend work', 'restart condition'],
    ['Using emotional or accusatory language'],
  ],
  [
    'Technical Clarification',
    'C1',
    'A specification clause conflicts with a drawing note.',
    'Present both requirements, risk and requested interpretation neutrally.',
    'Technical clarification',
    ['interpretation', 'precedence'],
    ['Selecting a contractual precedence without authority'],
  ],
  [
    'Commissioning Summary',
    'C1',
    'Integrated testing passed with two residual observations.',
    'Summarize scope, evidence, residual risk and closure plan.',
    'Commissioning summary',
    ['residual observation', 'closure plan'],
    ['Describing open observations as complete'],
  ],
  [
    'Conditional Handover Proposal',
    'C1',
    'Operations needs early access while documents are incomplete.',
    'Define transferred scope, exclusions, responsibilities and expiry conditions.',
    'Handover proposal',
    ['conditional handover', 'residual obligation'],
    ['Leaving liability boundaries vague'],
  ],
  [
    'Extension Notice',
    'C1',
    'Late design information affects a critical procurement item.',
    'Write a factual notice reserving rights and identifying records.',
    'Contract notice',
    ['contemporaneous notice', 'critical path'],
    ['Quantifying unproven entitlement'],
  ],
  [
    'Root Cause Review',
    'C2',
    'An investigation concludes only that an operator made an error.',
    'Rewrite the conclusion to address systemic controls and verification weaknesses.',
    'Root cause review',
    ['systemic cause', 'control weakness'],
    ['Assigning blame instead of analysing controls'],
  ],
  [
    'Executive Risk Brief',
    'C2',
    'Leadership must decide whether to proceed with phased acceptance.',
    'Write a one-page brief separating evidence, uncertainty, options and recommendation.',
    'Executive brief',
    ['decision criteria', 'residual risk'],
    ['Burying the decision beneath technical detail'],
  ],
  [
    'Governance Escalation',
    'C2',
    'A commercial instruction conflicts with a safety hold point.',
    'Document the conflict, authority boundary and required escalation without inflammatory language.',
    'Governance memorandum',
    ['authority boundary', 'safety hold point'],
    ['Making personal accusations'],
  ],
] as const;

export const PROFESSIONAL_WRITING_TASKS: WritingTaskDefinition[] =
  writingSeeds.map((seed, index) => {
    const [
      title,
      level,
      scenario,
      userTask,
      targetFormat,
      vocabularyTargets,
      commonMistakes,
    ] = seed;
    return {
      id: `prc-writing-${String(index + 1).padStart(2, '0')}`,
      title,
      level,
      scenario,
      userTask,
      targetFormat,
      rubric: [
        'Required information',
        'Logical structure',
        'Professional tone',
        'Grammar and target vocabulary',
      ],
      vocabularyTargets: [...vocabularyTargets],
      vocabularyIds: [],
      commonMistakes: [...commonMistakes],
    };
  });
