import { Mission } from './learning.types';

export const DEFAULT_MISSIONS: Mission[] = [
  {
    id: 'reading_idempotence',
    title: 'Read a Consultant Comment Sheet',
    description:
      'Practice identifying requirements, clarifications, and action items in a technical consultant response.',
    module: 'Reading',
    difficulty: 'Beginner',
    estimatedMinutes: 10,
    xpReward: 50,
    coinReward: 15,
    eloReward: 12,
    status: 'active',
    completedAt: null,
  },
  {
    id: 'writing_cache_draft',
    title: 'Polish Site Progress Report',
    description:
      'Analyze and edit a daily site update so it reads like a professional engineering report.',
    module: 'Writing',
    difficulty: 'Intermediate',
    estimatedMinutes: 15,
    xpReward: 75,
    coinReward: 20,
    eloReward: 18,
    status: 'available',
    completedAt: null,
  },
  {
    id: 'list_site_meeting',
    title: 'Substation Site Layout Alignment',
    description:
      'Listen to the site engineer and civil supervisor aligning on substation trench coordinates and cable entry conduits.',
    module: 'Listening',
    difficulty: 'Intermediate',
    estimatedMinutes: 12,
    xpReward: 60,
    coinReward: 20,
    eloReward: 12,
    status: 'active',
    completedAt: null,
  },
  {
    id: 'list_consultant_review',
    title: 'Submittal Comment Reconciliation',
    description:
      'Listen to a senior design engineer reviewing structural comment deviations with the lead electrical consultant.',
    module: 'Listening',
    difficulty: 'Advanced',
    estimatedMinutes: 15,
    xpReward: 80,
    coinReward: 25,
    eloReward: 16,
    status: 'available',
    completedAt: null,
  },
  {
    id: 'list_generator_testing',
    title: 'Diesel Generator Transient Load Testing',
    description:
      'Listen to the commissioning lead discussing transient voltage recovery during an emergency generator step-load test.',
    module: 'Listening',
    difficulty: 'Advanced',
    estimatedMinutes: 18,
    xpReward: 90,
    coinReward: 30,
    eloReward: 18,
    status: 'available',
    completedAt: null,
  },
  {
    id: 'list_fat_meeting',
    title: 'Factory Acceptance Testing Alignment',
    description:
      'Listen to the procurement lead and QA auditor conducting a pre-FAT briefing for control and protection panels.',
    module: 'Listening',
    difficulty: 'Intermediate',
    estimatedMinutes: 10,
    xpReward: 65,
    coinReward: 20,
    eloReward: 13,
    status: 'available',
    completedAt: null,
  },
  {
    id: 'list_lv_panel_discussion',
    title: 'Low-Voltage Board Busbar Thermal Anomalies',
    description:
      'Listen to a maintenance supervisor discussing thermal hotspots detected during a periodic thermographic scan of an LV panel.',
    module: 'Listening',
    difficulty: 'Advanced',
    estimatedMinutes: 14,
    xpReward: 85,
    coinReward: 25,
    eloReward: 17,
    status: 'available',
    completedAt: null,
  },
  {
    id: 'list_cable_routing',
    title: 'Galvanized Cable Ladder Containment Routing',
    description:
      'Listen to the site supervisor discussing segregation rules and load capacity constraints for heavy-duty galvanized cable ladders.',
    module: 'Listening',
    difficulty: 'Intermediate',
    estimatedMinutes: 11,
    xpReward: 70,
    coinReward: 22,
    eloReward: 14,
    status: 'available',
    completedAt: null,
  },
  {
    id: 'list_electrical_inspection',
    title: 'Post-Installation Grounding & Insulation Testing',
    description:
      'Listen to an inspector conducting safety checks on secondary transformer terminals using high-voltage insulation megger tests.',
    module: 'Listening',
    difficulty: 'Advanced',
    estimatedMinutes: 16,
    xpReward: 95,
    coinReward: 30,
    eloReward: 19,
    status: 'available',
    completedAt: null,
  },
  {
    id: 'list_safety_toolbox',
    title: 'Lockout-Tagout (LOTO) & Arc Flash Briefing',
    description:
      'Listen to the site safety officer conducting a safety toolbox talk on arc-flash boundaries and lockout procedures.',
    module: 'Listening',
    difficulty: 'Beginner',
    estimatedMinutes: 8,
    xpReward: 50,
    coinReward: 15,
    eloReward: 10,
    status: 'available',
    completedAt: null,
  },
  {
    id: 'list_project_progress',
    title: 'Site Delivery Critical Path Progress Meeting',
    description:
      'Listen to the project manager and lead electrical planner debating critical path delays for key switchgear deliveries.',
    module: 'Listening',
    difficulty: 'Intermediate',
    estimatedMinutes: 10,
    xpReward: 60,
    coinReward: 20,
    eloReward: 12,
    status: 'available',
    completedAt: null,
  },
  {
    id: 'list_mechanical_coordination',
    title: 'HVAC Duct & Electrical Tray Space Coordination',
    description:
      'Listen to a mechanical coordinator and lead electrical engineer resolving site space conflicts between large HVAC ducts and main cable trays.',
    module: 'Listening',
    difficulty: 'Advanced',
    estimatedMinutes: 14,
    xpReward: 80,
    coinReward: 25,
    eloReward: 16,
    status: 'available',
    completedAt: null,
  },
  {
    id: 'speaking_site_meeting',
    title: 'Site Meeting Alignment Brief',
    description:
      'Summarize site constraints, action owners, and installation blockers for a field coordination meeting.',
    module: 'Speaking',
    difficulty: 'Intermediate',
    estimatedMinutes: 10,
    xpReward: 70,
    coinReward: 20,
    eloReward: 14,
    status: 'available',
    completedAt: null,
  },
  {
    id: 'speaking_toolbox_talk',
    title: 'Daily Toolbox Talk',
    description:
      'Deliver a concise daily safety and work-front briefing for site technicians.',
    module: 'Speaking',
    difficulty: 'Beginner',
    estimatedMinutes: 8,
    xpReward: 55,
    coinReward: 15,
    eloReward: 10,
    status: 'available',
    completedAt: null,
  },
  {
    id: 'speaking_consultant_discussion',
    title: 'Consultant Comment Discussion',
    description:
      'Respond professionally to a consultant comment about shop drawing deviation and compliance evidence.',
    module: 'Speaking',
    difficulty: 'Advanced',
    estimatedMinutes: 14,
    xpReward: 85,
    coinReward: 25,
    eloReward: 18,
    status: 'available',
    completedAt: null,
  },
  {
    id: 'speaking_client_presentation',
    title: 'Client Presentation Summary',
    description:
      'Present a high-level technical solution to a non-specialist client without losing engineering precision.',
    module: 'Speaking',
    difficulty: 'Advanced',
    estimatedMinutes: 16,
    xpReward: 90,
    coinReward: 28,
    eloReward: 20,
    status: 'available',
    completedAt: null,
  },
  {
    id: 'speaking_progress_meeting',
    title: 'Progress Meeting Update',
    description:
      'Report schedule movement, blockers, and mitigation actions in a weekly progress meeting.',
    module: 'Speaking',
    difficulty: 'Intermediate',
    estimatedMinutes: 11,
    xpReward: 70,
    coinReward: 20,
    eloReward: 14,
    status: 'available',
    completedAt: null,
  },
  {
    id: 'speaking_commissioning_meeting',
    title: 'Commissioning Meeting Handover',
    description:
      'Explain test readiness, acceptance criteria, and open commissioning prerequisites.',
    module: 'Speaking',
    difficulty: 'Advanced',
    estimatedMinutes: 15,
    xpReward: 88,
    coinReward: 28,
    eloReward: 19,
    status: 'available',
    completedAt: null,
  },
  {
    id: 'speaking_fat_meeting',
    title: 'Factory Acceptance Test Brief',
    description:
      'Brief the factory team on acceptance criteria, punch items, and witness test expectations.',
    module: 'Speaking',
    difficulty: 'Advanced',
    estimatedMinutes: 14,
    xpReward: 82,
    coinReward: 25,
    eloReward: 18,
    status: 'available',
    completedAt: null,
  },
  {
    id: 'speaking_technical_explanation',
    title: 'Technical Explanation Drill',
    description:
      'Explain a complex engineering tradeoff using clear technical vocabulary and structured cause-effect language.',
    module: 'Speaking',
    difficulty: 'Advanced',
    estimatedMinutes: 16,
    xpReward: 95,
    coinReward: 30,
    eloReward: 22,
    status: 'available',
    completedAt: null,
  },
  {
    id: 'speaking_safety_briefing',
    title: 'Safety Briefing Escalation',
    description:
      'Give a clear safety escalation briefing for live electrical diagnostic work.',
    module: 'Speaking',
    difficulty: 'Intermediate',
    estimatedMinutes: 10,
    xpReward: 68,
    coinReward: 20,
    eloReward: 13,
    status: 'available',
    completedAt: null,
  },
  {
    id: 'speaking_design_coordination',
    title: 'Design Coordination Resolution',
    description:
      'Resolve a design interface clash between mechanical and electrical systems.',
    module: 'Speaking',
    difficulty: 'Advanced',
    estimatedMinutes: 15,
    xpReward: 86,
    coinReward: 26,
    eloReward: 18,
    status: 'available',
    completedAt: null,
  },
  {
    id: 'vocabulary_network',
    title: 'Master Site Coordination Vocabulary',
    description:
      'Learn and match project communication terms used in meetings, inspections, and submittals.',
    module: 'Vocabulary',
    difficulty: 'Beginner',
    estimatedMinutes: 5,
    xpReward: 40,
    coinReward: 10,
    eloReward: 10,
    status: 'available',
    completedAt: null,
  },
  {
    id: 'grammar_kernel',
    title: 'Audit Technical Grammar Issues',
    description:
      'Review formal grammar and clarity issues in engineering project communication.',
    module: 'Grammar',
    difficulty: 'Advanced',
    estimatedMinutes: 25,
    xpReward: 120,
    coinReward: 40,
    eloReward: 30,
    status: 'available' as const,
    completedAt: null,
  },
  {
    id: 'elec_site_inspection',
    title: 'Electrical Site Inspection Report',
    description:
      'Analyze physical substation installation checks and safety grounding compliance reports.',
    module: 'Reading',
    difficulty: 'Advanced',
    estimatedMinutes: 12,
    xpReward: 60,
    coinReward: 20,
    eloReward: 15,
    status: 'available',
    completedAt: null,
  },
  {
    id: 'lv_panel_issue',
    title: 'LV Panel Issue Report',
    description:
      'Diagnose overheating busbars, harmonics, and thermographic survey deviations in low-voltage distribution boards.',
    module: 'Reading',
    difficulty: 'Advanced',
    estimatedMinutes: 15,
    xpReward: 75,
    coinReward: 25,
    eloReward: 18,
    status: 'available',
    completedAt: null,
  },
  {
    id: 'generator_load_test',
    title: 'Generator Load Test Report',
    description:
      'Evaluate transient voltage recovery, frequency stability, and fuel consumption curves of emergency diesel generators.',
    module: 'Reading',
    difficulty: 'Intermediate',
    estimatedMinutes: 10,
    xpReward: 50,
    coinReward: 15,
    eloReward: 12,
    status: 'available',
    completedAt: null,
  },
  {
    id: 'fire_alarm_comm',
    title: 'Fire Alarm Commissioning Note',
    description:
      'Verify SLC loop addressing, strobe synchronization, and interface relays with HVAC dampers and elevators.',
    module: 'Reading',
    difficulty: 'Intermediate',
    estimatedMinutes: 10,
    xpReward: 55,
    coinReward: 18,
    eloReward: 13,
    status: 'available',
    completedAt: null,
  },
  {
    id: 'cable_tray_install',
    title: 'Cable Tray Installation Update',
    description:
      'Verify routing, containment separation distances, load structural margins, and bonding of galvanized cable tray ladders.',
    module: 'Reading',
    difficulty: 'Beginner',
    estimatedMinutes: 8,
    xpReward: 40,
    coinReward: 10,
    eloReward: 10,
    status: 'available',
    completedAt: null,
  },
  {
    id: 'consultant_comment_response',
    title: 'Consultant Comment Response',
    description:
      'Structure professional technical justifications and contract specification rebuttals.',
    module: 'Reading',
    difficulty: 'Intermediate',
    estimatedMinutes: 15,
    xpReward: 65,
    coinReward: 20,
    eloReward: 14,
    status: 'available',
    completedAt: null,
  },
  {
    id: 'shop_drawing_rev',
    title: 'Shop Drawing Revision Note',
    description:
      'Interpret drawing modifications, bill of materials adjustments, and architectural revisions.',
    module: 'Reading',
    difficulty: 'Intermediate',
    estimatedMinutes: 10,
    xpReward: 50,
    coinReward: 15,
    eloReward: 12,
    status: 'available',
    completedAt: null,
  },
  {
    id: 'mech_elec_coordination',
    title: 'Mechanical-Electrical Coordination Issue',
    description:
      'Solve complex geometric space clashes, thermal load requirements, and power feed capacity overrides.',
    module: 'Reading',
    difficulty: 'Advanced',
    estimatedMinutes: 18,
    xpReward: 80,
    coinReward: 30,
    eloReward: 20,
    status: 'available',
    completedAt: null,
  },
];
