import { Achievement } from './learning.types';

export const DEFAULT_ACHIEVEMENTS: Achievement[] = [
  {
    id: 'ach_1',
    title: 'First Mission',
    description: 'Complete any training mission on EngVox',
    criteriaType: 'first_mission',
    criteriaValue: 1,
    unlocked: false,
    unlockedAt: null,
  },
  {
    id: 'ach_2',
    title: 'Reading Beginner',
    description: 'Complete a Reading comprehension module',
    criteriaType: 'module_count',
    criteriaValue: 1,
    moduleFilter: 'Reading',
    unlocked: false,
    unlockedAt: null,
  },
  {
    id: 'ach_3',
    title: 'Writing Beginner',
    description: 'Complete a Writing workspace module',
    criteriaType: 'module_count',
    criteriaValue: 1,
    moduleFilter: 'Writing',
    unlocked: false,
    unlockedAt: null,
  },
  {
    id: 'ach_4',
    title: '7 Day Streak',
    description: 'Maintain a 7-day learning streak in EngVox',
    criteriaType: 'streak',
    criteriaValue: 7,
    unlocked: false,
    unlockedAt: null,
  },
  {
    id: 'ach_5',
    title: 'XP 1000',
    description: 'Earn a total of 1000 Experience Points',
    criteriaType: 'xp_earned',
    criteriaValue: 1000,
    unlocked: false,
    unlockedAt: null,
  },
  {
    id: 'ach_6',
    title: 'XP 5000',
    description: 'Earn a total of 5000 Experience Points',
    criteriaType: 'xp_earned',
    criteriaValue: 5000,
    unlocked: false,
    unlockedAt: null,
  },
  {
    id: 'ach_7',
    title: 'Perfect Score',
    description: 'Achieve a score of 100 on any learning module',
    criteriaType: 'perfect_score',
    criteriaValue: 100,
    unlocked: false,
    unlockedAt: null,
  },
  {
    id: 'ach_8',
    title: 'Fast Learner',
    description: 'Log at least 3 completed study sessions',
    criteriaType: 'fast_learner',
    criteriaValue: 3,
    unlocked: false,
    unlockedAt: null,
  },
  {
    id: 'ach_reading_tech',
    title: 'Technical Reader',
    description: 'Complete 3 Reading comprehension modules with high precision',
    criteriaType: 'module_count',
    criteriaValue: 3,
    moduleFilter: 'Reading',
    unlocked: false,
    unlockedAt: null,
  },
  {
    id: 'ach_reading_perfect',
    title: 'Perfect Reading Score',
    description: 'Achieve a score of 100 on a Reading comprehension module',
    criteriaType: 'perfect_score',
    criteriaValue: 100,
    unlocked: false,
    unlockedAt: null,
  },
  {
    id: 'ach_listening_first',
    title: 'First Listening',
    description: 'Complete your first Listening briefing session',
    criteriaType: 'module_count',
    criteriaValue: 1,
    moduleFilter: 'Listening',
    unlocked: false,
    unlockedAt: null,
  },
  {
    id: 'ach_listening_meeting',
    title: 'Meeting Listener',
    description: 'Log at least 3 completed engineering Listening meetings',
    criteriaType: 'module_count',
    criteriaValue: 3,
    moduleFilter: 'Listening',
    unlocked: false,
    unlockedAt: null,
  },
  {
    id: 'ach_listening_perfect',
    title: 'Perfect Listener',
    description: 'Achieve a perfect score of 100% in a Listening module',
    criteriaType: 'perfect_score',
    criteriaValue: 100,
    moduleFilter: 'Listening',
    unlocked: false,
    unlockedAt: null,
  },
  {
    id: 'ach_listening_tech',
    title: 'Technical Listener',
    description: 'Complete 5 Listening briefing sessions with high accuracy',
    criteriaType: 'module_count',
    criteriaValue: 5,
    moduleFilter: 'Listening',
    unlocked: false,
    unlockedAt: null,
  },
  {
    id: 'ach_listening_master',
    title: 'Listening Master',
    description: 'Complete all 10 Listening briefing sessions',
    criteriaType: 'module_count',
    criteriaValue: 10,
    moduleFilter: 'Listening',
    unlocked: false,
    unlockedAt: null,
  },
  {
    id: 'ach_speaking_first',
    title: 'First Speaking Brief',
    description: 'Complete your first Speaking Engine Pro mission',
    criteriaType: 'module_count',
    criteriaValue: 1,
    moduleFilter: 'Speaking',
    unlocked: false,
    unlockedAt: null,
  },
  {
    id: 'ach_speaking_meetings',
    title: 'Meeting Speaker',
    description: 'Complete 3 engineering speaking meeting missions',
    criteriaType: 'module_count',
    criteriaValue: 3,
    moduleFilter: 'Speaking',
    unlocked: false,
    unlockedAt: null,
  },
  {
    id: 'ach_speaking_perfect',
    title: 'Perfect Speaking Score',
    description: 'Achieve a perfect score in a Speaking mission',
    criteriaType: 'perfect_score',
    criteriaValue: 100,
    moduleFilter: 'Speaking',
    unlocked: false,
    unlockedAt: null,
  },
  {
    id: 'ach_speaking_technical',
    title: 'Technical Speaker',
    description:
      'Complete 5 Speaking missions with technical vocabulary calibration',
    criteriaType: 'module_count',
    criteriaValue: 5,
    moduleFilter: 'Speaking',
    unlocked: false,
    unlockedAt: null,
  },
  {
    id: 'ach_speaking_master',
    title: 'Speaking Master',
    description: 'Complete all 10 Speaking Engine Pro missions',
    criteriaType: 'module_count',
    criteriaValue: 10,
    moduleFilter: 'Speaking',
    unlocked: false,
    unlockedAt: null,
  },
  {
    id: 'ach_vocab_first_word',
    title: 'First Word',
    description: 'Learn your first engineering vocabulary word',
    criteriaType: 'module_count',
    criteriaValue: 1,
    moduleFilter: 'Vocabulary',
    unlocked: false,
    unlockedAt: null,
  },
  {
    id: 'ach_vocab_100_words',
    title: '100 Words',
    description: 'Learn 100 engineering vocabulary words',
    criteriaType: 'module_count',
    criteriaValue: 100,
    moduleFilter: 'Vocabulary',
    unlocked: false,
    unlockedAt: null,
  },
  {
    id: 'ach_vocab_500_words',
    title: '500 Words',
    description: 'Learn 500 engineering vocabulary words',
    criteriaType: 'module_count',
    criteriaValue: 500,
    moduleFilter: 'Vocabulary',
    unlocked: false,
    unlockedAt: null,
  },
  {
    id: 'ach_vocab_master',
    title: 'Vocabulary Master',
    description: 'Reach the advanced Vocabulary Engine Pro mastery threshold',
    criteriaType: 'module_count',
    criteriaValue: 750,
    moduleFilter: 'Vocabulary',
    unlocked: false,
    unlockedAt: null,
  },
  {
    id: 'ach_vocab_perfect_review',
    title: 'Perfect Review',
    description: 'Score 100 in a Vocabulary review session',
    criteriaType: 'perfect_score',
    criteriaValue: 100,
    moduleFilter: 'Vocabulary',
    unlocked: false,
    unlockedAt: null,
  },
  {
    id: 'ach_vocab_30_day_retention',
    title: '30 Day Retention',
    description: 'Maintain a 30 day Vocabulary review streak',
    criteriaType: 'streak',
    criteriaValue: 30,
    moduleFilter: 'Vocabulary',
    unlocked: false,
    unlockedAt: null,
  },
];
