import type { SupportedInterfaceLanguage } from '../localization.types';

export const EXTRA_UI_TRANSLATIONS: Record<SupportedInterfaceLanguage, Record<string, string>> = {
  en: { 'progress.eloCaption': '/ 5000 ELO', 'progress.targetBadge': 'Target: C1 Senior Tech Lead / Offshore Pitch Ready', 'progress.masteryTitle': 'Engineering Mastery Level', 'progress.eloToNext': '{count} more Elo to reach {level}. Keep practicing!', 'progress.maxBand': 'Highest CEFR band reached. Maintain your excellence!', 'progress.learningVelocity': 'Learning Velocity:', 'progress.velocityUnit': 'ELO/week', 'progress.estTarget': '⏱️ Est. ~3.8 weeks to C1 Target', 'curriculum.todaysBestTask': "Today's Best Task" },
  tr: { 'progress.eloCaption': '/ 5000 ELO', 'progress.targetBadge': 'Hedef: C1 Kıdemli Teknik Lider / Yurt Dışı Teklif Hazır', 'progress.masteryTitle': 'Mühendislik Ustalık Seviyesi', 'progress.eloToNext': '{level} için {count} Elo daha. Pratik yapmaya devam et!', 'progress.maxBand': 'En yüksek CEFR seviyesine ulaşıldı. Mükemmelliğini koru!', 'progress.learningVelocity': 'Öğrenme Hızı:', 'progress.velocityUnit': 'ELO/hafta', 'progress.estTarget': '⏱️ C1 hedefine tahmini ~3.8 hafta', 'curriculum.todaysBestTask': 'Bugünün En İyi Görevi' },
  ar: { 'progress.eloCaption': '/ 5000 نقطة', 'progress.targetBadge': 'الهدف: C1 قائد تقني أول / جاهز للعروض الدولية', 'progress.masteryTitle': 'مستوى الإتقان الهندسي', 'progress.eloToNext': '{count} نقطة إضافية للوصول إلى {level}. استمر في التدريب!', 'progress.maxBand': 'تم الوصول إلى أعلى مستوى CEFR. حافظ على تميزك!', 'progress.learningVelocity': 'سرعة التعلم:', 'progress.velocityUnit': 'نقطة/أسبوع', 'progress.estTarget': '⏱️ حوالي 3.8 أسابيع للوصول إلى هدف C1', 'curriculum.todaysBestTask': 'أفضل مهمة اليوم' },
  de: { 'progress.eloCaption': '/ 5000 ELO', 'progress.targetBadge': 'Ziel: C1 Senior Tech Lead / Offshore-Angebot bereit', 'progress.masteryTitle': 'Ingenieurmeister-Level', 'progress.eloToNext': '{count} Elo mehr, um {level} zu erreichen. Übe weiter!', 'progress.maxBand': 'Höchstes CEFR-Niveau erreicht. Behalte deine Exzellenz bei!', 'progress.learningVelocity': 'Lerngeschwindigkeit:', 'progress.velocityUnit': 'ELO/Woche', 'progress.estTarget': '⏱️ Geschätzt ~3,8 Wochen bis zum C1-Ziel', 'curriculum.todaysBestTask': 'Beste Aufgabe des Tages' },
  es: { 'progress.eloCaption': '/ 5000 ELO', 'progress.targetBadge': 'Objetivo: C1 Líder Técnico Senior / Listo para Ofertas Offshore', 'progress.masteryTitle': 'Nivel de Maestría en Ingeniería', 'progress.eloToNext': '{count} Elo más para alcanzar {level}. ¡Sigue practicando!', 'progress.maxBand': 'Nivel CEFR más alto alcanzado. ¡Mantén tu excelencia!', 'progress.learningVelocity': 'Velocidad de Aprendizaje:', 'progress.velocityUnit': 'ELO/semana', 'progress.estTarget': '⏱️ Estimado ~3.8 semanas para el objetivo C1', 'curriculum.todaysBestTask': 'Mejor Tarea de Hoy' },
  pt: { 'progress.eloCaption': '/ 5000 ELO', 'progress.targetBadge': 'Meta: C1 Líder Técnico Sênior / Pronto para Propostas Offshore', 'progress.masteryTitle': 'Nível de Maestria em Engenharia', 'progress.eloToNext': '{count} Elo a mais para alcançar {level}. Continue praticando!', 'progress.maxBand': 'Nível CEFR mais alto alcançado. Mantenha sua excelência!', 'progress.learningVelocity': 'Velocidade de Aprendizado:', 'progress.velocityUnit': 'ELO/semana', 'progress.estTarget': '⏱️ Estimado ~3,8 semanas para a meta C1', 'curriculum.todaysBestTask': 'Melhor Tarefa de Hoje' },
  fr: { 'progress.eloCaption': '/ 5000 ELO', 'progress.targetBadge': 'Objectif : C1 Responsable Technique Senior / Prêt pour Offres Offshore', 'progress.masteryTitle': 'Niveau de Maîtrise en Ingénierie', 'progress.eloToNext': '{count} Elo de plus pour atteindre {level}. Continuez à pratiquer !', 'progress.maxBand': 'Plus haut niveau CEFR atteint. Maintenez votre excellence !', 'progress.learningVelocity': "Vitesse d'Apprentissage :", 'progress.velocityUnit': 'ELO/semaine', 'progress.estTarget': "⏱️ Estimé ~3,8 semaines pour l'objectif C1", 'curriculum.todaysBestTask': 'Meilleure Tâche du Jour' },
  ru: { 'progress.eloCaption': '/ 5000 ELO', 'progress.targetBadge': 'Цель: C1 Старший Технический Руководитель / Готов к Offshore Предложениям', 'progress.masteryTitle': 'Уровень Инженерного Мастерства', 'progress.eloToNext': '{count} Elo больше, чтобы достичь {level}. Продолжайте практиковаться!', 'progress.maxBand': 'Достигнут наивысший уровень CEFR. Поддерживайте совершенство!', 'progress.learningVelocity': 'Скорость Обучения:', 'progress.velocityUnit': 'ELO/неделю', 'progress.estTarget': '⏱️ Приблизительно ~3,8 недели до цели C1', 'curriculum.todaysBestTask': 'Лучшее задание на сегодня' },
  zh: { 'progress.eloCaption': '/ 5000 ELO', 'progress.targetBadge': '目标：C1 高级技术主管 / 离岸投标就绪', 'progress.masteryTitle': '工程精通级别', 'progress.eloToNext': '再获得 {count} Elo 即可达到 {level}。继续练习！', 'progress.maxBand': '已达到最高 CEFR 等级。保持卓越！', 'progress.learningVelocity': '学习速度：', 'progress.velocityUnit': 'ELO/周', 'progress.estTarget': '⏱️ 预计约 3.8 周达到 C1 目标', 'curriculum.todaysBestTask': '今日最佳任务' },
  ja: { 'progress.eloCaption': '/ 5000 ELO', 'progress.targetBadge': '目標：C1 シニアテックリード / オフショア提案準備完了', 'progress.masteryTitle': 'エンジニアリング習熟度レベル', 'progress.eloToNext': '{level} に到達するにはあと {count} Elo。練習を続けて！', 'progress.maxBand': '最高 CEFR バンドに到達。卓越性を維持してください！', 'progress.learningVelocity': '学習速度：', 'progress.velocityUnit': 'ELO/週', 'progress.estTarget': '⏱️ C1 目標まで推定約 3.8 週間', 'curriculum.todaysBestTask': '今日のベストタスク' },
  it: { 'progress.eloCaption': '/ 5000 ELO', 'progress.targetBadge': 'Obiettivo: C1 Responsabile Tecnico Senior / Pronto per Offerte Offshore', 'progress.masteryTitle': 'Livello di Maestria Ingegneristica', 'progress.eloToNext': '{count} Elo in più per raggiungere {level}. Continua a esercitarti!', 'progress.maxBand': 'Raggiunto il livello CEFR più alto. Mantieni la tua eccellenza!', 'progress.learningVelocity': 'Velocità di Apprendimento:', 'progress.velocityUnit': 'ELO/settimana', 'progress.estTarget': "⏱️ Stimato ~3,8 settimane per l'obiettivo C1", 'curriculum.todaysBestTask': 'Migliore Attività di Oggi' },
  vi: { 'progress.eloCaption': '/ 5000 ELO', 'progress.targetBadge': 'Mục tiêu: C1 Lãnh đạo Kỹ thuật Cấp cao / Sẵn sàng cho Đề xuất Offshore', 'progress.masteryTitle': 'Cấp độ Thành thạo Kỹ thuật', 'progress.eloToNext': 'Cần thêm {count} Elo để đạt {level}. Hãy tiếp tục luyện tập!', 'progress.maxBand': 'Đã đạt cấp độ CEFR cao nhất. Hãy duy trì sự xuất sắc!', 'progress.learningVelocity': 'Tốc độ Học:', 'progress.velocityUnit': 'ELO/tuần', 'progress.estTarget': '⏱️ Ước tính ~3,8 tuần để đạt mục tiêu C1', 'curriculum.todaysBestTask': 'Nhiệm vụ tốt nhất hôm nay' },
  pl: { 'progress.eloCaption': '/ 5000 ELO', 'progress.targetBadge': 'Cel: C1 Starszy Lider Techniczny / Gotowy do Ofert Offshore', 'progress.masteryTitle': 'Poziom Mistrzostwa Inżynierskiego', 'progress.eloToNext': '{count} Elo więcej, aby osiągnąć {level}. Kontynuuj praktykę!', 'progress.maxBand': 'Osiągnięto najwyższy poziom CEFR. Utrzymuj doskonałość!', 'progress.learningVelocity': 'Prędkość Nauki:', 'progress.velocityUnit': 'ELO/tydzień', 'progress.estTarget': '⏱️ Szacunkowo ~3,8 tygodnia do celu C1', 'curriculum.todaysBestTask': 'Najlepsze zadanie dnia' },
  id: { 'progress.eloCaption': '/ 5000 ELO', 'progress.targetBadge': 'Target: C1 Pemimpin Teknis Senior / Siap untuk Penawaran Offshore', 'progress.masteryTitle': 'Tingkat Penguasaan Teknik', 'progress.eloToNext': '{count} Elo lagi untuk mencapai {level}. Terus berlatih!', 'progress.maxBand': 'Tingkat CEFR tertinggi tercapai. Pertahankan keunggulan Anda!', 'progress.learningVelocity': 'Kecepatan Belajar:', 'progress.velocityUnit': 'ELO/minggu', 'progress.estTarget': '⏱️ Estimasi ~3,8 minggu untuk target C1', 'curriculum.todaysBestTask': 'Tugas Terbaik Hari Ini' },
  nl: { 'progress.eloCaption': '/ 5000 ELO', 'progress.targetBadge': 'Doel: C1 Senior Tech Lead / Klaar voor Offshore Aanbiedingen', 'progress.masteryTitle': 'Niveau van Technische Meesterschap', 'progress.eloToNext': '{count} Elo meer om {level} te bereiken. Blijf oefenen!', 'progress.maxBand': 'Hoogste CEFR-niveau bereikt. Behoud je excellentie!', 'progress.learningVelocity': 'Leersnelheid:', 'progress.velocityUnit': 'ELO/week', 'progress.estTarget': '⏱️ Geschat ~3,8 weken tot het C1-doel', 'curriculum.todaysBestTask': 'Beste taak van vandaag' },
};