import { MissionDifficulty } from '@/core/learning';
import { VocabularyDiscipline, VocabularyEntry } from './vocabulary.types';

type PartOfSpeech = VocabularyEntry['partOfSpeech'];

interface VocabularyContentRow {
  word: string;
  partOfSpeech: PartOfSpeech;
  CEFR: VocabularyEntry['CEFR'];
  discipline: VocabularyDiscipline;
  meaning: string;
  definition: string;
  example: string;
  synonyms: string[];
  collocations: string[];
  difficulty: MissionDifficulty;
  tags: string[];
}

const row = (
  word: string,
  partOfSpeech: PartOfSpeech,
  CEFR: VocabularyEntry['CEFR'],
  discipline: VocabularyDiscipline,
  meaning: string,
  definition: string,
  example: string,
  synonyms: string[],
  collocations: string[],
  difficulty: MissionDifficulty,
  tags: string[]
): VocabularyContentRow => ({
  word,
  partOfSpeech,
  CEFR,
  discipline,
  meaning,
  definition,
  example,
  synonyms,
  collocations,
  difficulty,
  tags,
});

type ExpansionCategory = {
  discipline: VocabularyDiscipline;
  CEFR: VocabularyEntry['CEFR'];
  difficulty: MissionDifficulty;
  tags: string[];
  context: string;
  terms: string[];
};

const expansionCategories: ExpansionCategory[] = [
  {
    discipline: 'Electrical Engineering',
    CEFR: 'B2',
    difficulty: 'Intermediate',
    tags: ['electrical', 'power', 'installation'],
    context: 'electrical installation and power distribution',
    terms: [
      'earthing conductor',
      'protective relay',
      'ring main unit',
      'feeder pillar',
      'cable gland',
      'gland plate',
      'neutral bar',
      'earth leakage',
      'short-circuit rating',
      'fault level',
      'selectivity study',
      'voltage drop',
      'load schedule',
      'single line diagram',
      'panel schedule',
      'cable schedule',
      'termination kit',
      'insulation tester',
      'megger reading',
      'phase sequence',
      'surge protection',
      'harmonic distortion',
      'power factor',
      'capacitor bank',
      'bus coupler',
      'incomer breaker',
      'outgoing feeder',
      'control wiring',
      'interposing relay',
      'auxiliary contact',
    ],
  },
  {
    discipline: 'Mechanical Engineering',
    CEFR: 'B2',
    difficulty: 'Intermediate',
    tags: ['mechanical', 'hvac', 'piping'],
    context: 'mechanical services, HVAC, and piping coordination',
    terms: [
      'chilled water header',
      'differential pressure',
      'balancing valve',
      'strainer basket',
      'flexible connector',
      'expansion joint',
      'pump alignment',
      'vibration isolator',
      'air separator',
      'chemical dosing',
      'pressure gauge',
      'temperature sensor',
      'duct transition',
      'volume control damper',
      'fire damper',
      'access panel',
      'condensate drain',
      'fan coil unit',
      'air handling unit',
      'static pressure',
      'flow rate',
      'hydrostatic test',
      'flushing plan',
      'commissioning valve',
      'bypass line',
      'isolation valve',
      'pump curve',
      'heat exchanger',
      'thermal insulation',
      'pipe support',
    ],
  },
  {
    discipline: 'Civil Engineering',
    CEFR: 'B2',
    difficulty: 'Intermediate',
    tags: ['civil', 'structure', 'site'],
    context: 'civil works, structural coordination, and site execution',
    terms: [
      'blinding concrete',
      'reinforcement bar',
      'rebar spacing',
      'concrete cover',
      'formwork release',
      'anchor bolt',
      'embedment plate',
      'construction joint',
      'expansion joint',
      'level survey',
      'setting out',
      'compaction test',
      'backfilling layer',
      'screed level',
      'plinth foundation',
      'core drilling',
      'sleeve opening',
      'blockwork wall',
      'waterproofing membrane',
      'slope correction',
      'drainage channel',
      'manhole cover',
      'trench excavation',
      'shoring system',
      'load-bearing wall',
      'slab opening',
      'structural clearance',
      'grouting work',
      'as-built survey',
      'site benchmark',
    ],
  },
  {
    discipline: 'Architecture',
    CEFR: 'B2',
    difficulty: 'Intermediate',
    tags: ['architecture', 'finishes', 'coordination'],
    context: 'architectural finishes and multidisciplinary coordination',
    terms: [
      'finish schedule',
      'ceiling void',
      'access hatch',
      'wall penetration',
      'fire-rated wall',
      'door hardware',
      'ironmongery schedule',
      'room data sheet',
      'mock-up approval',
      'material sample',
      'joint sealant',
      'skirting detail',
      'floor transition',
      'ceiling grid',
      'paint system',
      'tile layout',
      'facade panel',
      'cladding support',
      'shopfront glazing',
      'acoustic panel',
      'signage zone',
      'architectural opening',
      'finish interface',
      'room numbering',
      'reflected ceiling plan',
      'door swing',
      'clear opening',
      'fire stopping detail',
      'snag item',
      'visual inspection',
    ],
  },
  {
    discipline: 'Construction',
    CEFR: 'B1',
    difficulty: 'Beginner',
    tags: ['construction', 'site', 'daily work'],
    context: 'construction site reporting and work-front control',
    terms: [
      'work front',
      'site access',
      'material delivery',
      'installation crew',
      'daily manpower',
      'look-ahead plan',
      'site constraint',
      'temporary works',
      'permit to work',
      'area handover',
      'progress photo',
      'inspection request',
      'work sequence',
      'site instruction',
      'access scaffold',
      'lifting area',
      'storage area',
      'housekeeping',
      'temporary lighting',
      'site clearance',
      'work permit',
      'toolbox briefing',
      'supervisor approval',
      'material shortage',
      'installation delay',
      'site obstruction',
      'interface area',
      'daily report',
      'shift handover',
      'closeout action',
    ],
  },
  {
    discipline: 'Commissioning',
    CEFR: 'C1',
    difficulty: 'Advanced',
    tags: ['commissioning', 'testing', 'handover'],
    context: 'commissioning, functional verification, and handover readiness',
    terms: [
      'pre-commissioning',
      'functional test',
      'integrated systems test',
      'cause-and-effect matrix',
      'sequence of operation',
      'commissioning dossier',
      'test script',
      'witness test',
      'performance test',
      'setpoint verification',
      'loop check',
      'point-to-point test',
      'interface signal',
      'alarm acknowledgement',
      'trend log',
      'operational readiness',
      'energization permit',
      'startup procedure',
      'load test',
      'acceptance criteria',
      'test sheet',
      'deficiency list',
      'commissioning hold',
      'retest record',
      'handover package',
      'training record',
      'O&M manual',
      'spare parts list',
      'system demonstration',
      'final acceptance',
    ],
  },
  {
    discipline: 'QA/QC',
    CEFR: 'B2',
    difficulty: 'Intermediate',
    tags: ['quality', 'inspection', 'documentation'],
    context: 'quality control inspection and corrective action tracking',
    terms: [
      'inspection request',
      'material inspection request',
      'non-conformance report',
      'corrective action',
      'preventive action',
      'root cause',
      'hold point',
      'witness point',
      'inspection checklist',
      'approved sample',
      'quality record',
      'closure evidence',
      'defect notice',
      'snag closure',
      'method statement',
      'ITP stage',
      'calibration certificate',
      'traceability record',
      'document control',
      'inspection status',
      'acceptance criteria',
      'rework instruction',
      'quality observation',
      'site surveillance',
      'punch item',
      'verification record',
      'compliance matrix',
      'material approval',
      'test certificate',
      'inspection release',
    ],
  },
  {
    discipline: 'HSE',
    CEFR: 'B2',
    difficulty: 'Intermediate',
    tags: ['safety', 'hse', 'risk'],
    context: 'health, safety, and environmental site control',
    terms: [
      'risk assessment',
      'method statement briefing',
      'job safety analysis',
      'lockout tagout',
      'arc-flash boundary',
      'confined space',
      'working at height',
      'lifting plan',
      'exclusion zone',
      'hot work permit',
      'emergency response',
      'near miss',
      'unsafe condition',
      'safety observation',
      'PPE compliance',
      'first aid station',
      'fire watch',
      'spill kit',
      'environmental control',
      'waste segregation',
      'manual handling',
      'scaffold tag',
      'fall arrest',
      'isolation point',
      'danger tag',
      'gas test',
      'incident report',
      'safety induction',
      'evacuation route',
      'permit suspension',
    ],
  },
  {
    discipline: 'Procurement',
    CEFR: 'B2',
    difficulty: 'Intermediate',
    tags: ['procurement', 'supplier', 'submittal'],
    context:
      'procurement tracking, supplier communication, and technical submittals',
    terms: [
      'purchase order',
      'technical submittal',
      'compliance statement',
      'delivery commitment',
      'lead time',
      'expediting report',
      'supplier deviation',
      'material requisition',
      'quotation comparison',
      'commercial offer',
      'technical offer',
      'factory acceptance test notice',
      'shipping document',
      'packing list',
      'certificate of origin',
      'warranty certificate',
      'spare parts quotation',
      'long-lead item',
      'vendor drawing',
      'submittal register',
      'procurement log',
      'delivery note',
      'material approval',
      'supplier clarification',
      'manufacturing schedule',
      'inspection release note',
      'shipment tracking',
      'customs clearance',
      'procurement risk',
      'replacement item',
    ],
  },
  {
    discipline: 'Project Management',
    CEFR: 'B2',
    difficulty: 'Intermediate',
    tags: ['project management', 'planning', 'controls'],
    context:
      'project controls, reporting, scheduling, and stakeholder communication',
    terms: [
      'baseline schedule',
      'critical path',
      'progress curve',
      'recovery plan',
      'delay notice',
      'extension of time',
      'milestone forecast',
      'constraint register',
      'risk register',
      'action tracker',
      'decision log',
      'interface matrix',
      'stakeholder update',
      'weekly dashboard',
      'earned value',
      'look-ahead schedule',
      'resource histogram',
      'cash flow forecast',
      'change request',
      'variation order',
      'site instruction',
      'minutes of meeting',
      'coordination action',
      'document register',
      'submission forecast',
      'approval cycle',
      'progress narrative',
      'project closeout',
      'handover milestone',
      'lessons learned',
    ],
  },
  {
    discipline: 'Hospital Projects',
    CEFR: 'C1',
    difficulty: 'Advanced',
    tags: ['hospital', 'healthcare', 'MEP'],
    context:
      'hospital project systems, clinical areas, and healthcare handover',
    terms: [
      'isolation room',
      'medical gas outlet',
      'nurse call system',
      'operating theatre',
      'clean room pressure',
      'HEPA filtration',
      'critical power',
      'essential supply',
      'IPS panel',
      'bedhead trunking',
      'clinical handwash basin',
      'infection control',
      'pressure cascade',
      'air change rate',
      'medical equipment interface',
      'laminar airflow',
      'patient area',
      'life safety branch',
      'medical IT system',
      'clinical commissioning',
      'sterile corridor',
      'recovery room',
      'oxygen manifold',
      'vacuum plant',
      'pendant system',
      'scrub station',
      'healthcare compliance',
      'operational policy',
      'clinical user training',
      'hospital handover',
    ],
  },
  {
    discipline: 'Data Centers',
    CEFR: 'C1',
    difficulty: 'Advanced',
    tags: ['data center', 'critical systems', 'resilience'],
    context: 'data center critical infrastructure and resilience communication',
    terms: [
      'white space',
      'rack density',
      'power usage effectiveness',
      'redundant path',
      'N+1 redundancy',
      'dual power feed',
      'static transfer switch',
      'UPS autonomy',
      'battery runtime',
      'busway tap-off',
      'hot aisle containment',
      'cold aisle containment',
      'CRAC unit',
      'leak detection',
      'structured cabling',
      'fiber backbone',
      'meet-me room',
      'remote power panel',
      'branch circuit monitoring',
      'capacity planning',
      'resilience tier',
      'failover test',
      'load bank test',
      'maintenance bypass',
      'critical load',
      'environmental monitoring',
      'access control',
      'security vestibule',
      'incident escalation',
      'service continuity',
    ],
  },
  {
    discipline: 'Oil & Gas',
    CEFR: 'C1',
    difficulty: 'Advanced',
    tags: ['oil and gas', 'industrial', 'hazardous area'],
    context: 'oil and gas industrial projects and hazardous area coordination',
    terms: [
      'hazardous area',
      'zone classification',
      'explosion-proof enclosure',
      'intrinsically safe circuit',
      'gas detector',
      'flame detector',
      'emergency shutdown',
      'process interlock',
      'control valve',
      'pressure safety valve',
      'piping class',
      'hydrocarbon service',
      'hot tapping',
      'line walkdown',
      'punch category',
      'mechanical completion',
      'pre-startup safety review',
      'permit to work',
      'isolation certificate',
      'blind flange',
      'leak test',
      'purging operation',
      'nitrogen blanket',
      'instrument air',
      'DCS panel',
      'ESD loop',
      'fire and gas system',
      'cause and effect chart',
      'commissioning punch',
      'startup readiness',
    ],
  },
  {
    discipline: 'Testing & Commissioning',
    CEFR: 'C1',
    difficulty: 'Advanced',
    tags: ['testing', 'commissioning', 'verification'],
    context:
      'testing and commissioning records across electrical and MEP systems',
    terms: [
      'test procedure',
      'test record',
      'calibrated instrument',
      'pre-test briefing',
      'acceptance test',
      'performance verification',
      'functional demonstration',
      'integrated test',
      'startup checklist',
      'energization checklist',
      'load step',
      'trip test',
      'alarm test',
      'interlock verification',
      'signal simulation',
      'trend capture',
      'defect retest',
      'witness signature',
      'commissioning certificate',
      'system readiness',
      'operating parameter',
      'test limitation',
      'temporary bypass',
      'test permit',
      'instrument loop',
      'point schedule',
      'sequence validation',
      'response time',
      'final test report',
      'client acceptance',
    ],
  },
  {
    discipline: 'Professional Communication',
    CEFR: 'B2',
    difficulty: 'Intermediate',
    tags: ['communication', 'emails', 'meetings'],
    context:
      'professional engineering communication in emails, reports, and meetings',
    terms: [
      'for your review',
      'please confirm',
      'pending approval',
      'subject to verification',
      'as discussed',
      'with reference to',
      'for record purposes',
      'kindly advise',
      'action required',
      'open item',
      'closed item',
      'responsible party',
      'target date',
      'agreed action',
      'technical justification',
      'supporting evidence',
      'clarification request',
      'reply by return',
      'status update',
      'progress narrative',
      'professional tone',
      'concise summary',
      'meeting outcome',
      'follow-up action',
      'escalation path',
      'formal response',
      'document reference',
      'submission status',
      'approval condition',
      'next step',
      'executive summary',
      'formal clarification',
      'site correspondence',
      'technical narrative',
      'review comment',
      'response matrix',
      'coordination record',
      'transmittal note',
      'document workflow',
      'approval route',
      'status narrative',
      'commercial impact',
      'technical impact',
      'recommended action',
      'pending response',
      'closure statement',
      'evidence package',
      'review deadline',
      'comment resolution',
      'contractual notice',
      'project correspondence',
      'engineering judgement',
      'discipline input',
      'interface response',
      'issue escalation',
      'stakeholder comment',
      'design response',
      'site confirmation',
      'action closure',
      'document revision',
      'handover note',
      'project memo',
      'technical email',
      'meeting summary',
      'decision record',
      'discipline response',
      'review cycle',
      'acceptance note',
      'query response',
      'closeout summary',
    ],
  },
];

function buildExpansionRows(): VocabularyContentRow[] {
  // Discipline-specific Turkish meaning generators
  const getMeaning = (term: string, discipline: string): string => {
    const meaningMap: Record<string, Record<string, string>> = {
      'Electrical Engineering': {
        'earthing conductor': 'topraklama iletkeni',
        'protective relay': 'koruma rölesi',
        'ring main unit': 'halka şebekesi ünitesi',
        'feeder pillar': 'besleyici direği',
        'cable gland': 'kablo pabucu',
        'gland plate': 'pabuc plakası',
        'neutral bar': 'nötr bara',
        'earth leakage': 'topraklama kaçağı',
        'short-circuit rating': 'kısa devre dayanımı',
        'fault level': 'ariza seviyesi',
        'selectivity study': 'selektiflik çalışması',
        'voltage drop': 'gerilim düşümü',
        'load plan': 'yük planı',
        'single line diagram': 'tek hat şeması',
        'panel schedule': 'pano programı',
        'cable schedule': 'kablo programı',
        'termination kit': 'uç bağlantı seti',
        'insulation tester': 'yalıtım test cihazı',
        'megger reading': 'megger okuması',
        'phase sequence': 'faz sırası',
        'surge protection': 'dalgalanma koruması',
        'harmonic distortion': 'harmonik bozulma',
        'power factor': 'güç faktörü',
        'capacitor bank': 'kondansatör bankı',
        'bus coupler': 'bara kuple',
        'incomer breaker': 'giriş devre kesici',
        'outgoing feeder': 'çıkış besleyici',
        'control wiring': 'kontrol kablajı',
        'interposing relay': 'ara röle',
        'auxiliary contact': 'yardımcı kontak',
      },
      'Mechanical Engineering': {
        'chilled water header': 'soğuk su manifoldu',
        'differential pressure': 'basınç farkı',
        'balancing valve': 'dengelerme vanası',
        'strainer basket': 'süzgeç sepeti',
        'flexible connector': 'esnek bağlantı',
        'expansion joint': 'genleşme derzi',
        'pump alignment': 'pompa hizalama',
        'vibration isolator': 'titreşim izolatörü',
        'air separator': 'hava ayırıcı',
        'chemical dosing': 'kimyasal dozlama',
        'pressure gauge': 'basınç ölçer',
        'temperature sensor': 'sıcaklık sensörü',
        'duct transition': 'kanal geçişi',
        'volume control damper': 'hacim kontrol kapısı',
        'fire damper': 'yangın kapısı',
        'access panel': 'erişim paneli',
        'condensate drain': 'yoğuşma gideri',
        'fan coil unit': 'fan-coil ünitesi',
        'air handling unit': 'hava işleme ünitesi',
        'static pressure': 'statik basınç',
        'flow rate': 'debi',
        'hydrostatic test': 'hidrostatik test',
        'flushing plan': 'temizleme planı',
        'commissioning valve': 'devreye alma vanası',
        'bypass line': 'by-pass hattı',
        'isolation valve': 'ayırma vanası',
        'pump curve': 'pompa eğrisi',
        'heat exchanger': 'ısı değiştirici',
        'thermal insulation': 'ısı yalıtımı',
        'pipe support': 'boru konsolu',
      },
      'Civil Engineering': {
        'blinding concrete': 'göz betonu',
        'reinforcement bar': 'donatı çubuğu',
        'rebar spacing': 'donatı aralığı',
        'concrete cover': 'beton örtüsü',
        'formwork release': 'kalıp sökme',
        'anchor bolt': 'ankraj cıvatası',
        'embedment plate': 'gömme plakası',
        'construction joint': 'inşaat derzi',
        'expansion joint': 'genleşme derzi',
        'level survey': 'kot ölçümü',
        'setting out': 'köy ölçümü',
        'compaction test': 'sıkıştırma deneyi',
        'backfilling layer': 'dolgu tabakası',
        'screed level': 'şap kotu',
        'plinth foundation': 'sokak temeli',
        'core drilling': 'karot delme',
        'sleeve opening': 'manşon açığı',
        'blockwork wall': 'blok duvar',
        'waterproofing membrane': 'su yalıtım membranı',
        'slope correction': 'eğim düzeltme',
        'drainage channel': 'drenaj kanalı',
        'manhole cover': 'rögar kapağı',
        'trench excavation': 'kanal kazısı',
        'shoring system': 'destek sistemi',
        'load-bearing wall': 'taşıyıcı duvar',
        'slab opening': 'döşeme boşluğu',
        'structural clearance': 'yapısal geçit',
        'grouting work': 'enjeksiyon çalışması',
        'as-built survey': 'yapıldığı gibi ölçüm',
        'site benchmark': 'saha referans noktası',
      },
      'Architecture': {
        'finish schedule': 'bitiş programı',
        'ceiling void': 'tavan boşluğu',
        'access hatch': 'erişim kapağı',
        'wall penetration': 'duvar geçişi',
        'fire-rated wall': 'yangına dayanıklı duvar',
        'door hardware': 'kapı aksesuarı',
        'ironmongery schedule': 'kapı donanım programı',
        'room data sheet': 'oda veri sayfası',
        'mock-up approval': 'örnek uygulama onayı',
        'material sample': 'malzeme örneği',
        'joint sealant': 'derz mastarı',
        'skirting detail': 'süpürgelik detayı',
        'floor transition': 'zemin geçişi',
        'ceiling grid': 'tavan kafes sistemi',
        'paint system': 'boya sistemi',
        'tile layout': 'seramik yerleşim planı',
        'facade panel': 'cephe paneli',
        'cladding support': 'kaplama destek sistemi',
        'shopfront glazing': 'dükkan cephe camı',
        'acoustic panel': 'akustik panel',
        'signage zone': 'tabela bölgesi',
        'architectural opening': 'mimari açıklık',
        'finish interface': 'bitiş arayüzü',
        'room numbering': 'oda numaralandırma',
        'reflected ceiling plan': 'yansıtılmış tavan planı',
        'door swing': 'kapı açıklık yönü',
        'clear opening': 'temiz geçit',
        'fire stopping detail': 'yangın durdurma detayı',
        'snag item': 'kusur maddesi',
        'visual inspection': 'görsel muayene',
      },
      'Construction': {
        'work front': 'çalışma cepheleri',
        'site access': 'saha girişi',
        'material delivery': 'malzeme teslimatı',
        'installation crew': 'montaj ekibi',
        'daily manpower': 'günlük iş gücü',
        'look-ahead plan': 'ileriye dönük plan',
        'site constraint': 'saha kısıtı',
        'temporary works': 'geçici işler',
        'permit to work': 'çalışma izni',
        'area handover': 'alan teslimi',
        'progress photo': 'ilerleme fotoğrafı',
        'inspection request': 'kontrol talebi',
        'work sequence': 'iş sırası',
        'site instruction': 'saha talimatı',
        'access scaffold': 'erişim iskelesi',
        'lifting area': 'vinç alanı',
        'storage area': 'depolama alanı',
        'housekeeping': 'saha düzeni',
        'temporary lighting': 'geçici aydınlatma',
        'site clearance': 'saha temizliği',
        'work permit': 'çalışma izni',
        'toolbox briefing': 'saha brifingi',
        'supervisor approval': 'şef onayı',
        'material shortage': 'malzeme eksikliği',
        'installation delay': 'montaj gecikmesi',
        'site obstruction': 'saha engeli',
        'interface area': 'arayüz bölgesi',
        'daily report': 'günlük rapor',
        'shift handover': 'vardiya devir teslimi',
        'closeout action': 'kapanış eylemi',
      },
      'Commissioning': {
        'pre-commissioning': 'devreye alma öncesi',
        'functional test': 'fonksiyonel test',
        'integrated systems test': 'entegre sistem testi',
        'cause-and-effect matrix': 'neden-sonuç matrisi',
        'sequence of operation': 'çalışma sırası',
        'commissioning dossier': 'devreye alma dosyası',
        'test script': 'test senaryosu',
        'witness test': 'tanık testi',
        'performance test': 'performans testi',
        'setpoint verification': 'setpoint doğrulaması',
        'loop check': 'çevrim kontrolü',
        'point-to-point test': 'noktadan noktaya test',
        'interface signal': 'arayüz sinyali',
        'alarm acknowledgement': 'alarm onayı',
        'trend log': 'trend kaydı',
        'operational readiness': 'operasyonel hazırlık',
        'energization permit': 'gerilim verme izni',
        'startup procedure': 'çalıştırma prosedürü',
        'load test': 'yük testi',
        'acceptance criteria': 'kabul kriterleri',
        'test sheet': 'test sayfası',
        'deficiency list': 'eksiklik listesi',
        'commissioning hold': 'devreye alma bekleme noktası',
        'retest record': 'yeniden test kaydı',
        'handover package': 'teslim paketi',
        'training record': 'eğitim kaydı',
        'O&M manual': 'işletme ve bakım kılavuzu',
        'spare parts list': 'yedek parça listesi',
        'system demonstration': 'sistem gösterimi',
        'final acceptance': 'final kabul',
      },
      'QA/QC': {
        'inspection request': 'kontrol talebi',
        'material inspection request': 'malzeme kontrol talebi',
        'non-conformance report': 'uygunsuzluk raporu',
        'corrective action': 'düzeltici faaliyet',
        'preventive action': 'önleyici faaliyet',
        'root cause': 'kök neden',
        'hold point': 'bekleme noktası',
        'witness point': 'tanık noktası',
        'inspection checklist': 'kontrol kontrol listesi',
        'approved sample': 'onaylı numune',
        'quality record': 'kalite kaydı',
        'closure evidence': 'kapanış kanıtı',
        'defect notice': 'kusur bildirimi',
        'snag closure': 'kusur kapanışı',
        'method statement': 'iş metodu',
        'ITP stage': 'ITP aşaması',
        'calibration certificate': 'kalibrasyon sertifikası',
        'traceability record': 'izlenebilirlik kaydı',
        'document control': 'doküman kontrolü',
        'inspection status': 'kontrol durumu',
        'acceptance criteria': 'kabul kriterleri',
        'rework instruction': 'yeniden iş talimatı',
        'quality observation': 'kalite gözlemi',
        'site surveillance': 'saha gözetimi',
        'punch item': 'punch maddesi',
        'verification record': 'doğrulama kaydı',
        'compliance matrix': 'uygunluk matrisi',
        'material approval': 'malzeme onayı',
        'test certificate': 'test sertifikası',
        'inspection release': 'kontrol serbest bırakma',
      },
      'HSE': {
        'risk assessment': 'risk değerlendirmesi',
        'method statement briefing': 'iş metodu brifingi',
        'job safety analysis': 'iş güvenliği analizi',
        'lockout tagout': 'kilit etiketleme',
        'arc-flash boundary': 'ark çarpma sınırı',
        'confined space': 'kapalı alan',
        'working at height': 'yükseklikte çalışma',
        'lifting plan': 'vinç planı',
        'exclusion zone': 'yasak bölge',
        'hot work permit': 'sıcak çalışma izni',
        'emergency response': 'acil durum müdahalesi',
        'near miss': 'yaralanmalı kaza',
        'unsafe condition': 'güvensiz durum',
        'safety observation': 'güvenlik gözlemi',
        'PPE compliance': 'KKD uygunluğu',
        'first aid station': 'ilk yardım istasyonu',
        'fire watch': 'yangın gözetimi',
        'spill kit': 'sızıntı kiti',
        'environmental control': 'çevre kontrolü',
        'waste segregation': 'atık ayrıştırma',
        'manual handling': 'manüel taşıma',
        'scaffold tag': 'iskele etiketi',
        'fall arrest': 'düşüş engelleme',
        'isolation point': 'ayırma noktası',
        'danger tag': 'tehlike etiketi',
        'gas test': 'gaz testi',
        'incident report': 'olay raporu',
        'safety induction': 'güvenlik oryantasyonu',
        'evacuation route': 'tahliye yolu',
        'permit suspension': 'izin askıya alma',
      },
      'Project Management': {
        'baseline programme': 'başlangıç programı',
        'critical path': 'kritik yol',
        'progress curve': 'ilerleme eğrisi',
        'recovery plan': 'kurtarma planı',
        'delay notice': 'gecikme bildirimi',
        'extension of time': 'süre uzatımı',
        'milestone forecast': 'kilometre taşı tahmini',
        'constraint register': 'kısıt defteri',
        'risk register': 'risk defteri',
        'action tracker': 'eylem takipçisi',
        'decision log': 'karar kaydı',
        'interface matrix': 'arayüz matrisi',
        'stakeholder update': 'paydaş güncellemesi',
        'weekly dashboard': 'haftalık kontrol paneli',
        'earned value': 'kazanılan değer',
        'look-ahead schedule': 'ileriye dönük program',
        'resource histogram': 'kaynak histogramı',
        'cash flow forecast': 'nakit akışı tahmini',
        'change request': 'değişiklik talebi',
        'variation order': 'değişiklik emri',
        'site instruction': 'saha talimatı',
        'minutes of meeting': 'toplantı tutanağı',
        'coordination action': 'koordinasyon eylemi',
        'document register': 'doküman defteri',
        'submission forecast': 'sunum tahmini',
        'approval cycle': 'onay döngüsü',
        'progress narrative': 'ilerleme hikayesi',
        'project closeout': 'proje kapanışı',
        'handover milestone': 'teslim kilometre taşı',
        'lessons learned': 'alınan dersler',
      },
    };
    return meaningMap[discipline]?.[term] || term;
  };

  // Generate definition based on discipline
  const getDefinition = (term: string, discipline: string, context: string): string => {
    const definitions: Record<string, string> = {
      'Electrical Engineering': `${term}, elektrik dağıtımında ve güvenlikte kritik bir bileşen veya kavramdır. ${context} alanında广泛kullanılır.`,
      'Mechanical Engineering': `${term}, mekanik sistem tasarımında ve işletmesinde temel bir unsurdur. Sistem verimliliği ve güvenilirliği üzerinde doğrudan etkisi vardır.`,
      'Civil Engineering': `${term}, yapısal bütünlük ve inşaat kalitesi açısından temel bir kavramdır. İnşaat mühendisliğinde yapısal uyumluluk için kritiktir.`,
      'Architecture': `${term}, yapılmış mekanların işlevsel ve estetik kalitesine katkıda bulunur. Mimari koordinasyon ve tasarım niyeti için gereklidir.`,
      'Construction': `${term}, inşaat sahalarında günlük olarak kullanılan pratik bir kavramdır. İnşaat kalitesi, güvenliği ve programı üzerinde etkisi vardır.`,
      'Commissioning': `${term}, sistem hazırlığını doğrulamak için devreye alma sırasında test edilir ve belgelenir. Teslim öncesi doğrulanmalıdır.`,
      'QA/QC': `${term}, muayene ve doğrulama sırasında kullanılan bir kalite kontrol kavramdır. Proje şartnamelerine ve standartlarına uygunluğu sağlamaya yardımcı olur.`,
      'HSE': `${term}, saha güvenliği için kritik olan bir sağlık, güvenlik ve çevre kavramdır. Kazaları önlemeye ve düzenleyici uyuma yardımcı olur.`,
      'Project Management': `${term}, planlama ve takip için kullanılan bir proje kontrol kavramıdır. Proje programı, maliyeti ve paydaş iletişimi üzerinde etkisi vardır.`,
    };
    return definitions[discipline] || `${term}, ${context} alanında profesyonel bir mühendislik kavramıdır.`;
  };

  // Generate example based on discipline
  const getExample = (term: string, discipline: string): string => {
    const examples: Record<string, string[]> = {
      'Electrical Engineering': [
        `${term} devreye alma sırasında denetlendi.`,
        `${term} devre enerjilmeden önce kontrol edilmelidir.`,
        `${term} proje şartnamesini karşılamalıdır.`,
        `${term} testi yapıldı ve kaydedildi.`,
      ],
      'Mechanical Engineering': [
        `${term} mekanik tamamlama incelemesi sırasında kontrol edildi.`,
        `${term} çalıştırma öncesi düzgün monte edilmelidir.`,
        `${term} performansı tasarım kriterlerine göre doğrulandı.`,
        `${term} operasyonel hazırlık kontrol listesinde yer alıyor.`,
      ],
      'Civil Engineering': [
        `${term} bir sonraki inşaat aşaması öncesi denetlendi.`,
        `${term} yapısal tasarım şartnamelerine uygun olmalıdır.`,
        `${term} saha muayenesi sırasında müteahhit tarafından doğrulandı.`,
        `${term} kalite kontrol kaydına işlendi.`,
      ],
      'Architecture': [
        `${term} tasarım koordinasyon toplantısında gözden geçirildi.`,
        `${term} mimari niyet ve şartnamelerle uyumlu olmalıdır.`,
        `${term} mimar proje gereksinimlerini karşıladığını onayladı.`,
        `${term} bitiş programında yer alıyor.`,
      ],
      'Construction': [
        `${term} bir sonraki iş cephesine geçmeden önce kontrol edildi.`,
        `${term} saha şefi tarafından günlük yürüyüşte doğrulandı.`,
        `${term} kontrol talebi gönderilmeden önce tamamlanmış olmalıdır.`,
        `${term} iş sırasına göre planlandı.`,
      ],
      'Commissioning': [
        `${term} devreye alma kontrol listesi sırasında test edildi.`,
        `${term} sistem enerjilmesi öncesi doğrulanmalıdır.`,
        `${term} test sonuçları commissioning ekibi tarafından belgelendi.`,
        `${term} operasyonel hazırlık durumunda onaylandı.`,
      ],
      'QA/QC': [
        `${term} kontrol kaydına işlendi.`,
        `${term} onay öncesi kabul kriterlerini karşılamalıdır.`,
        `${term} mühendis tarafından şartnameye göre doğrulandı.`,
        `${term} uygunluk matrisinde yer alıyor.`,
      ],
      'HSE': [
        `${term} güvenlik brifingi sırasında gözden geçirildi.`,
        `${term} çalışma başlamadan önce yerinde olmalıdır.`,
        `${term} saha denetimi sırasında kontrol edildi.`,
        `${term} acil durum müdahalesinde referans olarak kullanıldı.`,
      ],
      'Project Management': [
        `${term} haftalık ilerleme raporunda güncellendi.`,
        `${term} proje kilometre taşı programını etkiliyor.`,
        `${term} proje yöneticisi tarafından durum toplantısında incelendi.`,
        `${term} risk defterine kaydedildi.`,
      ],
    };
    const pool = examples[discipline] || [`The ${term} was verified during the quality review.`];
    return pool[term.length % pool.length];
  };

  // Generate varied collocations
  const getCollocations = (term: string, discipline: string): string[] => {
    const base = [`review ${term}`, `${term} status`, `${term} requirement`];
    const extras: Record<string, string[]> = {
      'Electrical Engineering': [`${term} test`, `${term} setting`, `${term} report`],
      'Mechanical Engineering': [`${term} inspection`, `${term} alignment`, `${term} performance`],
      'Civil Engineering': [`${term} specification`, `${term} tolerance`, `${term} compliance`],
      'Architecture': [`${term} design`, `${term} approval`, `${term} detail`],
      'Construction': [`${term} schedule`, `${term} completion`, `${term} sign-off`],
      'Commissioning': [`${term} checklist`, `${term} verification`, `${term} certificate`],
      'QA/QC': [`${term} record`, `${term} audit`, `${term} certification`],
      'HSE': [`${term} briefing`, `${term} compliance`, `${term} procedure`],
      'Project Management': [`${term} tracking`, `${term} forecast`, `${term} review`],
    };
    return [...base, ...(extras[discipline] || [])];
  };

  return expansionCategories.flatMap((category) =>
    category.terms.map((term) =>
      row(
        term,
        term.includes(' ') ? 'phrase' : 'noun',
        category.CEFR,
        category.discipline,
        getMeaning(term, category.discipline),
        getDefinition(term, category.discipline, category.context),
        getExample(term, category.discipline),
        [],
        getCollocations(term, category.discipline),
        category.difficulty,
        category.tags
      )
    )
  );
}

function dedupeRowsByWord(
  contentRows: VocabularyContentRow[]
): VocabularyContentRow[] {
  const seen = new Set<string>();
  return contentRows.filter((item) => {
    const key = item.word.trim().toLowerCase();
    if (seen.has(key)) return false;
    seen.add(key);
    return true;
  });
}

function buildEntries(rawData: VocabularyContentRow[]): VocabularyEntry[] {
  const beginnerRows = rawData.filter((r) => r.difficulty === 'Beginner');
  const contentRows = rawData.filter((r) => r.difficulty !== 'Beginner');

  const beginnerRowsByWord = new Map(
    beginnerRows.map((item) => [item.word.toLowerCase(), item])
  );
  const leveledExistingRows = [...contentRows, ...buildExpansionRows()].map(
    (item) => beginnerRowsByWord.get(item.word.toLowerCase()) ?? item
  );
  const expanded = dedupeRowsByWord([...leveledExistingRows, ...beginnerRows]);

  return expanded.map((item, index) => ({
    id: `vocab_pro_${(index + 1).toString().padStart(3, '0')}`,
    ...item,
  }));
}

let _entriesPromise: Promise<VocabularyEntry[]> | null = null;
let _entriesSync: VocabularyEntry[] | null = null;

export function loadVocabularyEntries(): Promise<VocabularyEntry[]> {
  if (_entriesSync) return Promise.resolve(_entriesSync);
  if (!_entriesPromise) {
    _entriesPromise = import('./vocabulary.data.json').then((mod) => {
      _entriesSync = buildEntries(mod.default as VocabularyContentRow[]);
      return _entriesSync;
    });
  }
  return _entriesPromise;
}

export function getVocabularyEntries(): VocabularyEntry[] | null {
  return _entriesSync;
}

export function getVocabularyEntriesOrWait(): Promise<VocabularyEntry[]> {
  return loadVocabularyEntries();
}
