import type { TeamWorkspaceSnapshot } from './team.types';

export const DEMO_TEAM_WORKSPACE: TeamWorkspaceSnapshot = {
  organization: {
    id: 'demo-org-engineering',
    name: 'Demo International Project Team',
    createdBy: 'demo-admin',
    createdAt: '2026-06-01T08:00:00.000Z',
  },
  source: 'demo',
  members: [
    {
      id: 'demo-member-1',
      organizationId: 'demo-org-engineering',
      displayName: 'Test Manager',
      email: 'manager@example.invalid',
      role: 'manager',
      discipline: 'MEP Coordination',
      lastActiveAt: '2026-06-29T14:20:00.000Z',
    },
    {
      id: 'demo-member-2',
      organizationId: 'demo-org-engineering',
      displayName: 'Demo Engineer',
      email: 'engineer@example.invalid',
      role: 'learner',
      discipline: 'Electrical Engineering',
      lastActiveAt: '2026-06-28T09:15:00.000Z',
    },
    {
      id: 'demo-member-3',
      organizationId: 'demo-org-engineering',
      displayName: 'Sample Learner',
      email: 'learner@example.invalid',
      role: 'learner',
      discipline: 'QA/QC',
      lastActiveAt: null,
    },
  ],
  summaries: [
    {
      memberId: 'demo-member-1',
      cefrEstimate: 'B2',
      overallProgress: 72,
      completedTasks: 38,
      skillScores: {
        reading: 78,
        writing: 70,
        listening: 76,
        speaking: 68,
        vocabulary: 73,
        grammar: 69,
      },
      mistakeCategories: ['Conciseness'],
      recommendedTasks: ['Lead a coordination meeting roleplay'],
    },
    {
      memberId: 'demo-member-2',
      cefrEstimate: 'B1+',
      overallProgress: 58,
      completedTasks: 24,
      skillScores: {
        reading: 64,
        writing: 54,
        listening: 60,
        speaking: 51,
        vocabulary: 62,
        grammar: 55,
      },
      mistakeCategories: ['Articles', 'Inspection vocabulary'],
      recommendedTasks: [
        'Write an inspection response',
        'Review electrical QA/QC terms',
      ],
    },
    {
      memberId: 'demo-member-3',
      cefrEstimate: 'A2+',
      overallProgress: 31,
      completedTasks: 11,
      skillScores: {
        reading: 42,
        writing: 29,
        listening: 35,
        speaking: 24,
        vocabulary: 38,
        grammar: 30,
      },
      mistakeCategories: ['Past tense', 'Meeting confidence'],
      recommendedTasks: ['Complete the A2 site update lesson'],
    },
  ],
  invitations: [],
};
