export const LOWER_TOLERANCE_MULTIPLIER = 0.75;
export const UPPER_TOLERANCE_MULTIPLIER = 1.15;
export const UNREALISTIC_SPEED_MULTIPLIER = 1.65;
export const UNREALISTIC_SPEED_PENALTY = 0.45;
export const OVERSPEED_RANGE_FACTOR = 0.55;

export const PACE_WEIGHT = 0.5;
export const LENGTH_WEIGHT = 0.3;
export const SENTENCE_RATIO_WEIGHT = 0.2;

export const SENTENCE_COUNT_DIVISOR = 2;
export const FILLER_PENALTY_MULTIPLIER = 8;
export const FILLER_PENALTY_CAP = 35;

export const MIN_PROMPT_TOKEN_LENGTH = 3;

export const PROMPT_COVERAGE_WEIGHT = 0.75;
export const CLARITY_KEYWORD_WEIGHT = 0.25;

export const TECHNICAL_KEYWORD_WEIGHT = 0.7;
export const TECHNICAL_TARGET_TERM_WEIGHT = 0.3;

export const CONFIDENCE_KEYWORD_WEIGHT = 0.55;
export const CONFIDENCE_SENTENCE_WEIGHT = 0.25;
export const CONFIDENCE_NO_FILLER_BONUS = 0.2;
export const CONFIDENCE_FILLER_PENALTY = 0.05;
export const CONFIDENCE_SENTENCE_COUNT_DIVISOR = 3;

export const FINAL_FLUENCY_WEIGHT = 0.22;
export const FINAL_CLARITY_WEIGHT = 0.24;
export const FINAL_GRAMMAR_WEIGHT = 0.18;
export const FINAL_TECHNICAL_WEIGHT = 0.24;
export const FINAL_CONFIDENCE_WEIGHT = 0.12;

export const FLUENCY_STRENGTH_THRESHOLD = 85;
export const CLARITY_STRENGTH_THRESHOLD = 85;
export const TECHNICAL_VOCABULARY_STRENGTH_THRESHOLD = 80;
export const GRAMMAR_STRENGTH_THRESHOLD = 80;
