import { createClient } from '@supabase/supabase-js';
import express from 'express';
import type { Express, NextFunction, Request, RequestHandler, Response } from 'express';
import { randomUUID } from 'node:crypto';
import { mkdir, writeFile } from 'node:fs/promises';
import path from 'node:path';
import { createAIService } from './ai.js';
import { ApiError } from './errors.js';
import { SpeakingSubmitBodySchema, validateBody } from './validation.js';
type AiService = ReturnType<typeof createAIService>;
const UPLOAD_ROOT=path.resolve(process.cwd(),'uploads','speaking');
const ALLOWED_AUDIO_TYPES:Record<string,string>={'audio/webm':'webm','audio/ogg':'ogg','audio/wav':'wav','audio/mpeg':'mp3','audio/mp4':'m4a'};
const MAX_AUDIO_BYTES=15*1024*1024; const AUDIO_BUCKET=process.env.SPEAKING_AUDIO_BUCKET||'speaking-audio';
const uploadToSupabaseStorage=async(userId:string,fileName:string,buffer:Buffer,contentType:string):Promise<string|null>=>{const url=process.env.SUPABASE_URL,key=process.env.SUPABASE_SERVICE_ROLE_KEY;if(!url||!key)return null;const client=createClient(url,key,{auth:{persistSession:false,autoRefreshToken:false}});const storagePath=`${userId}/${fileName}`;const {error}=await client.storage.from(AUDIO_BUCKET).upload(storagePath,buffer,{contentType,upsert:false});if(error)throw new ApiError(502,'audio_storage_failed','Audio could not be stored securely.');const {data,error:signedError}=await client.storage.from(AUDIO_BUCKET).createSignedUrl(storagePath,3600);if(signedError||!data?.signedUrl)throw new ApiError(502,'audio_url_failed','Audio was stored but its access URL failed.');return data.signedUrl;};
interface SpeakingPrompt{id:string;title:string;category:string;level:string;prompt:string;durationHint:string;}
interface SpeakingSubmission{id:string;promptId:string;audioUrl:string;transcript:string;status:'not_graded';reason:'speech_assessment_pipeline_not_configured';submittedAt:string;}
const SPEAKING_PROMPTS:SpeakingPrompt[]=[
{id:'sp-001',title:'Describe a Project You Worked On',category:'professional',level:'B1',prompt:'Describe a recent engineering project you were involved in. Explain your role, the challenges you faced, and the outcome.',durationHint:'2-3 minutes'},
{id:'sp-002',title:'Explain a Technical Concept',category:'technical',level:'B2',prompt:'Explain the concept of torque to a non-engineer. Use everyday examples to make your explanation clear.',durationHint:'2-3 minutes'},
{id:'sp-003',title:'Report a Workplace Issue',category:'professional',level:'B1',prompt:'You have noticed a safety hazard in your workplace. Describe the issue and explain what steps should be taken to address it.',durationHint:'1-2 minutes'},
{id:'sp-004',title:'Present a Design Proposal',category:'technical',level:'C1',prompt:'Present a brief proposal for redesigning a common household tool to improve its usability. Describe the current problems and your solution.',durationHint:'3-4 minutes'},
{id:'sp-005',title:'Discuss Sustainable Practices',category:'professional',level:'B2',prompt:'Discuss how engineers can incorporate sustainable practices into their daily work. Provide specific examples from your field.',durationHint:'2-3 minutes'},
{id:'sp-006',title:'Troubleshooting Scenario',category:'technical',level:'B1',prompt:'A hydraulic pump in your system is making unusual noises and not maintaining pressure. Walk through your troubleshooting steps.',durationHint:'2-3 minutes'},
{id:'sp-007',title:'Team Meeting Discussion',category:'professional',level:'B2',prompt:'You are leading a project status meeting. Summarize the current progress, highlight two risks, and propose mitigation strategies.',durationHint:'3-4 minutes'},
{id:'sp-008',title:'Explain a Reading or Lecture',category:'technical',level:'C1',prompt:'Summarize the key findings from a recent technical paper or lecture you attended. Explain why these findings are significant for your field.',durationHint:'3-4 minutes'}];
const store=new Map<string,SpeakingSubmission[]>();const userSubs=(id:string)=>{if(!store.has(id))store.set(id,[]);return store.get(id)!;};
export const registerSpeakingRoutes=(app:Express,auth:RequestHandler,limiter:RequestHandler,_aiService:AiService):void=>{
app.post('/api/speaking/audio-upload',auth,limiter,express.raw({type:Object.keys(ALLOWED_AUDIO_TYPES),limit:'15mb'}),async(req:Request,res:Response,next:NextFunction)=>{try{const userId=req.auth?.userId;if(!userId)throw new ApiError(401,'authentication_required','Auth required');const contentType=req.headers['content-type']??'',ext=ALLOWED_AUDIO_TYPES[contentType];if(!ext)throw new ApiError(415,'unsupported_media_type',`Unsupported audio content-type: ${contentType}`);const buffer=req.body as Buffer;if(!Buffer.isBuffer(buffer)||buffer.length===0)throw new ApiError(400,'empty_audio','No audio data received');if(buffer.length>MAX_AUDIO_BYTES)throw new ApiError(413,'audio_too_large',`Audio exceeds ${MAX_AUDIO_BYTES} byte limit`);const fileName=`${randomUUID()}.${ext}`,stored=await uploadToSupabaseStorage(userId,fileName,buffer,contentType);if(stored){res.status(201).json({audioUrl:stored,sizeBytes:buffer.length,uploadedAt:new Date().toISOString(),storage:'supabase'});return;}const dir=path.resolve(UPLOAD_ROOT,userId);if(dir!==UPLOAD_ROOT&&!dir.startsWith(UPLOAD_ROOT+path.sep))throw new ApiError(400,'invalid_authenticated_user','Invalid user identifier.');await mkdir(dir,{recursive:true});await writeFile(path.join(dir,fileName),buffer);res.status(201).json({audioUrl:`/uploads/speaking/${userId}/${fileName}`,sizeBytes:buffer.length,uploadedAt:new Date().toISOString(),storage:'local-fallback'});}catch(e){next(e);}});
app.get('/api/speaking/prompts',auth,async(req:Request,res:Response,next:NextFunction)=>{try{if(!req.auth?.userId)throw new ApiError(401,'authentication_required','Auth required');const limit=Math.min(Number(req.query.limit)||10,100),offset=Math.max(Number(req.query.offset)||0,0);res.json({items:SPEAKING_PROMPTS.slice(offset,offset+limit),total:SPEAKING_PROMPTS.length,limit,offset});}catch(e){next(e);}});
app.post('/api/speaking/submit',auth,limiter,validateBody(SpeakingSubmitBodySchema),async(req:Request,res:Response,next:NextFunction)=>{try{const userId=req.auth?.userId;if(!userId)throw new ApiError(401,'authentication_required','Auth required');const {missionId,audioUrl,transcript}=req.validatedBody as {missionId?:string;audioUrl?:string;transcript?:string};const submission:SpeakingSubmission={id:randomUUID(),promptId:missionId??'unknown',audioUrl:audioUrl??'',transcript:transcript?.trim()??'',status:'not_graded',reason:'speech_assessment_pipeline_not_configured',submittedAt:new Date().toISOString()};userSubs(userId).push(submission);res.status(202).json({success:true,id:submission.id,status:submission.status,reason:submission.reason,submittedAt:submission.submittedAt});}catch(e){next(e);}});
app.get('/api/speaking/stats',auth,async(req:Request,res:Response,next:NextFunction)=>{try{const userId=req.auth?.userId;if(!userId)throw new ApiError(401,'authentication_required','Auth required');res.json({totalSubmissions:userSubs(userId).length,gradedSubmissions:0,averageScore:null,byCategory:{},status:'not_configured'});}catch(e){next(e);}});
app.get('/api/speaking/:id',auth,async(req:Request,res:Response,next:NextFunction)=>{try{const userId=req.auth?.userId;if(!userId)throw new ApiError(401,'authentication_required','Auth required');res.json(userSubs(userId).find(x=>x.id===req.params.id)??{notFound:true});}catch(e){next(e);}});
};
