import { PageMetadata } from '@/shared/components/PageMetadata';
import { ShieldAlert } from 'lucide-react';

export type LegalDocument = 'terms' | 'privacy' | 'cookies' | 'refund';

const documents: Record<
  LegalDocument,
  { title: string; summary: string; sections: Array<[string, string]> }
> = {
  terms: {
    title: 'Terms of Service',
    summary:
      'Terms and conditions for using the EngVox engineering communication platform.',
    sections: [
      [
        'Acceptance of terms',
        'By accessing or using EngVox ("the Service"), you agree to be bound by these Terms. If you do not agree, do not use the Service.',
      ],
      [
        'Service description',
        'EngVox provides engineering communication learning tools including vocabulary practice, grammar exercises, reading comprehension, writing workshops, listening training, speaking practice, AI coaching, and interview simulation for construction and engineering professionals.',
      ],
      [
        'User accounts',
        'You are responsible for maintaining the confidentiality of your account credentials. You must notify us immediately of any unauthorized use. One account per person; shared or resold accounts are prohibited.',
      ],
      [
        'Subscription and billing',
        'Free tier provides limited access. Pro plans unlock full features. Subscriptions are billed through Stripe. You may cancel at any time; refunds are handled per our Refund Policy.',
      ],
      [
        'AI-generated content',
        'AI coaching responses, grammar corrections, and interview feedback are generated by artificial intelligence and may contain errors. They are provided as learning aids, not professional advice.',
      ],
      [
        'Intellectual property',
        'Your user-generated content (writing, speaking recordings) remains yours. EngVox retains ownership of the platform, curriculum content, and AI models.',
      ],
      [
        'Prohibited conduct',
        'You may not reverse-engineer the Service, attempt to bypass rate limits, use automated tools to scrape content, or share account access with unauthorized parties.',
      ],
      [
        'Limitation of liability',
        'EngVox is provided "as is" without warranties. We are not liable for indirect, incidental, or consequential damages arising from your use of the Service.',
      ],
      [
        'Governing law',
        'These Terms are governed by the laws of Turkey. Disputes shall be resolved in Istanbul courts.',
      ],
      [
        'Changes to terms',
        'We may update these Terms from time to time. Continued use after changes constitutes acceptance. Material changes will be notified via email or in-app notice.',
      ],
    ],
  },
  privacy: {
    title: 'Privacy Policy (GDPR / KVKK)',
    summary:
      'How EngVox collects, uses, stores, and protects your personal data in compliance with GDPR and Turkish KVKK regulations.',
    sections: [
      [
        'Data controller',
        'EngVox (the "Controller") is responsible for your personal data. Contact: privacy@englishengineer.vercel.app',
      ],
      [
        'Data we collect',
        'Account data (email, display name), learning progress (vocabulary, grammar, scores), usage analytics (page views, feature usage), and optional voice recordings for speaking practice.',
      ],
      [
        'Legal basis for processing',
        'We process data based on: (1) Contract performance — providing the learning service you subscribed to; (2) Legitimate interest — improving the platform; (3) Consent — for optional analytics and marketing.',
      ],
      [
        'Data storage and retention',
        'Learning data is stored locally in your browser by default. Cloud sync occurs only when configured. Account data is retained while your account is active. Analytics data is anonymized after 90 days.',
      ],
      [
        'Your rights (GDPR)',
        'You have the right to: access your data, rectify inaccurate data, erase your data ("right to be forgotten"), restrict processing, data portability, and object to processing. Contact us to exercise these rights.',
      ],
      [
        'Your rights (KVKK)',
        'Under Turkish KVKK: learn whether your data is processed, request information about processing, object to analysis of your data, request deletion of incorrectly processed data, and notify us of corrections.',
      ],
      [
        'Data sharing',
        'We do not sell your data. Data may be shared with: Supabase (authentication/database), Stripe (billing), and AI providers (for coaching features) — all under data processing agreements.',
      ],
      [
        'International transfers',
        'Data may be processed in countries outside Turkey. We ensure adequate protection through Standard Contractual Clauses or equivalent safeguards.',
      ],
      [
        'Cookies and tracking',
        'Essential cookies are used for authentication and preferences. Analytics cookies require your consent. See our Cookie Notice for details.',
      ],
      [
        "Children's privacy",
        'EngVox is not directed at children under 16. We do not knowingly collect data from minors.',
      ],
      [
        'Contact',
        'For privacy inquiries: privacy@englishengineer.vercel.app. You may also file a complaint with the Turkish Data Protection Authority (KVKK).',
      ],
    ],
  },
  cookies: {
    title: 'Cookie Policy',
    summary: 'How EngVox uses cookies and similar technologies.',
    sections: [
      [
        'What are cookies',
        'Cookies are small text files stored on your device when you visit a website. They help us remember your preferences and provide a better experience.',
      ],
      [
        'Essential cookies',
        'Required for authentication, session management, and core functionality. Cannot be disabled. Examples: auth tokens, CSRF protection, load balancer affinity.',
      ],
      [
        'Functional cookies',
        'Remember your preferences (theme, language, sidebar state). Optional but improve your experience.',
      ],
      [
        'Analytics cookies',
        'Help us understand how you use EngVox. Used only with your consent. No personally identifiable information is collected.',
      ],
      [
        'Managing cookies',
        'You can control cookies through your browser settings. Disabling essential cookies may prevent the Service from functioning properly.',
      ],
      [
        'Third-party cookies',
        'Stripe (billing) and Supabase (authentication) may set their own cookies when you use those features.',
      ],
    ],
  },
  refund: {
    title: 'Refund Policy',
    summary: 'Refund terms for EngVox Pro subscriptions.',
    sections: [
      [
        'Eligibility',
        'You may request a refund within 14 days of your initial subscription purchase if you have not used more than 10% of Pro features.',
      ],
      [
        'How to request',
        'Contact support@englishengineer.vercel.app with your account email and reason for the refund request.',
      ],
      [
        'Processing time',
        'Refunds are processed within 5-10 business days. The amount will be credited back to your original payment method via Stripe.',
      ],
      [
        'Exceptions',
        'Refunds are not available for: (1) subscriptions older than 14 days, (2) accounts that violated our Terms of Service, (3) promotional or gifted subscriptions.',
      ],
      [
        'Cancellation',
        'You may cancel your subscription at any time from your Profile > Billing page. Cancellation takes effect at the end of the current billing period. You retain access until then.',
      ],
      [
        'Regional rights',
        'Additional refund rights may apply under Turkish consumer protection law (Tüketici Hakları) or EU regulations. Contact us for region-specific inquiries.',
      ],
    ],
  },
};

const LegalPage = ({ document }: { document: LegalDocument }) => {
  const content = documents[document];
  return (
    <main className="bg-transparent py-10">
      <PageMetadata title={content.title} description={content.summary} />
      <article className="mx-auto max-w-3xl px-4 sm:px-6">
        <p className="public-eyebrow">Product template</p>
        <h1 className="mt-3 text-4xl font-medium text-foreground">
          {content.title}
        </h1>
        <p className="mt-4 leading-7 text-muted-copy">{content.summary}</p>
        <div
          className="mt-8 flex items-start gap-3 rounded-xl border border-warning/20 bg-warning/5 p-4 text-sm font-medium leading-6 text-foreground"
          role="note"
          aria-label="Legal review required"
        >
          <ShieldAlert className="mt-0.5 h-5 w-5 shrink-0" aria-hidden="true" />
          <span>
            This page is a product template and must be reviewed by legal
            counsel before production launch.
          </span>
        </div>
        <div className="mt-8 space-y-8">
          {content.sections.map(([title, text]) => (
            <section key={title} className="border-t border-border-soft pt-6">
              <h2 className="text-xl font-medium text-foreground">{title}</h2>
              <p className="mt-3 leading-7 text-muted-copy">{text}</p>
            </section>
          ))}
        </div>
      </article>
    </main>
  );
};

export default LegalPage;
