import type { InterfaceLanguageOption, SupportedInterfaceLanguage } from './localization.types';

const LANGUAGE_OPTIONS: InterfaceLanguageOption[] = [
  { id: 'en', label: 'English', nativeLabel: 'English', available: true, flag: '🇬🇧' },
  { id: 'tr', label: 'Turkish', nativeLabel: 'Türkçe', available: true, flag: '🇹🇷' },
  { id: 'ar', label: 'Arabic', nativeLabel: 'العربية', available: true, flag: '🇸🇦', dir: 'rtl' },
  { id: 'de', label: 'German', nativeLabel: 'Deutsch', available: true, flag: '🇩🇪' },
  { id: 'es', label: 'Spanish', nativeLabel: 'Español', available: true, flag: '🇪🇸' },
  { id: 'pt', label: 'Portuguese', nativeLabel: 'Português', available: true, flag: '🇧🇷' },
  { id: 'fr', label: 'French', nativeLabel: 'Français', available: true, flag: '🇫🇷' },
  { id: 'ru', label: 'Russian', nativeLabel: 'Русский', available: true, flag: '🇷🇺' },
  { id: 'zh', label: 'Chinese', nativeLabel: '中文', available: true, flag: '🇨🇳' },
  { id: 'ja', label: 'Japanese', nativeLabel: '日本語', available: true, flag: '🇯🇵' },
  { id: 'it', label: 'Italian', nativeLabel: 'Italiano', available: true, flag: '🇮🇹' },
  { id: 'vi', label: 'Vietnamese', nativeLabel: 'Tiếng Việt', available: true, flag: '🇻🇳' },
  { id: 'pl', label: 'Polish', nativeLabel: 'Polski', available: true, flag: '🇵🇱' },
  { id: 'id', label: 'Indonesian', nativeLabel: 'Bahasa Indonesia', available: true, flag: '🇮🇩' },
  { id: 'nl', label: 'Dutch', nativeLabel: 'Nederlands', available: true, flag: '🇳🇱' },
];

export const INTERFACE_LANGUAGES: InterfaceLanguageOption[] = LANGUAGE_OPTIONS.slice().sort(
  (a, b) => a.label.localeCompare(b.label, 'en')
);

export const AVAILABLE_INTERFACE_LANGUAGES = INTERFACE_LANGUAGES.filter(
  (
    language
  ): language is InterfaceLanguageOption & {
    id: SupportedInterfaceLanguage;
  } => language.available
);

export const NAVIGATION_TRANSLATIONS: Record<SupportedInterfaceLanguage, Record<string, string>> = {
  en: {
    Home: 'Home',
    Learning: 'Learning',
    Skills: 'Skills',
    Reading: 'Reading',
    Writing: 'Writing',
    Listening: 'Listening',
    Speaking: 'Speaking',
    Vocabulary: 'Vocabulary',
    Grammar: 'Grammar',
    Tools: 'Tools',
    Profile: 'Profile',
  },
  tr: {
    Home: 'Ana Sayfa',
    Learning: 'Öğrenme',
    Skills: 'Beceriler',
    Reading: 'Okuma',
    Writing: 'Yazma',
    Listening: 'Dinleme',
    Speaking: 'Konuşma',
    Vocabulary: 'Kelime',
    Grammar: 'Dil Bilgisi',
    Tools: 'Araçlar',
    Profile: 'Profil',
  },
  ar: {
    Home: 'الرئيسية',
    Learning: 'التعلم',
    Skills: 'المهارات',
    Reading: 'القراءة',
    Writing: 'الكتابة',
    Listening: 'الاستماع',
    Speaking: 'التحدث',
    Vocabulary: 'المفردات',
    Grammar: 'القواعد',
    Tools: 'الأدوات',
    Profile: 'الملف الشخصي',
  },
  de: {
    Home: 'Startseite',
    Learning: 'Lernen',
    Skills: 'Fähigkeiten',
    Reading: 'Lesen',
    Writing: 'Schreiben',
    Listening: 'Hören',
    Speaking: 'Sprechen',
    Vocabulary: 'Wortschatz',
    Grammar: 'Grammatik',
    Tools: 'Werkzeuge',
    Profile: 'Profil',
  },
  es: {
    Home: 'Inicio',
    Learning: 'Aprendizaje',
    Skills: 'Habilidades',
    Reading: 'Lectura',
    Writing: 'Escritura',
    Listening: 'Escucha',
    Speaking: 'Habla',
    Vocabulary: 'Vocabulario',
    Grammar: 'Gramática',
    Tools: 'Herramientas',
    Profile: 'Perfil',
  },
  pt: {
    Home: 'Início',
    'Learning Hub': 'Centro de Aprendizagem',
    Skills: 'Habilidades',
    Reading: 'Leitura',
    Writing: 'Escrita',
    Listening: 'Audição',
    Speaking: 'Fala',
    Vocabulary: 'Vocabulário',
    Grammar: 'Gramática',
    Tools: 'Ferramentas',
    Profile: 'Perfil',
    Team: 'Equipe',
    'Placement Test': 'Teste de nível',
    'Beta Program': 'Programa Beta',
    'Admin Panel': 'Painel admin',
    Path: 'Caminho',
    Hub: 'Hub',
    Pricing: 'Preços',
  },
  fr: {
    Home: 'Accueil',
    'Learning Hub': "Centre d'apprentissage",
    Skills: 'Compétences',
    Reading: 'Lecture',
    Writing: 'Écriture',
    Listening: 'Écoute',
    Speaking: 'Expression orale',
    Vocabulary: 'Vocabulaire',
    Grammar: 'Grammaire',
    Tools: 'Outils',
    Profile: 'Profil',
    Team: 'Équipe',
    'Placement Test': 'Test de positionnement',
    'Beta Program': 'Programme bêta',
    'Admin Panel': "Panneau d'administration",
    Path: 'Parcours',
    Hub: 'Hub',
    Pricing: 'Tarifs',
  },
  ru: {
    Home: 'Главная',
    'Learning Hub': 'Центр обучения',
    Skills: 'Навыки',
    Reading: 'Чтение',
    Writing: 'Письмо',
    Listening: 'Аудирование',
    Speaking: 'Говорение',
    Vocabulary: 'Лексика',
    Grammar: 'Грамматика',
    Tools: 'Инструменты',
    Profile: 'Профиль',
    Team: 'Команда',
    'Placement Test': 'Тест на уровень',
    'Beta Program': 'Бета-программа',
    'Admin Panel': 'Админ-панель',
    Path: 'Путь',
    Hub: 'Хаб',
    Pricing: 'Цены',
  },
  zh: {
    Home: '首页',
    'Learning Hub': '学习中心',
    Skills: '技能',
    Reading: '阅读',
    Writing: '写作',
    Listening: '听力',
    Speaking: '口语',
    Vocabulary: '词汇',
    Grammar: '语法',
    Tools: '工具',
    Profile: '个人资料',
    Team: '团队',
    'Placement Test': '分级测试',
    'Beta Program': 'Beta 计划',
    'Admin Panel': '管理面板',
    Path: '路径',
    Hub: '中心',
    Pricing: '价格',
  },
  ja: {
    Home: 'ホーム',
    'Learning Hub': '学習ハブ',
    Skills: 'スキル',
    Reading: 'リーディング',
    Writing: 'ライティング',
    Listening: 'リスニング',
    Speaking: 'スピーキング',
    Vocabulary: 'ボキャブラリー',
    Grammar: '文法',
    Tools: 'ツール',
    Profile: 'プロフィール',
    Team: 'チーム',
    'Placement Test': 'レベルチェック',
    'Beta Program': 'ベータプログラム',
    'Admin Panel': '管理パネル',
    Path: 'パス',
    Hub: 'ハブ',
    Pricing: '料金',
  },
  it: {
    Home: 'Home',
    'Learning Hub': 'Hub di Apprendimento',
    Skills: 'Competenze',
    Reading: 'Lettura',
    Writing: 'Scrittura',
    Listening: 'Ascolto',
    Speaking: 'Parlato',
    Vocabulary: 'Vocabolario',
    Grammar: 'Grammatica',
    Tools: 'Strumenti',
    Profile: 'Profilo',
    Team: 'Team',
    'Placement Test': 'Test di Livello',
    'Beta Program': 'Programma Beta',
    'Admin Panel': 'Pannello Admin',
    Path: 'Percorso',
    Hub: 'Hub',
    Pricing: 'Prezzi',
  },
  vi: {
    Home: 'Trang chủ',
    'Learning Hub': 'Trung tâm Học tập',
    Skills: 'Kỹ năng',
    Reading: 'Đọc',
    Writing: 'Viết',
    Listening: 'Nghe',
    Speaking: 'Nói',
    Vocabulary: 'Từ vựng',
    Grammar: 'Ngữ pháp',
    Tools: 'Công cụ',
    Profile: 'Hồ sơ',
    Team: 'Nhóm',
    'Placement Test': 'Kiểm tra Xếp loại',
    'Beta Program': 'Chương trình Beta',
    'Admin Panel': 'Bảng điều khiển Admin',
    Path: 'Lộ trình',
    Hub: 'Trung tâm',
    Pricing: 'Giá cả',
  },
  pl: {
    Home: 'Strona główna',
    'Learning Hub': 'Centrum Nauki',
    Skills: 'Umiejętności',
    Reading: 'Czytanie',
    Writing: 'Pisanie',
    Listening: 'Słuchanie',
    Speaking: 'Mówienie',
    Vocabulary: 'Słownictwo',
    Grammar: 'Gramatyka',
    Tools: 'Narzędzia',
    Profile: 'Profil',
    Team: 'Zespół',
    'Placement Test': 'Test Poziomu',
    'Beta Program': 'Program Beta',
    'Admin Panel': 'Panel Admina',
    Path: 'Ścieżka',
    Hub: 'Centrum',
    Pricing: 'Cennik',
  },
  id: {
    Home: 'Beranda',
    'Learning Hub': 'Pusat Belajar',
    Skills: 'Keterampilan',
    Reading: 'Membaca',
    Writing: 'Menulis',
    Listening: 'Mendengar',
    Speaking: 'Berbicara',
    Vocabulary: 'Kosakata',
    Grammar: 'Tata Bahasa',
    Tools: 'Alat',
    Profile: 'Profil',
    Team: 'Tim',
    'Placement Test': 'Tes Penempatan',
    'Beta Program': 'Program Beta',
    'Admin Panel': 'Panel Admin',
    Path: 'Jalur',
    Hub: 'Pusat',
    Pricing: 'Harga',
  },
  nl: {
    Home: 'Home',
    'Learning Hub': 'Leerplek',
    Skills: 'Vaardigheden',
    Reading: 'Lezen',
    Writing: 'Schrijven',
    Listening: 'Luisteren',
    Speaking: 'Spreken',
    Vocabulary: 'Woordenschat',
    Grammar: 'Grammatica',
    Tools: 'Hulpmiddelen',
    Profile: 'Profiel',
    Team: 'Team',
    'Placement Test': 'Instaptoets',
    'Beta Program': 'Bètaprogramma',
    'Admin Panel': 'Adminpaneel',
    Path: 'Pad',
    Hub: 'Hub',
    Pricing: 'Prijzen',
  },
};
