import type {
  InterfaceLanguageOption,
  SupportedInterfaceLanguage,
  TranslationKey,
} from './localization.types';

export const INTERFACE_LANGUAGES: InterfaceLanguageOption[] = [
  { id: 'en', label: 'English', nativeLabel: 'English', available: true, flag: '🇬🇧' },
  { id: 'tr', label: 'Turkish', nativeLabel: 'Türkçe', available: true, flag: '🇹🇷' },
  { id: 'ar', label: 'Arabic', nativeLabel: 'العربية', available: true, flag: '🇸🇦', dir: 'rtl' },
  { id: 'de', label: 'German', nativeLabel: 'Deutsch', available: true, flag: '🇩🇪' },
  { id: 'es', label: 'Spanish', nativeLabel: 'Español', available: true, flag: '🇪🇸' },
  { id: 'pt', label: 'Portuguese', nativeLabel: 'Português', available: true, flag: '🇧🇷' },
  { id: 'fr', label: 'French', nativeLabel: 'Français', available: true, flag: '🇫🇷' },
  { id: 'ru', label: 'Russian', nativeLabel: 'Русский', available: true, flag: '🇷🇺' },
  { id: 'zh', label: 'Chinese', nativeLabel: '中文', available: true, flag: '🇨🇳' },
  { id: 'ja', label: 'Japanese', nativeLabel: '日本語', available: true, flag: '🇯🇵' },
];

export const AVAILABLE_INTERFACE_LANGUAGES = INTERFACE_LANGUAGES.filter(
  (
    language
  ): language is InterfaceLanguageOption & {
    id: SupportedInterfaceLanguage;
  } => language.available
);

export const UI_TRANSLATIONS: Record<
  SupportedInterfaceLanguage,
  Partial<Record<TranslationKey, string>>
> = {
  en: {
    'nav.home': 'Home',
    'nav.learningHub': 'Learning Hub',
    'nav.skills': 'Skills',
    'nav.reading': 'Reading',
    'nav.writing': 'Writing',
    'nav.listening': 'Listening',
    'nav.speaking': 'Speaking',
    'nav.vocabulary': 'Vocabulary',
    'nav.grammar': 'Grammar',
    'nav.tools': 'Tools',
    'nav.profile': 'Profile',
    'common.language': 'Language',
    'common.comingSoon': 'Coming Soon',
    'common.cancel': 'Cancel',
    'common.close': 'Close',
    'common.submit': 'Submit',
    'common.loading': 'Loading...',
    'common.error': 'Something went wrong',
    'common.retry': 'Try Again',
    'common.save': 'Save',
    'common.delete': 'Delete',
    'common.confirm': 'Confirm',
    'common.back': 'Back',
    'common.next': 'Next',
    'common.copy': 'Copy',
    'common.copied': 'Copied!',
    'translator.title': 'Translate Text Now',
    'translator.sourcePlaceholder': 'Source Text / Technical Document',
    'translator.outputPlaceholder': 'Translated output will appear here automatically...',
    'translator.translating': 'Translating...',
    'translator.translateNow': 'Translate Text Now',
    'translator.copyResult': 'Copy Result',
    'translator.audio': 'Audio',
    'translator.playing': 'Playing...',
    'translator.listenAudio': 'Listen Translated Audio',
    'translator.quickAdd': 'Quick Add:',
    'onboarding.title': 'Build your learning workspace',
    'onboarding.selectDiscipline': 'Select your engineering discipline',
    'onboarding.selectLanguage': 'Select your interface language',
    'onboarding.professionalTrack': 'Professional track',
    'onboarding.electricalFocus': 'Electrical focus',
    'onboarding.industry': 'Industry',
    'onboarding.roleContext': 'Your focus changes the work context, not the CEFR difficulty.',
    'onboarding.giftedModules': 'Included with your discipline',
    'onboarding.giftedModulesDesc':
      'Vocabulary and grammar modules are included free for your selected discipline.',
    'profile.nameLanguage': 'Name and language',
    'profile.firstName': 'First name',
    'profile.lastName': 'Last name',
    'profile.save': 'Save Profile',
    'feedback.open': 'Feedback',
    'feedback.title': 'Closed Beta Feedback',
    'feedback.type': 'Feedback type',
    'feedback.message': 'Feedback message',
    'feedback.context': 'Page or context (optional)',
    'feedback.cancel': 'Cancel',
    'feedback.submit': 'Submit Feedback',
    'pricing.title': 'Pricing',
    'pricing.currentPlan': 'Current plan',
    'pricing.free': 'Free',
    'pricing.pro': 'Pro',
    'pricing.project': 'Project',
    'pricing.baseIncludes': 'Vocabulary + Grammar included',
    'pricing.addons': 'Add-ons available',
    'pricing.monthly': 'Monthly',
    'pricing.annual': 'Annual',
    'learningHub.title': 'Learning Hub',
    'grammar.meaningFunction': 'Meaning and function',
    'grammar.form': 'Form',
    'grammar.practice': 'Mini practice',
    'vocabulary.search': 'Search Vocabulary',
    'vocabulary.saveLearned': 'Save to Learned',
    'landing.heroTag': 'Built for engineers on international projects',
    'landing.heroTitle':
      'Master the emails, RFIs, and site meetings that shape your engineering career.',
    'landing.heroSubtitle':
      'The only platform built specifically for engineering communication — with AI feedback on every attempt.',
    'landing.startFree': 'Start Free',
    'landing.seeFeatures': 'See Features',
    'landing.features': 'Features',
    'landing.featuresDesc':
      'Six specialized modules designed for real-world engineering scenarios.',
    'landing.howItWorks': 'How it works',
    'landing.step1': 'Set your profile',
    'landing.step1Desc':
      'Choose your discipline, current level, and career goals. The system builds a personalized curriculum.',
    'landing.step2': 'Practice real scenarios',
    'landing.step2Desc':
      'Work through authentic engineering communication tasks — from daily reports to client presentations.',
    'landing.step3': 'Track and improve',
    'landing.step3Desc':
      'AI-powered analytics identify weak areas. Spaced repetition ensures you retain what you learn.',
    'landing.pricing': 'Pricing',
    'landing.startFreeUpgrade': 'Start free. Upgrade when ready.',
    'landing.faq': 'FAQ',
    'landing.trust': 'Your data stays local',
    'landing.trustDesc': 'Progress stored in your browser. No account required to start.',
    'discipline.architecture': 'Architecture',
    'discipline.chemical': 'Chemical Engineering',
    'discipline.civil': 'Civil Engineering',
    'discipline.electrical': 'Electrical Engineering',
    'discipline.electronics': 'Electronics Engineering',
    'discipline.hse': 'HSE Engineering',
    'discipline.industrial': 'Industrial Engineering',
    'discipline.mechanical': 'Mechanical Engineering',
    'discipline.mechatronics': 'Mechatronics / Robotics',
    'discipline.software': 'Software Engineering',
    'discipline.architecture.desc': 'Design, Spatial & BIM',
    'discipline.chemical.desc': 'Process, Refining & Safety',
    'discipline.civil.desc': 'Infrastructure & Structures',
    'discipline.electrical.desc': 'Power Systems & Grid',
    'discipline.electronics.desc': 'Semiconductors & Embedded',
    'discipline.hse.desc': 'Safety, Health & Compliance',
    'discipline.industrial.desc': 'Lean, Operations & Supply Chain',
    'discipline.mechanical.desc': 'HVAC, Fluid Dynamics & Machinery',
    'discipline.mechatronics.desc': 'Automation, Control & Robotics',
    'discipline.software.desc': 'Architecture, Cloud & Code',
  },
  tr: {
    'nav.home': 'Ana Sayfa',
    'nav.learningHub': 'Öğrenme Merkezi',
    'nav.skills': 'Beceriler',
    'nav.reading': 'Okuma',
    'nav.writing': 'Yazma',
    'nav.listening': 'Dinleme',
    'nav.speaking': 'Konuşma',
    'nav.vocabulary': 'Kelime',
    'nav.grammar': 'Dil Bilgisi',
    'nav.tools': 'Araçlar',
    'nav.profile': 'Profil',
    'common.language': 'Dil',
    'common.comingSoon': 'Yakında',
    'common.cancel': 'İptal',
    'common.close': 'Kapat',
    'common.submit': 'Gönder',
    'common.loading': 'Yükleniyor...',
    'common.error': 'Bir hata oluştu',
    'common.retry': 'Tekrar Dene',
    'common.save': 'Kaydet',
    'common.delete': 'Sil',
    'common.confirm': 'Onayla',
    'common.back': 'Geri',
    'common.next': 'İleri',
    'common.copy': 'Kopyala',
    'common.copied': 'Kopyalandı!',
    'translator.title': 'Metni Çevir',
    'translator.sourcePlaceholder': 'Kaynak Metin / Teknik Döküman',
    'translator.outputPlaceholder': 'Çevrilmiş çıktı otomatik olarak burada görünecek...',
    'translator.translating': 'Çevriliyor...',
    'translator.translateNow': 'Metni Şimdi Çevir',
    'translator.copyResult': 'Sonucu Kopyala',
    'translator.audio': 'Ses',
    'translator.playing': 'Çalınıyor...',
    'translator.listenAudio': 'Çevrilmiş Sesi Dinle',
    'translator.quickAdd': 'Hızlı Ekle:',
    'onboarding.title': 'Öğrenme alanını oluştur',
    'onboarding.selectDiscipline': 'Mühendislik alanınızı seçin',
    'onboarding.selectLanguage': 'Arayüz dilinizi seçin',
    'onboarding.professionalTrack': 'Mesleki alan',
    'onboarding.electricalFocus': 'Elektrik uzmanlık alanı',
    'onboarding.industry': 'Sektör',
    'onboarding.roleContext':
      'Uzmanlık seçimin iş konusunu değiştirir, CEFR zorluğunu değiştirmez.',
    'onboarding.giftedModules': 'Alanınızla birlikte gelen modüller',
    'onboarding.giftedModulesDesc':
      'Kelime ve dil bilgisi modüleri seçtiğiniz alan için ücretsizdir.',
    'profile.nameLanguage': 'İsim ve dil',
    'profile.firstName': 'Ad',
    'profile.lastName': 'Soyad',
    'profile.save': 'Profili Kaydet',
    'feedback.open': 'Geri Bildirim',
    'feedback.title': 'Kapalı Beta Geri Bildirimi',
    'feedback.type': 'Geri bildirim türü',
    'feedback.message': 'Geri bildirim mesajı',
    'feedback.context': 'Sayfa veya bağlam (isteğe bağlı)',
    'feedback.cancel': 'İptal',
    'feedback.submit': 'Gönder',
    'pricing.title': 'Fiyatlandırma',
    'pricing.currentPlan': 'Mevcut plan',
    'pricing.free': 'Ücretsiz',
    'pricing.pro': 'Pro',
    'pricing.project': 'Proje',
    'pricing.baseIncludes': 'Kelime + Dil Bilgisi dahil',
    'pricing.addons': 'Ek modüller mevcut',
    'pricing.monthly': 'Aylık',
    'pricing.annual': 'Yıllık',
    'learningHub.title': 'Öğrenme Merkezi',
    'grammar.meaningFunction': 'Anlam ve işlev',
    'grammar.form': 'Yapı',
    'grammar.practice': 'Mini alıştırma',
    'vocabulary.search': 'Kelime Ara',
    'vocabulary.saveLearned': 'Öğrenilenlere Kaydet',
    'landing.heroTag': 'Uluslararası projelerde çalışan mühendisler için',
    'landing.heroTitle':
      "Mühendislik kariyerinizi şekillendiren e-postaları, RFI'leri ve saha toplantılarını öğrenin.",
    'landing.heroSubtitle':
      'Mühendislik iletişimi için özel olarak oluşturulmuş tek platform — her denemede yapay zeka geri bildirimi ile.',
    'landing.startFree': 'Ücretsiz Başla',
    'landing.seeFeatures': 'Özellikleri Gör',
    'landing.features': 'Özellikler',
    'landing.featuresDesc':
      'Gerçek dünya mühendislik senaryoları için tasarlanmış altı özel modül.',
    'landing.howItWorks': 'Nasıl çalışır',
    'landing.step1': 'Profilini oluştur',
    'landing.step1Desc':
      'Uzmanlık alanınızı, mevcut seviyenizi ve kariyer hedeflerinizi seçin. Sistem size özel bir müfredat oluşturur.',
    'landing.step2': 'Gerçek senaryolarda pratik yapın',
    'landing.step2Desc':
      'Günlük raporlardan müşteri sunumlarına kadar otantik mühendislik iletişim görevlerinde çalışın.',
    'landing.step3': 'Takip edin ve geliştirin',
    'landing.step3Desc':
      'Yapay zeka destekli analizler zayıf alanları belirler. Aralıklı tekrar öğrendiklerinizi korumanızı sağlar.',
    'landing.pricing': 'Fiyatlandırma',
    'landing.startFreeUpgrade': 'Ücretsiz başla, hazır olunca yükselt.',
    'landing.faq': 'SSS',
    'landing.trust': 'Verileriniz yerel kalır',
    'landing.trustDesc': 'İlerlemeniz tarayıcınızda saklanır. Başlamak için hesap gerekmez.',
    'discipline.architecture': 'Mimarlık',
    'discipline.chemical': 'Kimya Mühendisliği',
    'discipline.civil': 'İnşaat Mühendisliği',
    'discipline.electrical': 'Elektrik Mühendisliği',
    'discipline.electronics': 'Elektronik Mühendisliği',
    'discipline.hse': 'İş Güvenliği Mühendisliği',
    'discipline.industrial': 'Endüstri Mühendisliği',
    'discipline.mechanical': 'Makine Mühendisliği',
    'discipline.mechatronics': 'Mekatronik / Robotik',
    'discipline.software': 'Yazılım Mühendisliği',
    'discipline.architecture.desc': 'Tasarım, Mekansal & BIM',
    'discipline.chemical.desc': 'Proses, Rafineri & Güvenlik',
    'discipline.civil.desc': 'Altyapı & Yapılar',
    'discipline.electrical.desc': 'Güç Sistemleri & Şebeke',
    'discipline.electronics.desc': 'Yarı İletkenler & Gömülü Sistemler',
    'discipline.hse.desc': 'Güvenlik, Sağlık & Uyumluluk',
    'discipline.industrial.desc': 'İnce İşlemler, Operasyon & Tedarik Zinciri',
    'discipline.mechanical.desc': 'HVAC, Akışkan Dinamiği & Makineler',
    'discipline.mechatronics.desc': 'Otomasyon, Kontrol & Robotik',
    'discipline.software.desc': 'Mimari, Bulut & Kod',
  },
  ar: {
    'nav.home': 'الرئيسية',
    'nav.learningHub': 'مركز التعلم',
    'nav.skills': 'المهارات',
    'nav.reading': 'القراءة',
    'nav.writing': 'الكتابة',
    'nav.listening': 'الاستماع',
    'nav.speaking': 'التحدث',
    'nav.vocabulary': 'المفردات',
    'nav.grammar': 'قواعد اللغة',
    'nav.tools': 'الأدوات',
    'nav.profile': 'الملف الشخصي',
    'common.language': 'اللغة',
    'common.comingSoon': 'قريباً',
    'common.cancel': 'إلغاء',
    'common.close': 'إغلاق',
    'common.submit': 'إرسال',
    'common.loading': 'جاري التحميل...',
    'common.error': 'حدث خطأ ما',
    'common.retry': 'حاول مرة أخرى',
    'common.save': 'حفظ',
    'common.delete': 'حذف',
    'common.confirm': 'تأكيد',
    'common.back': 'رجوع',
    'common.next': 'التالي',
    'common.copy': 'نسخ',
    'common.copied': 'تم النسخ!',
    'translator.title': 'ترجمة النص الآن',
    'translator.sourcePlaceholder': 'النص المصدر / المستند التقني',
    'translator.outputPlaceholder': 'ستظهر الترجمة تلقائياً هنا...',
    'translator.translating': 'جاري الترجمة...',
    'translator.translateNow': 'ترجم النص الآن',
    'translator.copyResult': 'نسخ النتيجة',
    'translator.audio': 'الصوت',
    'translator.playing': 'جاري التشغيل...',
    'translator.listenAudio': 'استمع إلى الترجمة الصوتية',
    'translator.quickAdd': 'إضافة سريعة:',
    'onboarding.title': 'أنشئ مساحة تعلمك',
    'onboarding.selectDiscipline': 'اختر تخصصك الهندسي',
    'onboarding.selectLanguage': 'اختر لغة الواجهة',
    'onboarding.professionalTrack': 'المسار المهني',
    'onboarding.electricalFocus': 'تخصص كهربائي',
    'onboarding.industry': 'القطاع',
    'onboarding.roleContext': 'يؤثر تخصصك على سياق العمل، وليس على مستوى CEFR.',
    'onboarding.giftedModules': 'مضمنة مع تخصصك',
    'onboarding.giftedModulesDesc': 'وحدات المفردات والقواعد متضمنة مجاناً لتخصصك المختار.',
    'profile.nameLanguage': 'الاسم واللغة',
    'profile.firstName': 'الاسم الأول',
    'profile.lastName': 'اسم العائلة',
    'profile.save': 'حفظ الملف الشخصي',
    'feedback.open': 'الملاحظات',
    'feedback.title': 'ملاحظات.beta مقفلة',
    'feedback.type': 'نوع الملاحظة',
    'feedback.message': 'رسالة الملاحظة',
    'feedback.context': 'الصفحة أو السياق (اختياري)',
    'feedback.cancel': 'إلغاء',
    'feedback.submit': 'إرسال الملاحظة',
    'pricing.title': 'الأسعار',
    'pricing.currentPlan': 'الخطة الحالية',
    'pricing.free': 'مجاني',
    'pricing.pro': 'برو',
    'pricing.project': 'مشروع',
    'pricing.baseIncludes': 'المفردات + القواعد مشمولة',
    'pricing.addons': 'إضافات متاحة',
    'pricing.monthly': 'شهري',
    'pricing.annual': 'سنوي',
    'learningHub.title': 'مركز التعلم',
    'grammar.meaningFunction': 'المعنى والوظيفة',
    'grammar.form': 'الشكل',
    'grammar.practice': 'تدريب مصغر',
    'vocabulary.search': 'البحث في المفردات',
    'vocabulary.saveLearned': 'حفظ كمُتعلَّم',
    'landing.heroTag': 'مصمم للمهندسين العاملين في المشاريع الدولية',
    'landing.heroTitle': 'أتقن الرسائل وطلبات المعلومات واجتماعات الموقع التي تشكل مسيرتك المهنية.',
    'landing.heroSubtitle':
      'المنصة الوحيدة المصممة خصيصاً للتواصل الهندسي — مع تغذية ارجاعية بالذكاء الاصطناعي.',
    'landing.startFree': 'ابدأ مجاناً',
    'landing.seeFeatures': 'عرض الميزات',
    'landing.features': 'الميزات',
    'landing.featuresDesc': 'ستة وحدات متخصصة مصممة لسيناريوهات الهندسة الواقعية.',
    'landing.howItWorks': 'كيف يعمل',
    'landing.step1': 'أعد ملفك الشخصي',
    'landing.step1Desc':
      'اختر تخصصك ومستواك الحالي وأهداف مسيرتك المهنية. يبني النظام منهاجاً مخصصاً.',
    'landing.step2': 'تدرب على سيناريوهات حقيقية',
    'landing.step2Desc':
      'مارس مهام التواصل الهندسي الأصيلة — من التقارير اليومية إلى العروض التقنية.',
    'landing.step3': 'تتبع وحسّن',
    'landing.step3Desc':
      'تحليلات بالذكاء الاصطناعي تحدد نقاط الضعف. التكرار المتباعد يضمن حفظ ما تتعلمه.',
    'landing.pricing': 'الأسعار',
    'landing.startFreeUpgrade': 'ابدأ مجاناً. قم بالترقية عند الاستعداد.',
    'landing.faq': 'الأسئلة الشائعة',
    'landing.trust': 'بياناتك تبقى محلية',
    'landing.trustDesc': 'يتم تخزين التقدم في متصفحك. لا حاجة لحساب للبدء.',
    'discipline.architecture': 'الهندسة المعمارية',
    'discipline.chemical': 'الهندسة الكيميائية',
    'discipline.civil': 'الهندسة المدنية',
    'discipline.electrical': 'الهندسة الكهربائية',
    'discipline.electronics': 'الهندسة الإلكترونية',
    'discipline.hse': 'هندسة السلامة والصحة والبيئة',
    'discipline.industrial': 'الهندسة الصناعية',
    'discipline.mechanical': 'الهندسة الميكانيكية',
    'discipline.mechatronics': 'الميكاترونكس / الروبوتات',
    'discipline.software': 'هندسة البرمجيات',
    'discipline.architecture.desc': 'التصميم والمكانيات وBIM',
    'discipline.chemical.desc': 'العمليات والتكرير والسلامة',
    'discipline.civil.desc': 'البنية التحتية والهياكل',
    'discipline.electrical.desc': 'أنظمة الطاقة والشبكات',
    'discipline.electronics.desc': 'الأشباه الموصلات والأنظمة المدمجة',
    'discipline.hse.desc': 'السلامة والصحة والامتثال',
    'discipline.industrial.desc': 'النحيف والعمليات وسلسلة التوريد',
    'discipline.mechanical.desc': 'HVAC وديناميكا الموائع والآلات',
    'discipline.mechatronics.desc': 'الأتمتة والتحكم والروبوتات',
    'discipline.software.desc': 'الهندسة المعمارية والسحابة والبرمجة',
  },
  de: {
    'nav.home': 'Startseite',
    'nav.learningHub': 'Lerncenter',
    'nav.skills': 'Fähigkeiten',
    'nav.reading': 'Lesen',
    'nav.writing': 'Schreiben',
    'nav.listening': 'Hören',
    'nav.speaking': 'Sprechen',
    'nav.vocabulary': 'Wortschatz',
    'nav.grammar': 'Grammatik',
    'nav.tools': 'Werkzeuge',
    'nav.profile': 'Profil',
    'common.language': 'Sprache',
    'common.comingSoon': 'Demnächst',
    'common.cancel': 'Abbrechen',
    'common.close': 'Schließen',
    'common.submit': 'Absenden',
    'common.loading': 'Laden...',
    'common.error': 'Etwas ist schiefgelaufen',
    'common.retry': 'Erneut versuchen',
    'common.save': 'Speichern',
    'common.delete': 'Löschen',
    'common.confirm': 'Bestätigen',
    'common.back': 'Zurück',
    'common.next': 'Weiter',
    'common.copy': 'Kopieren',
    'common.copied': 'Kopiert!',
    'translator.title': 'Text jetzt übersetzen',
    'translator.sourcePlaceholder': 'Quelltext / Technisches Dokument',
    'translator.outputPlaceholder': 'Übersetzung erscheint automatisch hier...',
    'translator.translating': 'Übersetzen...',
    'translator.translateNow': 'Text jetzt übersetzen',
    'translator.copyResult': 'Ergebnis kopieren',
    'translator.audio': 'Audio',
    'translator.playing': 'Abspielen...',
    'translator.listenAudio': 'Übersetzung anhören',
    'translator.quickAdd': 'Schnell hinzufügen:',
    'onboarding.title': 'Erstelle deinen Lernbereich',
    'onboarding.selectDiscipline': 'Wähle dein Ingenurfach',
    'onboarding.selectLanguage': 'Wähle deine Bildschirmsprache',
    'onboarding.professionalTrack': 'Beruflicher Schwerpunkt',
    'onboarding.electricalFocus': 'Elektrotechnischer Schwerpunkt',
    'onboarding.industry': 'Branche',
    'onboarding.roleContext': 'Dein Schwerpunkt ändert den Arbeitskontext, nicht die CEFR-Stufe.',
    'onboarding.giftedModules': 'In deinem Fach enthalten',
    'onboarding.giftedModulesDesc':
      'Wortschatz- und Grammatikmodule sind kostenlos in deinem Fach enthalten.',
    'profile.nameLanguage': 'Name und Sprache',
    'profile.firstName': 'Vorname',
    'profile.lastName': 'Nachname',
    'profile.save': 'Profil speichern',
    'feedback.open': 'Feedback',
    'feedback.title': 'Closed Beta Feedback',
    'feedback.type': 'Feedback-Typ',
    'feedback.message': 'Feedback-Nachricht',
    'feedback.context': 'Seite oder Kontext (optional)',
    'feedback.cancel': 'Abbrechen',
    'feedback.submit': 'Feedback absenden',
    'pricing.title': 'Preise',
    'pricing.currentPlan': 'Aktueller Plan',
    'pricing.free': 'Kostenlos',
    'pricing.pro': 'Pro',
    'pricing.project': 'Projekt',
    'pricing.baseIncludes': 'Wortschatz + Grammatik enthalten',
    'pricing.addons': 'Add-ons verfügbar',
    'pricing.monthly': 'Monatlich',
    'pricing.annual': 'Jährlich',
    'learningHub.title': 'Lerncenter',
    'grammar.meaningFunction': 'Bedeutung und Funktion',
    'grammar.form': 'Form',
    'grammar.practice': 'Mini-Übung',
    'vocabulary.search': 'Wortschatz suchen',
    'vocabulary.saveLearned': 'Als gelernt speichern',
    'landing.heroTag': 'Für Ingenieure auf internationalen Projekten entwickelt',
    'landing.heroTitle':
      'Meistere die E-Mails, RFI-Anfragen und Baustellenbesprechungen, die deine Ingenieurkarriere prägen.',
    'landing.heroSubtitle':
      'Die einzige Plattform speziell für die ingenieurtechnische Kommunikation — mit KI-Feedback bei jedem Versuch.',
    'landing.startFree': 'Kostenlos starten',
    'landing.seeFeatures': 'Funktionen ansehen',
    'landing.features': 'Funktionen',
    'landing.featuresDesc': 'Sechs spezialisierte Module für reale ingenieurtechnische Szenarien.',
    'landing.howItWorks': 'So funktioniert es',
    'landing.step1': 'Profil erstellen',
    'landing.step1Desc':
      'Wähle dein Fach, dein aktuelles Niveau und deine Karriereziele. Das System erstellt einen personalisierten Lehrplan.',
    'landing.step2': 'Reale Szenarien üben',
    'landing.step2Desc':
      'Arbeite authentische ingenieurtechnische Kommunikationsaufgaben durch — von täglichen Berichten bis zu Präsentationen.',
    'landing.step3': 'Verfolgen und verbessern',
    'landing.step3Desc':
      'KI-gestützte Analytik identifiziert Schwachstellen. Intervallwiederholung stellt sicher, dass du behältst, was du lernst.',
    'landing.pricing': 'Preise',
    'landing.startFreeUpgrade': 'Kostenlos starten. Upgraden, wenn bereit.',
    'landing.faq': 'FAQ',
    'landing.trust': 'Deine Daten bleiben lokal',
    'landing.trustDesc':
      'Fortschritt wird im Browser gespeichert. Kein Konto zum Starten erforderlich.',
    'discipline.architecture': 'Architektur',
    'discipline.chemical': 'Verfahrenstechnik',
    'discipline.civil': 'Bauingenieurwesen',
    'discipline.electrical': 'Elektrotechnik',
    'discipline.electronics': 'Elektronik',
    'discipline.hse': 'Arbeitssicherheit',
    'discipline.industrial': 'Industrieingenieurwesen',
    'discipline.mechanical': 'Maschinenbau',
    'discipline.mechatronics': 'Mechatronik / Robotik',
    'discipline.software': 'Softwaretechnik',
    'discipline.architecture.desc': 'Entwurf, Raum & BIM',
    'discipline.chemical.desc': 'Verfahren, Raffinerie & Sicherheit',
    'discipline.civil.desc': 'Infrastruktur & Bauwerke',
    'discipline.electrical.desc': 'Energieversorgung & Netz',
    'discipline.electronics.desc': 'Halbleiter & Eingebettete Systeme',
    'discipline.hse.desc': 'Sicherheit, Gesundheit & Compliance',
    'discipline.industrial.desc': 'Lean, Betrieb & Lieferkette',
    'discipline.mechanical.desc': 'HVAC, Strömungsmechanik & Maschinen',
    'discipline.mechatronics.desc': 'Automatisierung, Steuerung & Robotik',
    'discipline.software.desc': 'Architektur, Cloud & Code',
  },
  es: {
    'nav.home': 'Inicio',
    'nav.learningHub': 'Centro de Aprendizaje',
    'nav.skills': 'Habilidades',
    'nav.reading': 'Lectura',
    'nav.writing': 'Escritura',
    'nav.listening': 'Escucha',
    'nav.speaking': 'Habla',
    'nav.vocabulary': 'Vocabulario',
    'nav.grammar': 'Gramática',
    'nav.tools': 'Herramientas',
    'nav.profile': 'Perfil',
    'common.language': 'Idioma',
    'common.comingSoon': 'Próximamente',
    'common.cancel': 'Cancelar',
    'common.close': 'Cerrar',
    'common.submit': 'Enviar',
    'common.loading': 'Cargando...',
    'common.error': 'Algo salió mal',
    'common.retry': 'Intentar de nuevo',
    'common.save': 'Guardar',
    'common.delete': 'Eliminar',
    'common.confirm': 'Confirmar',
    'common.back': 'Atrás',
    'common.next': 'Siguiente',
    'common.copy': 'Copiar',
    'common.copied': '¡Copiado!',
    'translator.title': 'Traducir texto ahora',
    'translator.sourcePlaceholder': 'Texto fuente / Documento técnico',
    'translator.outputPlaceholder': 'La traducción aparecerá aquí automáticamente...',
    'translator.translating': 'Traduciendo...',
    'translator.translateNow': 'Traducir texto ahora',
    'translator.copyResult': 'Copiar resultado',
    'translator.audio': 'Audio',
    'translator.playing': 'Reproduciendo...',
    'translator.listenAudio': 'Escuchar traducción de audio',
    'translator.quickAdd': 'Agregar rápido:',
    'onboarding.title': 'Crea tu espacio de aprendizaje',
    'onboarding.selectDiscipline': 'Selecciona tu disciplina de ingeniería',
    'onboarding.selectLanguage': 'Selecciona tu idioma de interfaz',
    'onboarding.professionalTrack': 'Área profesional',
    'onboarding.electricalFocus': 'Enfoque eléctrico',
    'onboarding.industry': 'Industria',
    'onboarding.roleContext': 'Tu enfoque cambia el contexto laboral, no el nivel CEFR.',
    'onboarding.giftedModules': 'Incluido con tu disciplina',
    'onboarding.giftedModulesDesc':
      'Módulos de vocabulario y gramática incluidos gratis para tu disciplina.',
    'profile.nameLanguage': 'Nombre e idioma',
    'profile.firstName': 'Nombre',
    'profile.lastName': 'Apellido',
    'profile.save': 'Guardar perfil',
    'feedback.open': 'Comentarios',
    'feedback.title': 'Comentarios de Beta Cerrada',
    'feedback.type': 'Tipo de comentario',
    'feedback.message': 'Mensaje de comentario',
    'feedback.context': 'Página o contexto (opcional)',
    'feedback.cancel': 'Cancelar',
    'feedback.submit': 'Enviar comentario',
    'pricing.title': 'Precios',
    'pricing.currentPlan': 'Plan actual',
    'pricing.free': 'Gratis',
    'pricing.pro': 'Pro',
    'pricing.project': 'Proyecto',
    'pricing.baseIncludes': 'Vocabulario + Gramática incluidos',
    'pricing.addons': 'Complementos disponibles',
    'pricing.monthly': 'Mensual',
    'pricing.annual': 'Anual',
    'learningHub.title': 'Centro de Aprendizaje',
    'grammar.meaningFunction': 'Significado y función',
    'grammar.form': 'Forma',
    'grammar.practice': 'Práctica mini',
    'vocabulary.search': 'Buscar vocabulario',
    'vocabulary.saveLearned': 'Guardar como aprendido',
    'landing.heroTag': 'Diseñado para ingenieros en proyectos internacionales',
    'landing.heroTitle':
      'Domina los correos, RFI y reuniones de sitio que moldean tu carrera de ingeniería.',
    'landing.heroSubtitle':
      'La única plataforma diseñada específicamente para la comunicación de ingeniería — con retroalimentación de IA en cada intento.',
    'landing.startFree': 'Empezar gratis',
    'landing.seeFeatures': 'Ver características',
    'landing.features': 'Características',
    'landing.featuresDesc':
      'Seis módulos especializados diseñados para escenarios reales de ingeniería.',
    'landing.howItWorks': 'Cómo funciona',
    'landing.step1': 'Configura tu perfil',
    'landing.step1Desc':
      'Elige tu disciplina, nivel actual y objetivos profesionales. El sistema crea un plan de estudio personalizado.',
    'landing.step2': 'Practica escenarios reales',
    'landing.step2Desc':
      'Realiza tareas auténticas de comunicación de ingeniería — desde informes diarios hasta presentaciones.',
    'landing.step3': 'Rastrea y mejora',
    'landing.step3Desc':
      'Analíticas con IA identifican áreas débiles. La repetición espaciada asegura que retengas lo aprendido.',
    'landing.pricing': 'Precios',
    'landing.startFreeUpgrade': 'Empieza gratis. Mejora cuando estés listo.',
    'landing.faq': 'Preguntas frecuentes',
    'landing.trust': 'Tus datos permanecen locales',
    'landing.trustDesc':
      'El progreso se almacena en tu navegador. No necesitas cuenta para empezar.',
    'discipline.architecture': 'Arquitectura',
    'discipline.chemical': 'Ingeniería Química',
    'discipline.civil': 'Ingeniería Civil',
    'discipline.electrical': 'Ingeniería Eléctrica',
    'discipline.electronics': 'Ingeniería Electrónica',
    'discipline.hse': 'Ingeniería de Seguridad',
    'discipline.industrial': 'Ingeniería Industrial',
    'discipline.mechanical': 'Ingeniería Mecánica',
    'discipline.mechatronics': 'Mecatrónica / Robótica',
    'discipline.software': 'Ingeniería de Software',
    'discipline.architecture.desc': 'Diseño, Espacial & BIM',
    'discipline.chemical.desc': 'Procesos, Refinación & Seguridad',
    'discipline.civil.desc': 'Infraestructura & Estructuras',
    'discipline.electrical.desc': 'Sistemas de Energía & Redes',
    'discipline.electronics.desc': 'Semiconductores & Embebidos',
    'discipline.hse.desc': 'Seguridad, Salud & Cumplimiento',
    'discipline.industrial.desc': 'Lean, Operaciones & Cadena de Suministro',
    'discipline.mechanical.desc': 'HVAC, Dinámica de Fluidos & Maquinaria',
    'discipline.mechatronics.desc': 'Automatización, Control & Robótica',
    'discipline.software.desc': 'Arquitectura, Nube & Código',
  },
  pt: {
    'nav.home': 'Início',
    'nav.learningHub': 'Centro de Aprendizagem',
    'nav.skills': 'Habilidades',
    'nav.reading': 'Leitura',
    'nav.writing': 'Escrita',
    'nav.listening': 'Audição',
    'nav.speaking': 'Fala',
    'nav.vocabulary': 'Vocabulário',
    'nav.grammar': 'Gramática',
    'nav.tools': 'Ferramentas',
    'nav.profile': 'Perfil',
    'common.language': 'Idioma',
    'common.comingSoon': 'Em breve',
    'common.cancel': 'Cancelar',
    'common.close': 'Fechar',
    'common.submit': 'Enviar',
    'common.loading': 'Carregando...',
    'common.error': 'Algo deu errado',
    'common.retry': 'Tentar novamente',
    'common.save': 'Salvar',
    'common.delete': 'Excluir',
    'common.confirm': 'Confirmar',
    'common.back': 'Voltar',
    'common.next': 'Próximo',
    'common.copy': 'Copiar',
    'common.copied': 'Copiado!',
    'translator.title': 'Traduzir texto agora',
    'translator.sourcePlaceholder': 'Texto fonte / Documento técnico',
    'translator.outputPlaceholder': 'A tradução aparecerá aqui automaticamente...',
    'translator.translating': 'Traduzindo...',
    'translator.translateNow': 'Traduzir texto agora',
    'translator.copyResult': 'Copiar resultado',
    'translator.audio': 'Áudio',
    'translator.playing': 'Reproduzindo...',
    'translator.listenAudio': 'Ouvir áudio traduzido',
    'translator.quickAdd': 'Adicionar rápido:',
    'onboarding.title': 'Crie seu espaço de aprendizagem',
    'onboarding.selectDiscipline': 'Selecione sua disciplina de engenharia',
    'onboarding.selectLanguage': 'Selecione o idioma da interface',
    'onboarding.professionalTrack': 'Área profissional',
    'onboarding.electricalFocus': 'Foco elétrico',
    'onboarding.industry': 'Indústria',
    'onboarding.roleContext': 'Seu foco muda o contexto de trabalho, não o nível CEFR.',
    'onboarding.giftedModules': 'Incluído com sua disciplina',
    'onboarding.giftedModulesDesc':
      'Módulos de vocabulário e gramática incluídos gratuitamente para sua disciplina.',
    'profile.nameLanguage': 'Nome e idioma',
    'profile.firstName': 'Nome',
    'profile.lastName': 'Sobrenome',
    'profile.save': 'Salvar perfil',
    'feedback.open': 'Feedback',
    'feedback.title': 'Feedback da Beta Fechada',
    'feedback.type': 'Tipo de feedback',
    'feedback.message': 'Mensagem de feedback',
    'feedback.context': 'Página ou contexto (opcional)',
    'feedback.cancel': 'Cancelar',
    'feedback.submit': 'Enviar feedback',
    'pricing.title': 'Preços',
    'pricing.currentPlan': 'Plano atual',
    'pricing.free': 'Grátis',
    'pricing.pro': 'Pro',
    'pricing.project': 'Projeto',
    'pricing.baseIncludes': 'Vocabulário + Gramática incluídos',
    'pricing.addons': 'Complementos disponíveis',
    'pricing.monthly': 'Mensal',
    'pricing.annual': 'Anual',
    'learningHub.title': 'Centro de Aprendizagem',
    'grammar.meaningFunction': 'Significado e função',
    'grammar.form': 'Forma',
    'grammar.practice': 'Prática mini',
    'vocabulary.search': 'Pesquisar vocabulário',
    'vocabulary.saveLearned': 'Salvar como aprendido',
    'landing.heroTag': 'Projetado para engenheiros em projetos internacionais',
    'landing.heroTitle':
      'Domine os e-mails, RFIs e reuniões de obra que moldam sua carreira de engenharia.',
    'landing.heroSubtitle':
      'A única plataforma projetada especificamente para comunicação de engenharia — com feedback de IA em cada tentativa.',
    'landing.startFree': 'Começar grátis',
    'landing.seeFeatures': 'Ver funcionalidades',
    'landing.features': 'Funcionalidades',
    'landing.featuresDesc':
      'Seis módulos especializados projetados para cenários reais de engenharia.',
    'landing.howItWorks': 'Como funciona',
    'landing.step1': 'Configure seu perfil',
    'landing.step1Desc':
      'Escolha sua disciplina, nível atual e objetivos de carreira. O sistema cria um currículo personalizado.',
    'landing.step2': 'Pratique cenários reais',
    'landing.step2Desc':
      'Realize tarefas autênticas de comunicação de engenharia — de relatórios diários a apresentações.',
    'landing.step3': 'Acompanhe e melhore',
    'landing.step3Desc':
      'Analíticos com IA identificam áreas fracas. Repetição espaçada garante retenção do aprendido.',
    'landing.pricing': 'Preços',
    'landing.startFreeUpgrade': 'Comece grátis. Melhore quando estiver pronto.',
    'landing.faq': 'Perguntas frequentes',
    'landing.trust': 'Seus dados permanecem locais',
    'landing.trustDesc': 'Progresso salvo no navegador. Sem necessidade de conta para começar.',
    'discipline.architecture': 'Arquitetura',
    'discipline.chemical': 'Engenharia Química',
    'discipline.civil': 'Engenharia Civil',
    'discipline.electrical': 'Engenharia Elétrica',
    'discipline.electronics': 'Engenharia Eletrônica',
    'discipline.hse': 'Engenharia de Segurança',
    'discipline.industrial': 'Engenharia Industrial',
    'discipline.mechanical': 'Engenharia Mecânica',
    'discipline.mechatronics': 'Mecatrônica / Robótica',
    'discipline.software': 'Engenharia de Software',
    'discipline.architecture.desc': 'Design, Espacial & BIM',
    'discipline.chemical.desc': 'Processos, Refino & Segurança',
    'discipline.civil.desc': 'Infraestrutura & Estruturas',
    'discipline.electrical.desc': 'Sistemas de Energia & Redes',
    'discipline.electronics.desc': 'Semicondutores & Embarcados',
    'discipline.hse.desc': 'Segurança, Saúde & Conformidade',
    'discipline.industrial.desc': 'Lean, Operações & Cadeia de Suprimentos',
    'discipline.mechanical.desc': 'HVAC, Dinâmica de Fluidos & Maquinário',
    'discipline.mechatronics.desc': 'Automação, Controle & Robótica',
    'discipline.software.desc': 'Arquitetura, Nuvem & Código',
  },
  fr: {
    'nav.home': 'Accueil',
    'nav.learningHub': "Centre d'Apprentissage",
    'nav.skills': 'Compétences',
    'nav.reading': 'Lecture',
    'nav.writing': 'Écriture',
    'nav.listening': 'Écoute',
    'nav.speaking': 'Expression orale',
    'nav.vocabulary': 'Vocabulaire',
    'nav.grammar': 'Grammaire',
    'nav.tools': 'Outils',
    'nav.profile': 'Profil',
    'common.language': 'Langue',
    'common.comingSoon': 'Bientôt disponible',
    'common.cancel': 'Annuler',
    'common.close': 'Fermer',
    'common.submit': 'Soumettre',
    'common.loading': 'Chargement...',
    'common.error': "Une erreur s'est produite",
    'common.retry': 'Réessayer',
    'common.save': 'Enregistrer',
    'common.delete': 'Supprimer',
    'common.confirm': 'Confirmer',
    'common.back': 'Retour',
    'common.next': 'Suivant',
    'common.copy': 'Copier',
    'common.copied': 'Copié !',
    'translator.title': 'Traduire le texte maintenant',
    'translator.sourcePlaceholder': 'Texte source / Document technique',
    'translator.outputPlaceholder': 'La traduction apparaîtra ici automatiquement...',
    'translator.translating': 'Traduction en cours...',
    'translator.translateNow': 'Traduire le texte maintenant',
    'translator.copyResult': 'Copier le résultat',
    'translator.audio': 'Audio',
    'translator.playing': 'Lecture en cours...',
    'translator.listenAudio': 'Écouter la traduction audio',
    'translator.quickAdd': 'Ajout rapide :',
    'onboarding.title': "Créez votre espace d'apprentissage",
    'onboarding.selectDiscipline': "Sélectionnez votre discipline d'ingénierie",
    'onboarding.selectLanguage': "Sélectionnez votre langue d'interface",
    'onboarding.professionalTrack': 'Parcours professionnel',
    'onboarding.electricalFocus': 'Spécialité électrique',
    'onboarding.industry': 'Industrie',
    'onboarding.roleContext': 'Votre spécialité change le contexte de travail, pas le niveau CEFR.',
    'onboarding.giftedModules': 'Inclus avec votre discipline',
    'onboarding.giftedModulesDesc':
      'Les modules de vocabulaire et grammaire sont inclus gratuitement pour votre discipline.',
    'profile.nameLanguage': 'Nom et langue',
    'profile.firstName': 'Prénom',
    'profile.lastName': 'Nom',
    'profile.save': 'Enregistrer le profil',
    'feedback.open': 'Commentaires',
    'feedback.title': 'Commentaires Beta Fermée',
    'feedback.type': 'Type de commentaire',
    'feedback.message': 'Message de commentaire',
    'feedback.context': 'Page ou contexte (optionnel)',
    'feedback.cancel': 'Annuler',
    'feedback.submit': 'Soumettre le commentaire',
    'pricing.title': 'Tarifs',
    'pricing.currentPlan': 'Forfait actuel',
    'pricing.free': 'Gratuit',
    'pricing.pro': 'Pro',
    'pricing.project': 'Projet',
    'pricing.baseIncludes': 'Vocabulaire + Grammaire inclus',
    'pricing.addons': 'Modules complémentaires disponibles',
    'pricing.monthly': 'Mensuel',
    'pricing.annual': 'Annuel',
    'learningHub.title': "Centre d'Apprentissage",
    'grammar.meaningFunction': 'Sens et fonction',
    'grammar.form': 'Forme',
    'grammar.practice': 'Exercice mini',
    'vocabulary.search': 'Rechercher du vocabulaire',
    'vocabulary.saveLearned': 'Enregistrer comme appris',
    'landing.heroTag': 'Conçu pour les ingénieurs sur des projets internationaux',
    'landing.heroTitle':
      "Maîtrisez les e-mails, RFI et réunions de chantier qui façonnent votre carrière d'ingénieur.",
    'landing.heroSubtitle':
      "La seule plateforme conçue spécifiquement pour la communication d'ingénierie — avec feedback IA à chaque tentative.",
    'landing.startFree': 'Commencer gratuitement',
    'landing.seeFeatures': 'Voir les fonctionnalités',
    'landing.features': 'Fonctionnalités',
    'landing.featuresDesc': "Six modules spécialisés conçus pour des scénarios d'ingénierie réels.",
    'landing.howItWorks': 'Comment ça marche',
    'landing.step1': 'Configurez votre profil',
    'landing.step1Desc':
      'Choisissez votre discipline, niveau actuel et objectifs de carrière. Le système construit un programme personnalisé.',
    'landing.step2': 'Entraînez-vous sur des scénarios réels',
    'landing.step2Desc':
      "Travaillez des tâches authentiques de communication d'ingénierie — des rapports quotidiens aux présentations.",
    'landing.step3': 'Suivez et améliorez',
    'landing.step3Desc':
      'Analyses par IA identifiant les points faibles. Répétition espacée pour retenir ce que vous apprenez.',
    'landing.pricing': 'Tarifs',
    'landing.startFreeUpgrade': 'Commencez gratuitement. Passez au supérieur quand vous êtes prêt.',
    'landing.faq': 'FAQ',
    'landing.trust': 'Vos données restent locales',
    'landing.trustDesc':
      'Progrès enregistré dans votre navigateur. Aucun compte nécessaire pour commencer.',
    'discipline.architecture': 'Architecture',
    'discipline.chemical': 'Génie Chimique',
    'discipline.civil': 'Génie Civil',
    'discipline.electrical': 'Génie Électrique',
    'discipline.electronics': 'Électronique',
    'discipline.hse': 'Sécurité Industrielle',
    'discipline.industrial': 'Génie Industriel',
    'discipline.mechanical': 'Génie Mécanique',
    'discipline.mechatronics': 'Mécatronique / Robotique',
    'discipline.software': 'Génie Logiciel',
    'discipline.architecture.desc': 'Design, Spatial & BIM',
    'discipline.chemical.desc': 'Procédés, Raffinage & Sécurité',
    'discipline.civil.desc': 'Infrastructure & Structures',
    'discipline.electrical.desc': 'Systèmes Électriques & Réseaux',
    'discipline.electronics.desc': 'Semi-conducteurs & Embarqués',
    'discipline.hse.desc': 'Sécurité, Santé & Conformité',
    'discipline.industrial.desc': 'Lean, Opérations & Chaîne Logistique',
    'discipline.mechanical.desc': 'HVAC, Dynamique des Fluides & Machines',
    'discipline.mechatronics.desc': 'Automatisation, Commande & Robotique',
    'discipline.software.desc': 'Architecture, Cloud & Code',
  },
  ru: {
    'nav.home': 'Главная',
    'nav.learningHub': 'Центр обучения',
    'nav.skills': 'Навыки',
    'nav.reading': 'Чтение',
    'nav.writing': 'Письмо',
    'nav.listening': 'Аудирование',
    'nav.speaking': 'Говорение',
    'nav.vocabulary': 'Лексика',
    'nav.grammar': 'Грамматика',
    'nav.tools': 'Инструменты',
    'nav.profile': 'Профиль',
    'common.language': 'Язык',
    'common.comingSoon': 'Скоро',
    'common.cancel': 'Отмена',
    'common.close': 'Закрыть',
    'common.submit': 'Отправить',
    'common.loading': 'Загрузка...',
    'common.error': 'Что-то пошло не так',
    'common.retry': 'Попробовать снова',
    'common.save': 'Сохранить',
    'common.delete': 'Удалить',
    'common.confirm': 'Подтвердить',
    'common.back': 'Назад',
    'common.next': 'Далее',
    'common.copy': 'Копировать',
    'common.copied': 'Скопировано!',
    'translator.title': 'Перевести текст сейчас',
    'translator.sourcePlaceholder': 'Исходный текст / Технический документ',
    'translator.outputPlaceholder': 'Перевод появится здесь автоматически...',
    'translator.translating': 'Перевод...',
    'translator.translateNow': 'Перевести текст сейчас',
    'translator.copyResult': 'Копировать результат',
    'translator.audio': 'Аудио',
    'translator.playing': 'Воспроизведение...',
    'translator.listenAudio': 'Прослушать перевод',
    'translator.quickAdd': 'Быстрое добавление:',
    'onboarding.title': 'Создайте своё пространство для обучения',
    'onboarding.selectDiscipline': 'Выберите вашу инженерную специальность',
    'onboarding.selectLanguage': 'Выберите язык интерфейса',
    'onboarding.professionalTrack': 'Профессиональное направление',
    'onboarding.electricalFocus': 'Электротехническая специализация',
    'onboarding.industry': 'Отрасль',
    'onboarding.roleContext': 'Ваша специализация меняет контекст работы, а не уровень CEFR.',
    'onboarding.giftedModules': 'Включено в вашу специальность',
    'onboarding.giftedModulesDesc':
      'Модули лексики и грамматики включены бесплатно для выбранной специальности.',
    'profile.nameLanguage': 'Имя и язык',
    'profile.firstName': 'Имя',
    'profile.lastName': 'Фамилия',
    'profile.save': 'Сохранить профиль',
    'feedback.open': 'Обратная связь',
    'feedback.title': 'Обратная связь закрытой беты',
    'feedback.type': 'Тип отзыва',
    'feedback.message': 'Сообщение отзыва',
    'feedback.context': 'Страница или контекст (необязательно)',
    'feedback.cancel': 'Отмена',
    'feedback.submit': 'Отправить отзыв',
    'pricing.title': 'Цены',
    'pricing.currentPlan': 'Текущий план',
    'pricing.free': 'Бесплатный',
    'pricing.pro': 'Про',
    'pricing.project': 'Проект',
    'pricing.baseIncludes': 'Лексика + Грамматика включены',
    'pricing.addons': 'Дополнения доступны',
    'pricing.monthly': 'Ежемесячно',
    'pricing.annual': 'Ежегодно',
    'learningHub.title': 'Центр обучения',
    'grammar.meaningFunction': 'Значение и функция',
    'grammar.form': 'Форма',
    'grammar.practice': 'Мини-практика',
    'vocabulary.search': 'Поиск лексики',
    'vocabulary.saveLearned': 'Сохранить как изученное',
    'landing.heroTag': 'Создано для инженеров на международных проектах',
    'landing.heroTitle':
      'Овладейте электронными письмами, запросами информации и встречами на объекте, которые формируют вашу инженерную карьеру.',
    'landing.heroSubtitle':
      'Единственная платформа, созданная специально для инженерного общения — с обратной связью ИИ при каждой попытке.',
    'landing.startFree': 'Начать бесплатно',
    'landing.seeFeatures': 'Посмотреть функции',
    'landing.features': 'Функции',
    'landing.featuresDesc': 'Шесть специализированных модулей для реальных инженерных сценариев.',
    'landing.howItWorks': 'Как это работает',
    'landing.step1': 'Настройте профиль',
    'landing.step1Desc':
      'Выберите специальность, текущий уровень и карьерные цели. Система создаст персональную программу.',
    'landing.step2': 'Практикуйте реальные сценарии',
    'landing.step2Desc':
      'Выполняйте аутентичные задачи инженерного общения — от ежедневных отчётов до презентаций.',
    'landing.step3': 'Отслеживайте и улучшайте',
    'landing.step3Desc':
      'Аналитика на основе ИИ выявляет слабые места. Интервальное повторение закрепляет знания.',
    'landing.pricing': 'Цены',
    'landing.startFreeUpgrade': 'Начните бесплатно. Улучшите, когда будете готовы.',
    'landing.faq': 'Вопросы и ответы',
    'landing.trust': 'Ваши данные остаются локальными',
    'landing.trustDesc': 'Прогресс сохраняется в браузере. Для начала не нужна учётная запись.',
    'discipline.architecture': 'Архитектура',
    'discipline.chemical': 'Химическая инженерия',
    'discipline.civil': 'Гражданская инженерия',
    'discipline.electrical': 'Электротехника',
    'discipline.electronics': 'Электроника',
    'discipline.hse': 'Промышленная безопасность',
    'discipline.industrial': 'Инженерная безопасность',
    'discipline.mechanical': 'Машиностроение',
    'discipline.mechatronics': 'Мехатроника / Робототехника',
    'discipline.software': 'Программная инженерия',
    'discipline.architecture.desc': 'Дизайн, Пространство & BIM',
    'discipline.chemical.desc': 'Процессы, Переработка & Безопасность',
    'discipline.civil.desc': 'Инфраструктура & Конструкции',
    'discipline.electrical.desc': 'Системы электроснабжения & Сети',
    'discipline.electronics.desc': 'Полупроводники & Встроенные системы',
    'discipline.hse.desc': 'Безопасность, Здоровье & Соответствие',
    'discipline.industrial.desc': 'Лин-производство, Операции & Логистика',
    'discipline.mechanical.desc': 'HVAC, Гидродинамика & Машины',
    'discipline.mechatronics.desc': 'Автоматизация, Управление & Робототехника',
    'discipline.software.desc': 'Архитектура, Облако & Код',
  },
  zh: {
    'nav.home': '首页',
    'nav.learningHub': '学习中心',
    'nav.skills': '技能',
    'nav.reading': '阅读',
    'nav.writing': '写作',
    'nav.listening': '听力',
    'nav.speaking': '口语',
    'nav.vocabulary': '词汇',
    'nav.grammar': '语法',
    'nav.tools': '工具',
    'nav.profile': '个人资料',
    'common.language': '语言',
    'common.comingSoon': '即将推出',
    'common.cancel': '取消',
    'common.close': '关闭',
    'common.submit': '提交',
    'common.loading': '加载中...',
    'common.error': '出了点问题',
    'common.retry': '重试',
    'common.save': '保存',
    'common.delete': '删除',
    'common.confirm': '确认',
    'common.back': '返回',
    'common.next': '下一步',
    'common.copy': '复制',
    'common.copied': '已复制！',
    'translator.title': '立即翻译文本',
    'translator.sourcePlaceholder': '源文本 / 技术文档',
    'translator.outputPlaceholder': '翻译结果将自动显示在此处...',
    'translator.translating': '翻译中...',
    'translator.translateNow': '立即翻译',
    'translator.copyResult': '复制结果',
    'translator.audio': '音频',
    'translator.playing': '播放中...',
    'translator.listenAudio': '收听翻译音频',
    'translator.quickAdd': '快速添加：',
    'onboarding.title': '创建您的学习空间',
    'onboarding.selectDiscipline': '选择您的工程专业',
    'onboarding.selectLanguage': '选择界面语言',
    'onboarding.professionalTrack': '专业方向',
    'onboarding.electricalFocus': '电气专业',
    'onboarding.industry': '行业',
    'onboarding.roleContext': '您的专业方向改变工作背景，而非CEFR难度。',
    'onboarding.giftedModules': '包含在您的专业中',
    'onboarding.giftedModulesDesc': '词汇和语法模块为您的专业免费提供。',
    'profile.nameLanguage': '姓名和语言',
    'profile.firstName': '名字',
    'profile.lastName': '姓氏',
    'profile.save': '保存资料',
    'feedback.open': '反馈',
    'feedback.title': '封闭测试反馈',
    'feedback.type': '反馈类型',
    'feedback.message': '反馈消息',
    'feedback.context': '页面或上下文（可选）',
    'feedback.cancel': '取消',
    'feedback.submit': '提交反馈',
    'pricing.title': '定价',
    'pricing.currentPlan': '当前计划',
    'pricing.free': '免费',
    'pricing.pro': '专业版',
    'pricing.project': '团队版',
    'pricing.baseIncludes': '包含词汇 + 语法',
    'pricing.addons': '可购买附加模块',
    'pricing.monthly': '月付',
    'pricing.annual': '年付',
    'learningHub.title': '学习中心',
    'grammar.meaningFunction': '含义和功能',
    'grammar.form': '形式',
    'grammar.practice': '迷你练习',
    'vocabulary.search': '搜索词汇',
    'vocabulary.saveLearned': '保存为已学',
    'landing.heroTag': '为参与国际项目的工程师打造',
    'landing.heroTitle': '掌握塑造您工程职业生涯的邮件、信息请求和现场会议。',
    'landing.heroSubtitle': '唯一专为工程沟通打造的平台 — 每次尝试都有AI反馈。',
    'landing.startFree': '免费开始',
    'landing.seeFeatures': '查看功能',
    'landing.features': '功能',
    'landing.featuresDesc': '六个专为真实工程场景设计的专业模块。',
    'landing.howItWorks': '工作原理',
    'landing.step1': '设置您的资料',
    'landing.step1Desc': '选择您的专业、当前水平和职业目标。系统将构建个性化课程。',
    'landing.step2': '练习真实场景',
    'landing.step2Desc': '完成真实的工程沟通任务 — 从日报到客户演示。',
    'landing.step3': '跟踪并提升',
    'landing.step3Desc': 'AI分析识别薄弱环节。间隔重复确保您记住所学内容。',
    'landing.pricing': '定价',
    'landing.startFreeUpgrade': '免费开始，准备好后升级。',
    'landing.faq': '常见问题',
    'landing.trust': '您的数据保留在本地',
    'landing.trustDesc': '进度保存在浏览器中。无需账户即可开始。',
    'discipline.architecture': '建筑学',
    'discipline.chemical': '化学工程',
    'discipline.civil': '土木工程',
    'discipline.electrical': '电气工程',
    'discipline.electronics': '电子工程',
    'discipline.hse': '安全工程',
    'discipline.industrial': '工业工程',
    'discipline.mechanical': '机械工程',
    'discipline.mechatronics': '机电一体化 / 机器人',
    'discipline.software': '软件工程',
    'discipline.architecture.desc': '设计、空间 & BIM',
    'discipline.chemical.desc': '工艺、炼制 & 安全',
    'discipline.civil.desc': '基础设施 & 结构',
    'discipline.electrical.desc': '电力系统 & 电网',
    'discipline.electronics.desc': '半导体 & 嵌入式系统',
    'discipline.hse.desc': '安全、健康 & 合规',
    'discipline.industrial.desc': '精益、运营 & 供应链',
    'discipline.mechanical.desc': '暖通、流体力学 & 机械',
    'discipline.mechatronics.desc': '自动化、控制 & 机器人',
    'discipline.software.desc': '架构、云计算 & 代码',
  },
  ja: {
    'nav.home': 'ホーム',
    'nav.learningHub': 'ラーニングハブ',
    'nav.skills': 'スキル',
    'nav.reading': '読解',
    'nav.writing': 'ライティング',
    'nav.listening': 'リスニング',
    'nav.speaking': 'スピーキング',
    'nav.vocabulary': '語彙',
    'nav.grammar': '文法',
    'nav.tools': 'ツール',
    'nav.profile': 'プロフィール',
    'common.language': '言語',
    'common.comingSoon': '近日公開',
    'common.cancel': 'キャンセル',
    'common.close': '閉じる',
    'common.submit': '送信',
    'common.loading': '読み込み中...',
    'common.error': '問題が発生しました',
    'common.retry': '再試行',
    'common.save': '保存',
    'common.delete': '削除',
    'common.confirm': '確認',
    'common.back': '戻る',
    'common.next': '次へ',
    'common.copy': 'コピー',
    'common.copied': 'コピーしました！',
    'translator.title': 'テキストを今すぐ翻訳',
    'translator.sourcePlaceholder': '原文 / 技術文書',
    'translator.outputPlaceholder': '翻訳結果がここに自動的に表示されます...',
    'translator.translating': '翻訳中...',
    'translator.translateNow': 'テキストを今すぐ翻訳',
    'translator.copyResult': '結果をコピー',
    'translator.audio': 'オーディオ',
    'translator.playing': '再生中...',
    'translator.listenAudio': '翻訳音声を聞く',
    'translator.quickAdd': 'クイック追加：',
    'onboarding.title': '学習スペースを作成',
    'onboarding.selectDiscipline': '工学専攻を選択',
    'onboarding.selectLanguage': 'インターフェース言語を選択',
    'onboarding.professionalTrack': '専門分野',
    'onboarding.electricalFocus': '電気専攻',
    'onboarding.industry': '業界',
    'onboarding.roleContext': '専攻は作業コンテキストを変えますが、CEFRレベルは変えません。',
    'onboarding.giftedModules': '専攻に含まれるもの',
    'onboarding.giftedModulesDesc': '語彙と文法モジュールは選択した専攻で無料提供されます。',
    'profile.nameLanguage': '名前と言語',
    'profile.firstName': '名',
    'profile.lastName': '姓',
    'profile.save': 'プロフィール保存',
    'feedback.open': 'フィードバック',
    'feedback.title': 'クローズドベータフィードバック',
    'feedback.type': 'フィードバックの種類',
    'feedback.message': 'フィードバックメッセージ',
    'feedback.context': 'ページまたはコンテキスト（任意）',
    'feedback.cancel': 'キャンセル',
    'feedback.submit': 'フィードバック送信',
    'pricing.title': '料金',
    'pricing.currentPlan': '現在のプラン',
    'pricing.free': '無料',
    'pricing.pro': 'プロ',
    'pricing.project': 'プロジェクト',
    'pricing.baseIncludes': '語彙 + 文法 含む',
    'pricing.addons': 'アドオン利用可能',
    'pricing.monthly': '月額',
    'pricing.annual': '年額',
    'learningHub.title': 'ラーニングハブ',
    'grammar.meaningFunction': '意味と機能',
    'grammar.form': '形式',
    'grammar.practice': 'ミニ練習',
    'vocabulary.search': '語彙を検索',
    'vocabulary.saveLearned': '学習済みとして保存',
    'landing.heroTag': '海外プロジェクトで働くエンジニアのために開発',
    'landing.heroTitle':
      'エンジニアキャリアを形づくるメール、RFI、現場ミーティングをマスターしよう。',
    'landing.heroSubtitle':
      'エンジニアリングコミュニケーション専用に構築された唯一のプラットフォーム — 各試行でAIフィードバック付き。',
    'landing.startFree': '無料で始める',
    'landing.seeFeatures': '機能を見る',
    'landing.features': '機能',
    'landing.featuresDesc': '実際のエンジニアリングシナリオ向けに設計された6つの専門モジュール。',
    'landing.howItWorks': '仕組み',
    'landing.step1': 'プロフィール設定',
    'landing.step1Desc':
      '専攻、現在のレベル、キャリア目標を選択。システムがパーソナライズされたカリキュラムを作成。',
    'landing.step2': '実際のシナリオで練習',
    'landing.step2Desc': '日報からプレゼンテーションまで、本物のエンジニアリングタスクに取り組む。',
    'landing.step3': '追跡して向上',
    'landing.step3Desc': 'AI分析が弱点を特定。間隔を空けた復習で学んだ内容を定着。',
    'landing.pricing': '料金',
    'landing.startFreeUpgrade': '無料で始め、準備ができたらアップグレード。',
    'landing.faq': 'よくある質問',
    'landing.trust': 'データはローカルに保存',
    'landing.trustDesc': 'ブラウザに進捗を保存。開始にアカウント不要。',
    'discipline.architecture': '建築学',
    'discipline.chemical': '化学工学',
    'discipline.civil': '土木工学',
    'discipline.electrical': '電気工学',
    'discipline.electronics': '電子工学',
    'discipline.hse': '安全工学',
    'discipline.industrial': '工業工学',
    'discipline.mechanical': '機械工学',
    'discipline.mechatronics': 'メカトロニクス / ロボティクス',
    'discipline.software': 'ソフトウェア工学',
    'discipline.architecture.desc': 'デザイン、空間 & BIM',
    'discipline.chemical.desc': 'プロセス、精製 & 安全',
    'discipline.civil.desc': 'インフラ & 構造物',
    'discipline.electrical.desc': '電力系統 & 送電網',
    'discipline.electronics.desc': '半導体 & 組込みシステム',
    'discipline.hse.desc': '安全、健康 & コンプライアンス',
    'discipline.industrial.desc': 'リーン、オペレーション & サプライチェーン',
    'discipline.mechanical.desc': 'HVAC、流体工学 & 機械',
    'discipline.mechatronics.desc': '自動化、制御 & ロボティクス',
    'discipline.software.desc': 'アーキテクチャ、クラウド & コード',
  },
};

export const NAVIGATION_TRANSLATIONS: Record<SupportedInterfaceLanguage, Record<string, string>> = {
  en: {},
  tr: {
    Home: 'Ana Sayfa',
    'Learning Hub': 'Öğrenme Merkezi',
    Skills: 'Beceriler',
    Reading: 'Okuma',
    Writing: 'Yazma',
    Listening: 'Dinleme',
    Speaking: 'Konuşma',
    Vocabulary: 'Kelime',
    Grammar: 'Dil Bilgisi',
    Tools: 'İş Araçları',
    Profile: 'Profil',
    Team: 'Takım & Şirket',
    'Placement Test': 'Seviye Sınavı',
    'Beta Program': 'Beta & Topluluk',
    'Admin Panel': 'Yönetim Paneli',
  },
  ar: {
    Home: 'الرئيسية',
    'Learning Hub': 'مركز التعلم',
    Skills: 'المهارات',
    Reading: 'القراءة',
    Writing: 'الكتابة',
    Listening: 'الاستماع',
    Speaking: 'التحدث',
    Vocabulary: 'المفردات',
    Grammar: 'القواعد',
    Tools: 'الأدوات',
    Profile: 'الملف الشخصي',
    Team: 'الفريق',
    'Placement Test': 'اختبار التعيين',
    'Beta Program': 'برنامج بيتا',
    'Admin Panel': 'لوحة الإدارة',
  },
  de: {
    Home: 'Startseite',
    'Learning Hub': 'Lerncenter',
    Skills: 'Fähigkeiten',
    Reading: 'Lesen',
    Writing: 'Schreiben',
    Listening: 'Hören',
    Speaking: 'Sprechen',
    Vocabulary: 'Wortschatz',
    Grammar: 'Grammatik',
    Tools: 'Werkzeuge',
    Profile: 'Profil',
    Team: 'Team',
    'Placement Test': 'Einstufungstest',
    'Beta Program': 'Beta-Programm',
    'Admin Panel': 'Admin-Bereich',
  },
  es: {
    Home: 'Inicio',
    'Learning Hub': 'Centro de Aprendizaje',
    Skills: 'Habilidades',
    Reading: 'Lectura',
    Writing: 'Escritura',
    Listening: 'Escucha',
    Speaking: 'Habla',
    Vocabulary: 'Vocabulario',
    Grammar: 'Gramática',
    Tools: 'Herramientas',
    Profile: 'Perfil',
    Team: 'Equipo',
    'Placement Test': 'Test de nivel',
    'Beta Program': 'Programa Beta',
    'Admin Panel': 'Panel de administración',
  },
  pt: {
    Home: 'Início',
    'Learning Hub': 'Centro de Aprendizagem',
    Skills: 'Habilidades',
    Reading: 'Leitura',
    Writing: 'Escrita',
    Listening: 'Audição',
    Speaking: 'Fala',
    Vocabulary: 'Vocabulário',
    Grammar: 'Gramática',
    Tools: 'Ferramentas',
    Profile: 'Perfil',
    Team: 'Equipe',
    'Placement Test': 'Teste de nível',
    'Beta Program': 'Programa Beta',
    'Admin Panel': 'Painel admin',
  },
  fr: {
    Home: 'Accueil',
    'Learning Hub': "Centre d'apprentissage",
    Skills: 'Compétences',
    Reading: 'Lecture',
    Writing: 'Écriture',
    Listening: 'Écoute',
    Speaking: 'Expression orale',
    Vocabulary: 'Vocabulaire',
    Grammar: 'Grammaire',
    Tools: 'Outils',
    Profile: 'Profil',
    Team: 'Équipe',
    'Placement Test': 'Test de positionnement',
    'Beta Program': 'Programme bêta',
    'Admin Panel': "Panneau d'administration",
  },
  ru: {
    Home: 'Главная',
    'Learning Hub': 'Центр обучения',
    Skills: 'Навыки',
    Reading: 'Чтение',
    Writing: 'Письмо',
    Listening: 'Аудирование',
    Speaking: 'Говорение',
    Vocabulary: 'Лексика',
    Grammar: 'Грамматика',
    Tools: 'Инструменты',
    Profile: 'Профиль',
    Team: 'Команда',
    'Placement Test': 'Тест на определение уровня',
    'Beta Program': 'Бета-программа',
    'Admin Panel': 'Панель управления',
  },
  zh: {
    Home: '首页',
    'Learning Hub': '学习中心',
    Skills: '技能',
    Reading: '阅读',
    Writing: '写作',
    Listening: '听力',
    Speaking: '口语',
    Vocabulary: '词汇',
    Grammar: '语法',
    Tools: '工具',
    Profile: '个人资料',
    Team: '团队',
    'Placement Test': '分级测试',
    'Beta Program': '测试计划',
    'Admin Panel': '管理面板',
  },
  ja: {
    Home: 'ホーム',
    'Learning Hub': 'ラーニングハブ',
    Skills: 'スキル',
    Reading: '読解',
    Writing: 'ライティング',
    Listening: 'リスニング',
    Speaking: 'スピーキング',
    Vocabulary: '語彙',
    Grammar: '文法',
    Tools: 'ツール',
    Profile: 'プロフィール',
    Team: 'チーム',
    'Placement Test': 'レベルテスト',
    'Beta Program': 'ベータプログラム',
    'Admin Panel': '管理画面',
  },
};
