import { SpeakingMission } from './speaking.types';
import { STARTER_SPEAKING_MISSIONS } from './speaking.starter.data';

const CORE_SPEAKING_MISSIONS: SpeakingMission[] = [
  {
    id: 'speaking_site_meeting',
    title: 'Site Meeting Alignment Brief',
    description:
      'Summarize site constraints, action owners, and installation blockers for a field coordination meeting.',
    scenarioType: 'site_meeting',
    discipline: 'Field Engineering',
    cefrLevel: 'B2',
    difficulty: 'Intermediate',
    estimatedMinutes: 10,
    promptText:
      'The cable tray installation at gridline B4 is blocked by temporary scaffolding, so we need to resequence containment works and confirm access clearance with the civil supervisor before tomorrow morning.',
    expectedKeywords: [
      'cable tray',
      'gridline',
      'scaffolding',
      'resequence',
      'containment',
      'clearance',
      'civil supervisor',
    ],
    grammarTargets: ['blocked by', 'we need to', 'before tomorrow morning'],
    confidenceMarkers: ['confirm', 'coordinate', 'resolve', 'assign', 'verify'],
    syllabicTargets: [
      { word: 'Scaffolding', IPA: '/ˈskæf.əl.dɪŋ/', score: 86 },
      { word: 'Resequence', IPA: '/riːˈsiː.kwəns/', score: 84 },
      { word: 'Containment', IPA: '/kənˈteɪn.mənt/', score: 88 },
      { word: 'Clearance', IPA: '/ˈklɪr.əns/', score: 90 },
    ],
    targetWpm: 145,
    xpReward: 70,
    coinReward: 20,
    eloReward: 14,
  },
  {
    id: 'speaking_toolbox_talk',
    title: 'Daily Toolbox Talk',
    description:
      'Deliver a concise daily safety and work-front briefing for site technicians.',
    scenarioType: 'toolbox_talk',
    discipline: 'Construction Safety',
    cefrLevel: 'B2',
    difficulty: 'Beginner',
    estimatedMinutes: 8,
    promptText:
      'Before any work starts on the energized switchboard area, every technician must verify lockout tags, wear the required arc-flash PPE, and report unsafe access conditions immediately.',
    expectedKeywords: [
      'energized',
      'switchboard',
      'technician',
      'lockout',
      'arc-flash',
      'PPE',
      'unsafe',
    ],
    grammarTargets: [
      'before any work starts',
      'must verify',
      'report immediately',
    ],
    confidenceMarkers: ['must', 'verify', 'report', 'stop', 'escalate'],
    syllabicTargets: [
      { word: 'Energized', IPA: '/ˈen.ər.dʒaɪzd/', score: 82 },
      { word: 'Switchboard', IPA: '/ˈswɪtʃ.bɔːrd/', score: 87 },
      { word: 'Lockout', IPA: '/ˈlɑːk.aʊt/', score: 91 },
      { word: 'Arc-flash', IPA: '/ɑːrk flæʃ/', score: 89 },
    ],
    targetWpm: 135,
    xpReward: 55,
    coinReward: 15,
    eloReward: 10,
  },
  {
    id: 'speaking_consultant_discussion',
    title: 'Consultant Comment Discussion',
    description:
      'Respond professionally to a consultant comment about shop drawing deviation and compliance evidence.',
    scenarioType: 'consultant_discussion',
    discipline: 'Design Compliance',
    cefrLevel: 'C1',
    difficulty: 'Advanced',
    estimatedMinutes: 14,
    promptText:
      'We acknowledge the consultant comment regarding the busbar clearance deviation, and we will submit a revised shop drawing with manufacturer test evidence and updated coordination sections.',
    expectedKeywords: [
      'consultant',
      'busbar',
      'clearance',
      'deviation',
      'shop drawing',
      'manufacturer',
      'coordination',
    ],
    grammarTargets: ['we acknowledge', 'we will submit', 'with evidence'],
    confidenceMarkers: [
      'acknowledge',
      'submit',
      'evidence',
      'revise',
      'comply',
    ],
    syllabicTargets: [
      { word: 'Consultant', IPA: '/kənˈsʌl.tənt/', score: 90 },
      { word: 'Deviation', IPA: '/ˌdiː.viˈeɪ.ʃən/', score: 84 },
      { word: 'Manufacturer', IPA: '/ˌmæn.jəˈfæk.tʃɚ.ɚ/', score: 80 },
      { word: 'Coordination', IPA: '/koʊˌɔːr.dənˈeɪ.ʃən/', score: 86 },
    ],
    targetWpm: 150,
    xpReward: 85,
    coinReward: 25,
    eloReward: 18,
  },
  {
    id: 'speaking_client_presentation',
    title: 'Client Presentation Summary',
    description:
      'Present a high-level technical solution to a non-specialist client without losing engineering precision.',
    scenarioType: 'client_presentation',
    discipline: 'Client Delivery',
    cefrLevel: 'C1',
    difficulty: 'Advanced',
    estimatedMinutes: 16,
    promptText:
      'Our proposed redundancy strategy keeps the chilled water plant operational during a single pump failure by automatically transferring load to the standby unit within the agreed response window.',
    expectedKeywords: [
      'redundancy',
      'chilled water',
      'operational',
      'pump failure',
      'transferring load',
      'standby',
      'response window',
    ],
    grammarTargets: [
      'keeps operational',
      'by automatically transferring',
      'within the agreed',
    ],
    confidenceMarkers: [
      'proposed',
      'keeps',
      'automatically',
      'agreed',
      'assured',
    ],
    syllabicTargets: [
      { word: 'Redundancy', IPA: '/rɪˈdʌn.dən.si/', score: 88 },
      { word: 'Operational', IPA: '/ˌɑː.pəˈreɪ.ʃən.əl/', score: 84 },
      { word: 'Automatically', IPA: '/ˌɑː.t̬əˈmæt̬.ɪ.kəl.i/', score: 82 },
      { word: 'Standby', IPA: '/ˈstænd.baɪ/', score: 92 },
    ],
    targetWpm: 140,
    xpReward: 90,
    coinReward: 28,
    eloReward: 20,
  },
  {
    id: 'speaking_progress_meeting',
    title: 'Progress Meeting Update',
    description:
      'Report schedule movement, blockers, and mitigation actions in a weekly progress meeting.',
    scenarioType: 'progress_meeting',
    discipline: 'Project Controls',
    cefrLevel: 'B2',
    difficulty: 'Intermediate',
    estimatedMinutes: 11,
    promptText:
      'The switchgear delivery delay has shifted the testing sequence by three days, but the team can recover one day by overlapping cable termination checks with panel labeling.',
    expectedKeywords: [
      'switchgear',
      'delivery delay',
      'testing sequence',
      'recover',
      'overlapping',
      'termination',
      'panel labeling',
    ],
    grammarTargets: ['has shifted', 'can recover', 'by overlapping'],
    confidenceMarkers: ['recover', 'overlap', 'mitigate', 'track', 'commit'],
    syllabicTargets: [
      { word: 'Switchgear', IPA: '/ˈswɪtʃ.ɡɪr/', score: 91 },
      { word: 'Sequence', IPA: '/ˈsiː.kwəns/', score: 89 },
      { word: 'Overlapping', IPA: '/ˌoʊ.vɚˈlæp.ɪŋ/', score: 83 },
      { word: 'Termination', IPA: '/ˌtɝː.məˈneɪ.ʃən/', score: 85 },
    ],
    targetWpm: 145,
    xpReward: 70,
    coinReward: 20,
    eloReward: 14,
  },
  {
    id: 'speaking_commissioning_meeting',
    title: 'Commissioning Meeting Handover',
    description:
      'Explain test readiness, acceptance criteria, and open commissioning prerequisites.',
    scenarioType: 'commissioning_meeting',
    discipline: 'Commissioning',
    cefrLevel: 'C1',
    difficulty: 'Advanced',
    estimatedMinutes: 15,
    promptText:
      'Commissioning can proceed once insulation resistance records, relay settings, and point-to-point verification sheets are signed off by quality control and the operations representative.',
    expectedKeywords: [
      'commissioning',
      'insulation resistance',
      'relay settings',
      'point-to-point',
      'verification',
      'quality control',
      'operations',
    ],
    grammarTargets: [
      'can proceed once',
      'are signed off',
      'by quality control',
    ],
    confidenceMarkers: [
      'proceed',
      'verified',
      'signed off',
      'ready',
      'accepted',
    ],
    syllabicTargets: [
      { word: 'Commissioning', IPA: '/kəˈmɪʃ.ən.ɪŋ/', score: 88 },
      { word: 'Insulation', IPA: '/ˌɪn.səˈleɪ.ʃən/', score: 84 },
      { word: 'Verification', IPA: '/ˌver.ə.fəˈkeɪ.ʃən/', score: 82 },
      { word: 'Representative', IPA: '/ˌrep.rɪˈzen.t̬ə.t̬ɪv/', score: 79 },
    ],
    targetWpm: 142,
    xpReward: 88,
    coinReward: 28,
    eloReward: 19,
  },
  {
    id: 'speaking_fat_meeting',
    title: 'Factory Acceptance Test Brief',
    description:
      'Brief the factory team on acceptance criteria, punch items, and witness test expectations.',
    scenarioType: 'fat_meeting',
    discipline: 'QA/QC',
    cefrLevel: 'C1',
    difficulty: 'Advanced',
    estimatedMinutes: 14,
    promptText:
      'During the factory acceptance test, we must verify protection relay logic, interlock behavior, and alarm annunciation before closing any punch item related to control wiring.',
    expectedKeywords: [
      'factory acceptance test',
      'protection relay',
      'interlock',
      'alarm annunciation',
      'punch item',
      'control wiring',
    ],
    grammarTargets: ['we must verify', 'before closing', 'related to'],
    confidenceMarkers: ['must verify', 'witness', 'accept', 'reject', 'close'],
    syllabicTargets: [
      { word: 'Acceptance', IPA: '/əkˈsep.təns/', score: 90 },
      { word: 'Protection', IPA: '/prəˈtek.ʃən/', score: 88 },
      { word: 'Interlock', IPA: '/ˈɪn.t̬ɚ.lɑːk/', score: 86 },
      { word: 'Annunciation', IPA: '/əˌnʌn.siˈeɪ.ʃən/', score: 78 },
    ],
    targetWpm: 145,
    xpReward: 82,
    coinReward: 25,
    eloReward: 18,
  },
  {
    id: 'speaking_technical_explanation',
    title: 'Technical Explanation Drill',
    description:
      'Explain a complex engineering tradeoff using clear technical vocabulary and structured cause-effect language.',
    scenarioType: 'technical_explanation',
    discipline: 'Commissioning Engineering',
    cefrLevel: 'C2',
    difficulty: 'Advanced',
    estimatedMinutes: 16,
    promptText:
      'Static bypass operation improves UPS availability during inverter faults, but this design can expose the downstream load to upstream power quality issues if coordination is not verified.',
    expectedKeywords: [
      'static bypass',
      'UPS availability',
      'inverter faults',
      'downstream load',
      'power quality',
      'coordination',
    ],
    grammarTargets: [
      'improves availability because',
      'but this design can',
      'if coordination is not verified',
    ],
    confidenceMarkers: [
      'because',
      'therefore',
      'tradeoff',
      'introduce',
      'mitigate',
    ],
    syllabicTargets: [
      { word: 'Availability', IPA: '/availability/', score: 86 },
      { word: 'Inverter', IPA: '/inverter/', score: 88 },
      { word: 'Downstream', IPA: '/downstream/', score: 80 },
      { word: 'Coordination', IPA: '/coordination/', score: 84 },
    ],
    targetWpm: 152,
    xpReward: 95,
    coinReward: 30,
    eloReward: 22,
  },
  {
    id: 'speaking_safety_briefing',
    title: 'Safety Briefing Escalation',
    description:
      'Give a clear safety escalation briefing for live electrical diagnostic work.',
    scenarioType: 'safety_briefing',
    discipline: 'Electrical Safety',
    cefrLevel: 'B2',
    difficulty: 'Intermediate',
    estimatedMinutes: 10,
    promptText:
      'If the voltage indicator fails self-test, the inspection must stop immediately, the permit must be suspended, and the supervisor must isolate the work area.',
    expectedKeywords: [
      'voltage indicator',
      'self-test',
      'inspection',
      'stop immediately',
      'permit',
      'supervisor',
      'isolate',
    ],
    grammarTargets: ['if the', 'must stop', 'must be suspended'],
    confidenceMarkers: [
      'stop',
      'suspend',
      'isolate',
      'immediately',
      'escalate',
    ],
    syllabicTargets: [
      { word: 'Indicator', IPA: '/ˈɪn.də.keɪ.t̬ɚ/', score: 88 },
      { word: 'Inspection', IPA: '/ɪnˈspek.ʃən/', score: 90 },
      { word: 'Suspended', IPA: '/səˈspen.dɪd/', score: 84 },
      { word: 'Isolate', IPA: '/ˈaɪ.sə.leɪt/', score: 87 },
    ],
    targetWpm: 132,
    xpReward: 68,
    coinReward: 20,
    eloReward: 13,
  },
  {
    id: 'speaking_design_coordination',
    title: 'Design Coordination Resolution',
    description:
      'Resolve a design interface clash between mechanical and electrical systems.',
    scenarioType: 'design_coordination',
    discipline: 'MEP Coordination',
    cefrLevel: 'C1',
    difficulty: 'Advanced',
    estimatedMinutes: 15,
    promptText:
      'To resolve the duct and cable ladder clash, the mechanical team will split the supply duct into parallel branches while electrical maintains the required bending radius for the feeder cables.',
    expectedKeywords: [
      'duct',
      'cable ladder',
      'clash',
      'mechanical',
      'parallel branches',
      'bending radius',
      'feeder cables',
    ],
    grammarTargets: ['to resolve', 'will split', 'while electrical maintains'],
    confidenceMarkers: [
      'resolve',
      'maintains',
      'coordinate',
      'confirm',
      'required',
    ],
    syllabicTargets: [
      { word: 'Mechanical', IPA: '/məˈkæn.ɪ.kəl/', score: 89 },
      { word: 'Parallel', IPA: '/ˈper.ə.lel/', score: 83 },
      { word: 'Electrical', IPA: '/ɪˈlek.trɪ.kəl/', score: 88 },
      { word: 'Radius', IPA: '/ˈreɪ.di.əs/', score: 86 },
    ],
    targetWpm: 145,
    xpReward: 86,
    coinReward: 26,
    eloReward: 18,
  },
];

export const SPEAKING_MISSIONS: SpeakingMission[] = [
  ...STARTER_SPEAKING_MISSIONS,
  ...CORE_SPEAKING_MISSIONS,
];
