import {
  BarChart3,
  BookMarked,
  BookOpen,
  BrainCircuit,
  BriefcaseBusiness,
  Calendar,
  Headphones,
  Languages,
  Library,
  Mic2,
  Moon,
  PenTool,
  Settings,
  Shield,
  Sun,
  Target,
  Trophy,
  User,
  Wallet,
  WandSparkles,
  Home,
} from 'lucide-react';
import type { FC } from 'react';

export const COMMANDS = [
  {
    id: 'dashboard',
    label: 'Dashboard',
    href: '/dashboard',
    icon: 'Home',
    category: 'Navigate',
    keywords: ['home', 'main'],
  },
  {
    id: 'vocabulary',
    label: 'Vocabulary',
    href: '/vocabulary',
    icon: 'BookMarked',
    category: 'Skills',
    keywords: ['words', 'kelime'],
  },
  {
    id: 'grammar',
    label: 'Grammar',
    href: '/grammar',
    icon: 'Languages',
    category: 'Skills',
    keywords: ['gr kuralları'],
  },
  {
    id: 'reading',
    label: 'Reading',
    href: '/reading',
    icon: 'BookOpen',
    category: 'Skills',
    keywords: ['okuma'],
  },
  {
    id: 'writing',
    label: 'Writing',
    href: '/writing',
    icon: 'PenTool',
    category: 'Skills',
    keywords: ['yazma'],
  },
  {
    id: 'listening',
    label: 'Listening',
    href: '/listening',
    icon: 'Headphones',
    category: 'Skills',
    keywords: ['dinleme'],
  },
  {
    id: 'speaking',
    label: 'Speaking',
    href: '/speaking',
    icon: 'Mic2',
    category: 'Skills',
    keywords: ['konuşma'],
  },
  {
    id: 'curriculum-today',
    label: "Today's Curriculum",
    href: '/curriculum/today',
    icon: 'Calendar',
    category: 'Learning Hub',
    keywords: ['bugün', 'plan'],
  },
  {
    id: 'curriculum-full',
    label: 'Full Curriculum',
    href: '/curriculum/full',
    icon: 'Library',
    category: 'Learning Hub',
    keywords: ['müfredat'],
  },
  {
    id: 'curriculum-memory',
    label: 'Learning Memory',
    href: '/curriculum/memory',
    icon: 'BarChart3',
    category: 'Learning Hub',
    keywords: ['bellek'],
  },
  {
    id: 'progress-overview',
    label: 'Progress Overview',
    href: '/progress/overview',
    icon: 'Target',
    category: 'Progress',
    keywords: ['ilerleme'],
  },
  {
    id: 'progress-next-steps',
    label: 'Next Steps',
    href: '/progress/next-steps',
    icon: 'Trophy',
    category: 'Progress',
    keywords: ['sonraki', 'adım'],
  },
  {
    id: 'tools-work',
    label: 'Work Tools',
    href: '/tools/work',
    icon: 'BriefcaseBusiness',
    category: 'Tools',
    keywords: ['iş'],
  },
  {
    id: 'tools-quick',
    label: 'Quick Tools',
    href: '/tools/quick',
    icon: 'WandSparkles',
    category: 'Tools',
    keywords: ['hızlı'],
  },
  {
    id: 'tools-ai',
    label: 'AI Copilot',
    href: '/tools/ai',
    icon: 'BrainCircuit',
    category: 'Tools',
    keywords: ['asistan', 'ai'],
  },
  {
    id: 'profile-overview',
    label: 'Profile',
    href: '/profile/overview',
    icon: 'User',
    category: 'Account',
    keywords: ['hesap'],
  },
  {
    id: 'profile-preferences',
    label: 'Settings',
    href: '/profile/preferences',
    icon: 'Settings',
    category: 'Account',
    keywords: ['ayarlar'],
  },
  {
    id: 'profile-billing',
    label: 'Billing',
    href: '/billing',
    icon: 'Wallet',
    category: 'Account',
    keywords: ['fatura'],
  },
  {
    id: 'profile-security',
    label: 'Security & Data',
    href: '/profile/security',
    icon: 'Shield',
    category: 'Account',
    keywords: ['güvenlik'],
  },
  {
    id: 'admin',
    label: 'Admin Panel',
    href: '/admin',
    icon: 'Settings',
    category: 'Account',
    keywords: ['admin'],
  },
  {
    id: 'pricing',
    label: 'Pricing',
    href: '/pricing',
    icon: 'Wallet',
    category: 'Account',
    keywords: ['fiyat'],
  },
];

export const ICON_MAP: Record<string, FC<{ className?: string }>> = {
  Home,
  User,
  BookMarked,
  Languages,
  BookOpen,
  PenTool,
  Headphones,
  Mic2,
  Library,
  Calendar,
  BarChart3,
  Target,
  Trophy,
  BriefcaseBusiness,
  WandSparkles,
  BrainCircuit,
  Shield,
  Wallet,
  Settings,
  Moon,
  Sun,
};

export const CATEGORIES_ORDER = ['Navigate', 'Skills', 'Learning Hub', 'Progress', 'Tools', 'Account'];
