import {
  EmailTemplate,
  EngineeringTemplate,
  PhraseEntry,
} from './work-tools.types';

type EngineeringSeed = readonly [
  id: string,
  title: string,
  category: string,
  useCase: string,
  sampleInput: string,
  requiredAction: string,
];

const ENGINEERING_SEEDS: EngineeringSeed[] = [
  [
    'ncr-follow-up',
    'NCR Follow-up Reply',
    'QA/QC',
    'Follow up an overdue corrective action',
    'NCR-021 remains open after the agreed date.',
    'confirm the revised closure date and attach current evidence',
  ],
  [
    'ncr-closure',
    'NCR Closure Request',
    'QA/QC',
    'Request formal NCR closure',
    'All cable support spacing has been corrected.',
    'review the attached photographs and close the NCR',
  ],
  [
    'mir-rejection',
    'MIR Rejection Response',
    'QA/QC',
    'Respond to rejected material inspection',
    'Cable glands were rejected because certification was not traceable.',
    'segregate the batch and resubmit traceable certificates',
  ],
  [
    'itp-hold',
    'ITP Hold Point Confirmation',
    'QA/QC',
    'Confirm hold-point readiness',
    'Transformer pre-energization checks are complete.',
    'confirm witness attendance before the hold point is released',
  ],
  [
    'inspection-reschedule',
    'Inspection Reschedule Request',
    'QA/QC',
    'Move an inspection without losing control',
    'Ceiling access was not released for today’s inspection.',
    'reschedule the inspection for tomorrow at 10:00',
  ],
  [
    'inspection-ready',
    'Inspection Readiness Confirmation',
    'QA/QC',
    'Confirm work is ready for inspection',
    'Level 2 lighting installation is complete.',
    'confirm internal checks and request inspection',
  ],
  [
    'punch-close',
    'Punch List Closure Note',
    'QA/QC',
    'Close a punch-list item with evidence',
    'Panel labels and directory cards were corrected.',
    'verify the correction and submit dated evidence',
  ],
  [
    'snag-update',
    'Snag Rectification Update',
    'QA/QC',
    'Report snag correction progress',
    'Eight of ten generator-room snags are closed.',
    'identify the two remaining owners and dates',
  ],
  [
    'site-observation',
    'Consultant Site Observation Response',
    'QA/QC',
    'Answer a consultant site observation',
    'The consultant observed unsealed cable penetrations.',
    'complete fire stopping and request reinspection',
  ],
  [
    'corrective-confirm',
    'Corrective Action Confirmation',
    'QA/QC',
    'Confirm corrective and preventive action',
    'Incorrect tray support spacing was found in two corridors.',
    'correct affected work and extend the check to similar areas',
  ],
  [
    'tray-update',
    'Cable Tray Installation Update',
    'Electrical',
    'Report containment progress',
    'Main tray installation reached Grid D.',
    'state completed quantity, constraint and next work front',
  ],
  [
    'pulling-progress',
    'Cable Pulling Progress Note',
    'Electrical',
    'Report cable-pulling status',
    'Four of six feeders were pulled today.',
    'record drum references and tomorrow’s sequence',
  ],
  [
    'termination-complete',
    'Cable Termination Completion',
    'Electrical',
    'Confirm termination readiness',
    'UPS outgoing feeders are terminated.',
    'confirm torque, labels and test records',
  ],
  [
    'lv-inspection',
    'LV Panel Inspection Response',
    'Electrical',
    'Close an LV panel inspection comment',
    'Two gland plates require additional sealing.',
    'complete sealing and offer the panel for reinspection',
  ],
  [
    'mv-delay',
    'MV Panel Delivery Delay Explanation',
    'Electrical',
    'Explain a critical equipment delay',
    'MV panels are seven days late at the factory.',
    'state programme impact and recovery action',
  ],
  [
    'transformer-ready',
    'Transformer Energization Readiness',
    'Electrical',
    'Confirm energization prerequisites',
    'Transformer T2 is mechanically complete.',
    'list protection, earthing and permit prerequisites',
  ],
  [
    'earthing-note',
    'Earthing Test Report Note',
    'Electrical',
    'Summarize an earthing test',
    'Earth resistance measured 0.62 ohm.',
    'record acceptance criteria and instrument details',
  ],
  [
    'lighting-request',
    'Lighting Inspection Request',
    'Electrical',
    'Request lighting inspection',
    'Ward lighting circuits are installed and tested.',
    'identify area, drawing and inspection time',
  ],
  [
    'fire-clarification',
    'Fire Alarm Cause-and-Effect Clarification',
    'Electrical',
    'Clarify an interface response',
    'The matrix does not define the AHU shutdown delay.',
    'request the confirmed sequence and responsible reviewer',
  ],
  [
    'generator-summary',
    'Generator Load Test Summary',
    'Electrical',
    'Summarize generator testing',
    'The generator passed 25, 50, 75 and 100 percent load steps.',
    'record performance, exception and follow-up',
  ],
  [
    'clearance-request',
    'Mechanical Clearance Request',
    'MEP Coordination',
    'Protect equipment maintenance access',
    'The duct route reduces panel clearance.',
    'request a coordinated route revision',
  ],
  [
    'ceiling-coordination',
    'Ceiling Closure Coordination',
    'MEP Coordination',
    'Control services before ceiling closure',
    'Above-ceiling inspections remain open in Zone 4.',
    'hold closure until listed inspections are released',
  ],
  [
    'shaft-access',
    'Shaft Access Coordination',
    'MEP Coordination',
    'Coordinate shared shaft access',
    'Electrical riser work conflicts with pipe insulation.',
    'agree access windows and responsible supervisors',
  ],
  [
    'clash-resolution',
    'Clash Resolution Note',
    'MEP Coordination',
    'Record a coordinated clash solution',
    'Cable ladder clashes with a chilled-water branch.',
    'document the agreed reroute and drawing revision',
  ],
  [
    'mep-action',
    'MEP Coordination Meeting Action',
    'MEP Coordination',
    'Create an accountable coordination action',
    'Builder’s work opening location is unresolved.',
    'assign owner, date and required drawing',
  ],
  [
    'hvac-power',
    'HVAC Power Supply Confirmation',
    'MEP Coordination',
    'Confirm an electrical-mechanical interface',
    'AHU-12 requires final load confirmation.',
    'confirm load, isolator and cable schedule reference',
  ],
  [
    'damper-interface',
    'Fire Damper Integration Clarification',
    'MEP Coordination',
    'Clarify fire damper controls',
    'Fire alarm and BMS responsibilities differ.',
    'confirm command, feedback and test responsibility',
  ],
  [
    'bms-follow',
    'BMS Interface Follow-up',
    'MEP Coordination',
    'Follow up controls integration',
    'Three panel points are missing from the BMS list.',
    'update point list and confirm testing date',
  ],
  [
    'pump-ready',
    'Pump Room Readiness Note',
    'MEP Coordination',
    'Confirm pump-room testing readiness',
    'Power, controls and pipe flushing are nearly complete.',
    'list remaining prerequisites and owners',
  ],
  [
    'tc-coordinate',
    'Testing and Commissioning Coordination',
    'MEP Coordination',
    'Coordinate integrated testing',
    'The integrated test requires five disciplines.',
    'confirm prerequisites, attendance and sequence',
  ],
  [
    'delivery-follow',
    'Material Delivery Follow-up',
    'Procurement',
    'Obtain a firm delivery commitment',
    'Approved luminaires have no confirmed dispatch date.',
    'provide production status and committed delivery',
  ],
  [
    'long-lead',
    'Long Lead Item Update',
    'Procurement',
    'Report long-lead equipment risk',
    'Transformer manufacturing is on the critical path.',
    'state milestone status and escalation required',
  ],
  [
    'alternative-material',
    'Alternative Material Proposal',
    'Procurement',
    'Propose a compliant alternative',
    'Specified cable tray is unavailable locally.',
    'compare compliance, lead time and cost impact',
  ],
  [
    'vendor-doc',
    'Vendor Document Follow-up',
    'Procurement',
    'Request overdue vendor documents',
    'Generator shop drawings remain outstanding.',
    'submit the document register and recovery dates',
  ],
  [
    'certificate-request',
    'Missing Certificate Request',
    'Procurement',
    'Request traceable certification',
    'Delivered fire cable has no batch certificate.',
    'link certificates to drum and delivery references',
  ],
  [
    'delivery-escalation',
    'Delivery Delay Escalation',
    'Procurement',
    'Escalate a delivery risk',
    'ATS delivery missed the second confirmed date.',
    'request management recovery plan and daily updates',
  ],
  [
    'fat-invite',
    'FAT Invitation Note',
    'Procurement',
    'Invite stakeholders to a FAT',
    'LV panel FAT is planned for 18 August.',
    'confirm agenda, location and witness list',
  ],
  [
    'factory-doc',
    'Factory Test Document Request',
    'Procurement',
    'Request FAT records before release',
    'Factory test sheets are incomplete.',
    'submit signed records and exception list',
  ],
  [
    'spares-follow',
    'Spare Parts List Follow-up',
    'Procurement',
    'Close spare-parts documentation',
    'The O&M package has no priced spares list.',
    'provide recommended quantities and part numbers',
  ],
  [
    'warranty-request',
    'Warranty Document Request',
    'Procurement',
    'Request warranty confirmation',
    'The handover dossier lacks warranty letters.',
    'provide start date, duration and exclusions',
  ],
  [
    'weekly-summary',
    'Weekly Progress Summary',
    'Project Management',
    'Summarize weekly delivery',
    'Electrical works advanced but panel delivery remains critical.',
    'report progress, blockers and next-week priorities',
  ],
  [
    'mitigation-plan',
    'Delay Mitigation Plan',
    'Project Management',
    'Present a measurable recovery plan',
    'Containment is five days behind baseline.',
    'state resequencing, resources and recovered days',
  ],
  [
    'manpower-note',
    'Manpower Increase Note',
    'Project Management',
    'Request targeted additional resources',
    'Cable termination output is below look-ahead demand.',
    'justify trade numbers, duration and work fronts',
  ],
  [
    'critical-impact',
    'Critical Path Impact Explanation',
    'Project Management',
    'Explain critical-path movement',
    'Switchgear approval moved the energization milestone.',
    'show dependency, impact and decision required',
  ],
  [
    'lookahead-clarify',
    'Look-ahead Plan Clarification',
    'Project Management',
    'Clarify a short-term programme',
    'Inspection dates are missing from the three-week plan.',
    'add hold points, owners and access constraints',
  ],
  [
    'client-response',
    'Client Response Draft',
    'Project Management',
    'Give a concise client update',
    'The client requests assurance on the handover date.',
    'state facts, risks and controlled next action',
  ],
  [
    'consultant-summary',
    'Consultant Meeting Summary',
    'Project Management',
    'Summarize decisions after a consultant meeting',
    'Four technical actions were agreed.',
    'record owners, dates and evidence required',
  ],
  [
    'subcontract-warning',
    'Subcontractor Warning Note',
    'Project Management',
    'Warn about repeated underperformance',
    'Daily targets were missed for one week.',
    'request recovery plan without aggressive language',
  ],
  [
    'instruction-confirm',
    'Site Instruction Confirmation',
    'Project Management',
    'Confirm receipt and interpretation of an instruction',
    'The route revision was instructed verbally.',
    'record scope, cost/time reservation and drawing need',
  ],
  [
    'handover-ready',
    'Handover Readiness Update',
    'Project Management',
    'Report handover readiness honestly',
    'Testing is complete but O&M documents remain open.',
    'separate completed systems from outstanding documents',
  ],
];

export const EXPANDED_ENGINEERING_TEMPLATES: EngineeringTemplate[] =
  ENGINEERING_SEEDS.map(
    ([id, title, category, useCase, sampleInput, requiredAction]) => ({
      id: `expanded-${id}`,
      title,
      category,
      useCase,
      context: `${useCase} in a controlled ${category} workflow with a clear owner, date and evidence requirement.`,
      sampleInput,
      professionalOutput: `${sampleInput} Please ${requiredAction}. Include the relevant drawing, inspection or programme reference and confirm the accountable owner and completion date.`,
      turkishExplanation: `Bu şablon, ${title.toLocaleLowerCase('tr-TR')} için durumu, gerekli aksiyonu, sorumluyu ve kapanış kanıtını açık biçimde kaydeder.`,
      tone: 'Professional and accountable',
      tags: [category.toLowerCase(), 'site communication', 'action tracking'],
    })
  );

type EmailSeed = readonly [
  id: string,
  title: string,
  category: string,
  subject: string,
  issue: string,
  request: string,
];

const EMAIL_SEEDS: EmailSeed[] = [
  [
    'delay-notice',
    'Formal Delay Notification',
    'Delay',
    'Notice of programme delay',
    'The approved equipment delivery has moved by seven days.',
    'confirm the revised date and recovery plan',
  ],
  [
    'delay-mitigation',
    'Delay Mitigation Plan',
    'Delay',
    'Mitigation plan for delayed containment works',
    'Containment progress is below the approved look-ahead.',
    'review the attached resequencing and resource plan',
  ],
  [
    'delay-material',
    'Material Delivery Delay',
    'Delay',
    'Material delivery delay and site impact',
    'The fire-rated cable batch has not been dispatched.',
    'provide a firm dispatch date and partial-delivery option',
  ],
  [
    'delay-access',
    'Access Issue Delay',
    'Delay',
    'Access restriction affecting planned works',
    'The electrical room remains unavailable to the installation team.',
    'release access or confirm an alternative work window',
  ],
  [
    'delay-design',
    'Design Clarification Delay',
    'Delay',
    'Design clarification affecting progress',
    'The unresolved routing detail prevents installation in Corridor 3.',
    'issue the confirmed detail by the stated decision date',
  ],
  [
    'inspection-request-2',
    'Detailed Inspection Request',
    'Inspection',
    'Inspection request - completed installation',
    'The identified work is complete and internally checked.',
    'confirm attendance for the proposed inspection time',
  ],
  [
    'inspection-reschedule-2',
    'Inspection Reschedule',
    'Inspection',
    'Request to reschedule inspection',
    'The required access platform will be available tomorrow.',
    'move the inspection to the proposed replacement slot',
  ],
  [
    'inspection-cancel',
    'Inspection Cancellation',
    'Inspection',
    'Cancellation of inspection request',
    'A prerequisite test record is not yet complete.',
    'cancel today’s inspection and await a revised request',
  ],
  [
    'inspection-ready-2',
    'Inspection Readiness',
    'Inspection',
    'Confirmation of inspection readiness',
    'All checklist items and supporting records are complete.',
    'proceed with inspection at the confirmed location',
  ],
  [
    'inspection-reject',
    'Inspection Rejection Response',
    'Inspection',
    'Response to rejected inspection',
    'The identified labels and seals have been corrected.',
    'review the evidence and arrange reinspection',
  ],
  [
    'approval-standard',
    'Technical Approval Request',
    'Approval',
    'Approval request for coordinated proposal',
    'The revised proposal resolves the recorded interface issue.',
    'approve the attached revision for construction',
  ],
  [
    'approval-revised',
    'Revised Submittal Approval',
    'Approval',
    'Revised submittal - approval requested',
    'All review comments are addressed in the response sheet.',
    'confirm approval of the revised submission',
  ],
  [
    'approval-urgent',
    'Urgent Approval Request',
    'Approval',
    'Urgent approval required to protect delivery',
    'Manufacturing release depends on this approval.',
    'complete review by the stated decision deadline',
  ],
  [
    'approval-follow',
    'Approval Follow-up',
    'Approval',
    'Follow-up on outstanding approval',
    'The review period has passed and procurement is now affected.',
    'confirm current status and final response date',
  ],
  [
    'approval-conditional',
    'Conditional Approval Response',
    'Approval',
    'Response to conditional approval',
    'The conditions have been incorporated into the latest revision.',
    'confirm whether construction may proceed',
  ],
  [
    'proc-material',
    'Material Status Follow-up',
    'Procurement',
    'Material manufacturing and delivery status',
    'The latest supplier update does not include a dispatch date.',
    'provide milestones, inspection and delivery dates',
  ],
  [
    'proc-document',
    'Missing Vendor Document',
    'Procurement',
    'Outstanding vendor document request',
    'The technical document register remains incomplete.',
    'submit the listed drawings and calculations',
  ],
  [
    'proc-certificate',
    'Certificate Request',
    'Procurement',
    'Traceable material certificate required',
    'The delivered batch cannot be matched to its certificate.',
    'provide batch-linked compliance evidence',
  ],
  [
    'proc-fat',
    'FAT Arrangement',
    'Procurement',
    'Factory acceptance test arrangement',
    'The equipment is approaching factory test readiness.',
    'confirm date, agenda and witness requirements',
  ],
  [
    'proc-escalate',
    'Delivery Escalation',
    'Procurement',
    'Escalation of missed delivery commitment',
    'The second committed delivery date was missed.',
    'submit a management-approved recovery plan',
  ],
  [
    'consultant-reply',
    'Consultant Comment Reply',
    'Consultant / Client',
    'Response to consultant technical comment',
    'The requested calculation and marked-up detail are attached.',
    'review the response and close the comment',
  ],
  [
    'consultant-clarify-2',
    'Consultant Clarification Request',
    'Consultant / Client',
    'Clarification required for conflicting requirement',
    'The specification and drawing show different interface locations.',
    'confirm the governing requirement',
  ],
  [
    'consultant-resubmit',
    'Document Resubmission',
    'Consultant / Client',
    'Resubmission of revised technical document',
    'The document was revised against every recorded comment.',
    'review Revision 03 and update the status',
  ],
  [
    'client-update',
    'Client Progress Update',
    'Consultant / Client',
    'Client update on critical works',
    'Progress remains controlled but one delivery risk is open.',
    'note the mitigation and upcoming decision',
  ],
  [
    'observation-response',
    'Site Observation Response',
    'Consultant / Client',
    'Response to consultant site observation',
    'The observed deficiency has been isolated and corrected.',
    'review the evidence and confirm closure',
  ],
  [
    'contract-instruction',
    'Contractor Work Instruction',
    'Contractor / Subcontractor',
    'Instruction to correct installation',
    'The installed support arrangement differs from the approved detail.',
    'correct the affected area before continuing',
  ],
  [
    'contract-warning',
    'Subcontractor Warning Letter',
    'Contractor / Subcontractor',
    'Warning regarding repeated underperformance',
    'Daily production targets have been missed repeatedly.',
    'submit an immediate recovery plan',
  ],
  [
    'contract-manpower',
    'Manpower Increase Request',
    'Contractor / Subcontractor',
    'Request for additional skilled manpower',
    'Current resources cannot achieve the look-ahead sequence.',
    'mobilize the stated trade resources',
  ],
  [
    'contract-corrective',
    'Corrective Action Request',
    'Contractor / Subcontractor',
    'Corrective action required',
    'The same quality issue has occurred in multiple areas.',
    'identify root cause and preventive control',
  ],
  [
    'contract-accelerate',
    'Progress Acceleration Request',
    'Contractor / Subcontractor',
    'Acceleration required for critical activity',
    'The activity now threatens the next milestone.',
    'confirm shift, resource and supervision changes',
  ],
  [
    'commission-result',
    'Test Result Submission',
    'Commissioning / Handover',
    'Submission of signed test results',
    'The functional test was completed without open defects.',
    'review the attached record and accept the result',
  ],
  [
    'commission-ready',
    'Commissioning Readiness',
    'Commissioning / Handover',
    'Readiness for commissioning activity',
    'All prerequisites except one interface sign-off are complete.',
    'close the interface action before the test window',
  ],
  [
    'commission-punch',
    'Punch List Closure',
    'Commissioning / Handover',
    'Commissioning punch-list closure',
    'The listed defects were corrected and retested.',
    'accept the evidence and close the items',
  ],
  [
    'commission-om',
    'O&M Manual Follow-up',
    'Commissioning / Handover',
    'Outstanding O&M manual documents',
    'The final manuals lack approved settings and certificates.',
    'submit the complete indexed revision',
  ],
  [
    'commission-handover',
    'Handover Document Submission',
    'Commissioning / Handover',
    'Submission of handover dossier',
    'As-builts, tests, manuals and training records are compiled.',
    'review the dossier and identify any final gap',
  ],
  [
    'meeting-invite-2',
    'Technical Coordination Invitation',
    'Meeting',
    'Coordination meeting - open interfaces',
    'Several cross-discipline interfaces require decisions.',
    'confirm attendance and prepare the listed inputs',
  ],
  [
    'meeting-minutes-2',
    'Meeting Minutes Distribution',
    'Meeting',
    'Minutes and action register',
    'The agreed actions and owners are recorded.',
    'review and raise corrections within two working days',
  ],
  [
    'safety-warning',
    'Safety Non-compliance Warning',
    'HSE',
    'Immediate correction of safety non-compliance',
    'An access route was obstructed by temporary services.',
    'remove the hazard and confirm preventive action',
  ],
  [
    'handover-training',
    'Operator Training Arrangement',
    'Commissioning / Handover',
    'Operator training schedule',
    'System training is required before handover.',
    'confirm attendees, trainer and proposed dates',
  ],
  [
    'project-decision',
    'Decision Required from Client',
    'Consultant / Client',
    'Client decision required to protect milestone',
    'Two compliant options remain open with different programme impacts.',
    'select the preferred option by the decision date',
  ],
];

export const EXPANDED_EMAIL_TEMPLATES: EmailTemplate[] = EMAIL_SEEDS.map(
  ([id, title, category, subject, issue, request]) => ({
    id: `expanded-email-${id}`,
    title,
    category,
    subject,
    shortVersion: `Subject: ${subject}\n\nDear Team,\n\n${issue} Please ${request}.\n\nRegards,`,
    professionalVersion: `Subject: ${subject}\n\nDear Team,\n\n${issue} Please ${request}, including the responsible person and committed date. This response is required to maintain the coordinated project sequence.\n\nKind regards,`,
    politeVersion: `Subject: ${subject}\n\nDear Team,\n\nCould you please ${request}? ${issue} Your timely support will help us maintain the agreed project sequence.\n\nKind regards,`,
    technicalVersion: `Subject: ${subject}\n\nDear Team,\n\n${issue} Please ${request} with the applicable drawing, specification, inspection or programme reference. Identify any technical constraint, accountable owner and close-out date.\n\nKind regards,`,
    turkishExplanation: `Bu e-posta, ${title.toLocaleLowerCase('tr-TR')} için teknik durumu ve beklenen cevabı profesyonel biçimde açıklar.`,
    tags: [
      category.toLowerCase(),
      'engineering email',
      'project communication',
    ],
  })
);

const PHRASE_TOPICS = [
  ['Consultant', 'the revised technical submission', 'revize teknik sunum'],
  [
    'Contractor',
    'the agreed corrective action',
    'mutabık kalınan düzeltici faaliyet',
  ],
  ['Client', 'the milestone decision', 'kilometre taşı kararı'],
  [
    'Subcontractor',
    'the committed completion date',
    'taahhüt edilen bitiş tarihi',
  ],
  ['QA/QC', 'the inspection close-out evidence', 'kontrol kapanış kanıtı'],
  ['HSE', 'the immediate safety control', 'acil güvenlik kontrolü'],
  [
    'Procurement',
    'the confirmed delivery programme',
    'teyit edilmiş teslimat programı',
  ],
  [
    'Commissioning',
    'the outstanding test prerequisite',
    'eksik test ön koşulu',
  ],
  ['Delay', 'the recovery action', 'telafi aksiyonu'],
  ['Approval', 'the required technical approval', 'gerekli teknik onay'],
  ['Rejection', 'the non-compliant proposal', 'uygun olmayan teklif'],
  [
    'Clarification',
    'the conflicting interface requirement',
    'çelişen arayüz gereksinimi',
  ],
  ['Follow-up', 'the overdue action', 'gecikmiş aksiyon'],
  ['Meeting', 'the agreed meeting decision', 'mutabık kalınan toplantı kararı'],
  ['Handover', 'the remaining handover item', 'kalan teslim maddesi'],
  [
    'Warning',
    'the repeated site non-compliance',
    'tekrarlanan saha uygunsuzluğu',
  ],
  ['Progress', 'the current installation status', 'mevcut montaj durumu'],
  [
    'Coordination',
    'the unresolved coordination interface',
    'çözülmemiş koordinasyon arayüzü',
  ],
  ['Design', 'the latest coordinated design', 'son koordineli tasarım'],
  ['Testing', 'the signed test record', 'imzalı test kaydı'],
] as const;

const PHRASE_PATTERNS = [
  {
    phrase: (topic: string) =>
      `Please confirm ${topic} before we proceed with the next activity.`,
    turkish: (topic: string) =>
      `Bir sonraki faaliyete geçmeden önce ${topic} teyit edin.`,
    use: 'Requesting a controlled confirmation',
    example: (topic: string) =>
      `Please confirm ${topic} by 14:00 so the site team can proceed safely.`,
  },
  {
    phrase: (topic: string) =>
      `The current status of ${topic} needs to be recorded in today’s action log.`,
    turkish: (topic: string) =>
      `${topic} için mevcut durum bugünkü aksiyon kaydına işlenmelidir.`,
    use: 'Keeping an auditable action record',
    example: (topic: string) =>
      `The current status of ${topic} needs to be recorded with an owner and due date.`,
  },
  {
    phrase: (topic: string) =>
      `We can close this point once ${topic} is formally accepted.`,
    turkish: (topic: string) =>
      `${topic} resmen kabul edildiğinde bu maddeyi kapatabiliriz.`,
    use: 'Explaining a closure condition',
    example: (topic: string) =>
      `We can close this point once ${topic} is formally accepted by the consultant.`,
  },
  {
    phrase: (topic: string) =>
      `Could you identify the owner and deadline for ${topic}?`,
    turkish: (topic: string) =>
      `${topic} için sorumluyu ve son tarihi belirtebilir misiniz?`,
    use: 'Turning discussion into accountability',
    example: (topic: string) =>
      `Could you identify the owner and deadline for ${topic} before we close the meeting?`,
  },
  {
    phrase: (topic: string) =>
      `Without ${topic}, the planned sequence remains at risk.`,
    turkish: (topic: string) =>
      `${topic} olmadan planlanan iş sırası risk altında kalır.`,
    use: 'Explaining programme impact without blame',
    example: (topic: string) =>
      `Without ${topic}, the planned sequence remains at risk and resequencing may be required.`,
  },
];

export const EXPANDED_PHRASE_LIBRARY: PhraseEntry[] = PHRASE_TOPICS.flatMap(
  ([category, englishTopic, turkishTopic], categoryIndex) =>
    PHRASE_PATTERNS.map((pattern, patternIndex) => ({
      id: `expanded-phrase-${categoryIndex + 1}-${patternIndex + 1}`,
      category,
      phrase: pattern.phrase(englishTopic),
      turkishMeaning: pattern.turkish(turkishTopic),
      usageContext: pattern.use,
      example: pattern.example(englishTopic),
      tone: patternIndex === 4 ? 'Firm and factual' : 'Professional and polite',
      tags: [
        category.toLowerCase(),
        'site meeting',
        'engineering communication',
      ],
    }))
);
