export type EngineeringSeed = readonly [
  id: string,
  title: string,
  category: string,
  useCase: string,
  sampleInput: string,
  requiredAction: string,
];

export const SITE_SEEDS: EngineeringSeed[] = [
  [
    'ncr-follow-up',
    'NCR Follow-up Reply',
    'QA/QC',
    'Follow up an overdue corrective action',
    'NCR-021 remains open after the agreed date.',
    'confirm the revised closure date and attach current evidence',
  ],
  [
    'ncr-closure',
    'NCR Closure Request',
    'QA/QC',
    'Request formal NCR closure',
    'All cable support spacing has been corrected.',
    'review the attached photographs and close the NCR',
  ],
  [
    'mir-rejection',
    'MIR Rejection Response',
    'QA/QC',
    'Respond to rejected material inspection',
    'Cable glands were rejected because certification was not traceable.',
    'segregate the batch and resubmit traceable certificates',
  ],
  [
    'itp-hold',
    'ITP Hold Point Confirmation',
    'QA/QC',
    'Confirm hold-point readiness',
    'Transformer pre-energization checks are complete.',
    'confirm witness attendance before the hold point is released',
  ],
  [
    'inspection-reschedule',
    'Inspection Reschedule Request',
    'QA/QC',
    'Move an inspection without losing control',
    "Ceiling access was not released for today's inspection.",
    'reschedule the inspection for tomorrow at 10:00',
  ],
  [
    'inspection-ready',
    'Inspection Readiness Confirmation',
    'QA/QC',
    'Confirm work is ready for inspection',
    'Level 2 lighting installation is complete.',
    'confirm internal checks and request inspection',
  ],
  [
    'punch-close',
    'Punch List Closure Note',
    'QA/QC',
    'Close a punch-list item with evidence',
    'Panel labels and directory cards were corrected.',
    'verify the correction and submit dated evidence',
  ],
  [
    'snag-update',
    'Snag Rectification Update',
    'QA/QC',
    'Report snag correction progress',
    'Eight of ten generator-room snags are closed.',
    'identify the two remaining owners and dates',
  ],
  [
    'site-observation',
    'Consultant Site Observation Response',
    'QA/QC',
    'Answer a consultant site observation',
    'The consultant observed unsealed cable penetrations.',
    'complete fire stopping and request reinspection',
  ],
  [
    'corrective-confirm',
    'Corrective Action Confirmation',
    'QA/QC',
    'Confirm corrective and preventive action',
    'Incorrect tray support spacing was found in two corridors.',
    'correct affected work and extend the check to similar areas',
  ],
  [
    'tray-update',
    'Cable Tray Installation Update',
    'Electrical',
    'Report containment progress',
    'Main tray installation reached Grid D.',
    'state completed quantity, constraint and next work front',
  ],
  [
    'pulling-progress',
    'Cable Pulling Progress Note',
    'Electrical',
    'Report cable-pulling status',
    'Four of six feeders were pulled today.',
    "record drum references and tomorrow's sequence",
  ],
  [
    'termination-complete',
    'Cable Termination Completion',
    'Electrical',
    'Confirm termination readiness',
    'UPS outgoing feeders are terminated.',
    'confirm torque, labels and test records',
  ],
  [
    'lv-inspection',
    'LV Panel Inspection Response',
    'Electrical',
    'Close an LV panel inspection comment',
    'Two gland plates require additional sealing.',
    'complete sealing and offer the panel for reinspection',
  ],
  [
    'mv-delay',
    'MV Panel Delivery Delay Explanation',
    'Electrical',
    'Explain a critical equipment delay',
    'MV panels are seven days late at the factory.',
    'state programme impact and recovery action',
  ],
  [
    'transformer-ready',
    'Transformer Energization Readiness',
    'Electrical',
    'Confirm energization prerequisites',
    'Transformer T2 is mechanically complete.',
    'list protection, earthing and permit prerequisites',
  ],
  [
    'earthing-note',
    'Earthing Test Report Note',
    'Electrical',
    'Summarize an earthing test',
    'Earth resistance measured 0.62 ohm.',
    'record acceptance criteria and instrument details',
  ],
  [
    'lighting-request',
    'Lighting Inspection Request',
    'Electrical',
    'Request lighting inspection',
    'Ward lighting circuits are installed and tested.',
    'identify area, drawing and inspection time',
  ],
  [
    'fire-clarification',
    'Fire Alarm Cause-and-Effect Clarification',
    'Electrical',
    'Clarify an interface response',
    'The matrix does not define the AHU shutdown delay.',
    'request the confirmed sequence and responsible reviewer',
  ],
  [
    'generator-summary',
    'Generator Load Test Summary',
    'Electrical',
    'Summarize generator testing',
    'The generator passed 25, 50, 75 and 100 percent load steps.',
    'record performance, exception and follow-up',
  ],
];
