import { EngineeringSeed } from './work-tools.engineering.site-seeds';

export const MANAGEMENT_SEEDS: EngineeringSeed[] = [
  [
    'delivery-follow',
    'Material Delivery Follow-up',
    'Procurement',
    'Obtain a firm delivery commitment',
    'Approved luminaires have no confirmed dispatch date.',
    'provide production status and committed delivery',
  ],
  [
    'long-lead',
    'Long Lead Item Update',
    'Procurement',
    'Report long-lead equipment risk',
    'Transformer manufacturing is on the critical path.',
    'state milestone status and escalation required',
  ],
  [
    'alternative-material',
    'Alternative Material Proposal',
    'Procurement',
    'Propose a compliant alternative',
    'Specified cable tray is unavailable locally.',
    'compare compliance, lead time and cost impact',
  ],
  [
    'vendor-doc',
    'Vendor Document Follow-up',
    'Procurement',
    'Request overdue vendor documents',
    'Generator shop drawings remain outstanding.',
    'submit the document register and recovery dates',
  ],
  [
    'certificate-request',
    'Missing Certificate Request',
    'Procurement',
    'Request traceable certification',
    'Delivered fire cable has no batch certificate.',
    'link certificates to drum and delivery references',
  ],
  [
    'delivery-escalation',
    'Delivery Delay Escalation',
    'Procurement',
    'Escalate a delivery risk',
    'ATS delivery missed the second confirmed date.',
    'request management recovery plan and daily updates',
  ],
  [
    'fat-invite',
    'FAT Invitation Note',
    'Procurement',
    'Invite stakeholders to a FAT',
    'LV panel FAT is planned for 18 August.',
    'confirm agenda, location and witness list',
  ],
  [
    'factory-doc',
    'Factory Test Document Request',
    'Procurement',
    'Request FAT records before release',
    'Factory test sheets are incomplete.',
    'submit signed records and exception list',
  ],
  [
    'spares-follow',
    'Spare Parts List Follow-up',
    'Procurement',
    'Close spare-parts documentation',
    'The O&M package has no priced spares list.',
    'provide recommended quantities and part numbers',
  ],
  [
    'warranty-request',
    'Warranty Document Request',
    'Procurement',
    'Request warranty confirmation',
    'The handover dossier lacks warranty letters.',
    'provide start date, duration and exclusions',
  ],
  [
    'weekly-summary',
    'Weekly Progress Summary',
    'Project Management',
    'Summarize weekly delivery',
    'Electrical works advanced but panel delivery remains critical.',
    'report progress, blockers and next-week priorities',
  ],
  [
    'mitigation-plan',
    'Delay Mitigation Plan',
    'Project Management',
    'Present a measurable recovery plan',
    'Containment is five days behind baseline.',
    'state resequencing, resources and recovered days',
  ],
  [
    'manpower-note',
    'Manpower Increase Note',
    'Project Management',
    'Request targeted additional resources',
    'Cable termination output is below look-ahead demand.',
    'justify trade numbers, duration and work fronts',
  ],
  [
    'critical-impact',
    'Critical Path Impact Explanation',
    'Project Management',
    'Explain critical-path movement',
    'Switchgear approval moved the energization milestone.',
    'show dependency, impact and decision required',
  ],
  [
    'lookahead-clarify',
    'Look-ahead Plan Clarification',
    'Project Management',
    'Clarify a short-term programme',
    'Inspection dates are missing from the three-week plan.',
    'add hold points, owners and access constraints',
  ],
  [
    'client-response',
    'Client Response Draft',
    'Project Management',
    'Give a concise client update',
    'The client requests assurance on the handover date.',
    'state facts, risks and controlled next action',
  ],
  [
    'consultant-summary',
    'Consultant Meeting Summary',
    'Project Management',
    'Summarize decisions after a consultant meeting',
    'Four technical actions were agreed.',
    'record owners, dates and evidence required',
  ],
  [
    'subcontract-warning',
    'Subcontractor Warning Note',
    'Project Management',
    'Warn about repeated underperformance',
    'Daily targets were missed for one week.',
    'request recovery plan without aggressive language',
  ],
  [
    'instruction-confirm',
    'Site Instruction Confirmation',
    'Project Management',
    'Confirm receipt and interpretation of an instruction',
    'The route revision was instructed verbally.',
    'record scope, cost/time reservation and drawing need',
  ],
  [
    'handover-ready',
    'Handover Readiness Update',
    'Project Management',
    'Report handover readiness honestly',
    'Testing is complete but O&M documents remain open.',
    'separate completed systems from outstanding documents',
  ],
];
