import { EngineeringSeed } from './work-tools.engineering.site-seeds';

export const PROCUREMENT_SEEDS: EngineeringSeed[] = [
  [
    'delivery-follow',
    'Material Delivery Follow-up',
    'Procurement',
    'Obtain a firm delivery commitment',
    'Approved luminaires have no confirmed dispatch date.',
    'provide production status and committed delivery',
  ],
  [
    'long-lead',
    'Long Lead Item Update',
    'Procurement',
    'Report long-lead equipment risk',
    'Transformer manufacturing is on the critical path.',
    'state milestone status and escalation required',
  ],
  [
    'alternative-material',
    'Alternative Material Proposal',
    'Procurement',
    'Propose a compliant alternative',
    'Specified cable tray is unavailable locally.',
    'compare compliance, lead time and cost impact',
  ],
  [
    'vendor-doc',
    'Vendor Document Follow-up',
    'Procurement',
    'Request overdue vendor documents',
    'Generator shop drawings remain outstanding.',
    'submit the document register and recovery dates',
  ],
  [
    'certificate-request',
    'Missing Certificate Request',
    'Procurement',
    'Request traceable certification',
    'Delivered fire cable has no batch certificate.',
    'link certificates to drum and delivery references',
  ],
  [
    'delivery-escalation',
    'Delivery Delay Escalation',
    'Procurement',
    'Escalate a delivery risk',
    'ATS delivery missed the second confirmed date.',
    'request management recovery plan and daily updates',
  ],
  [
    'fat-invite',
    'FAT Invitation Note',
    'Procurement',
    'Invite stakeholders to a FAT',
    'LV panel FAT is planned for 18 August.',
    'confirm agenda, location and witness list',
  ],
  [
    'factory-doc',
    'Factory Test Document Request',
    'Procurement',
    'Request FAT records before release',
    'Factory test sheets are incomplete.',
    'submit signed records and exception list',
  ],
  [
    'spares-follow',
    'Spare Parts List Follow-up',
    'Procurement',
    'Close spare-parts documentation',
    'The O&M package has no priced spares list.',
    'provide recommended quantities and part numbers',
  ],
  [
    'warranty-request',
    'Warranty Document Request',
    'Procurement',
    'Request warranty confirmation',
    'The handover dossier lacks warranty letters.',
    'provide start date, duration and exclusions',
  ],
];
