import { EngineeringSeed } from './work-tools.engineering.site-seeds';

export const MEP_SEEDS: EngineeringSeed[] = [
  [
    'clearance-request',
    'Mechanical Clearance Request',
    'MEP Coordination',
    'Protect equipment maintenance access',
    'The duct route reduces panel clearance.',
    'request a coordinated route revision',
  ],
  [
    'ceiling-coordination',
    'Ceiling Closure Coordination',
    'MEP Coordination',
    'Control services before ceiling closure',
    'Above-ceiling inspections remain open in Zone 4.',
    'hold closure until listed inspections are released',
  ],
  [
    'shaft-access',
    'Shaft Access Coordination',
    'MEP Coordination',
    'Coordinate shared shaft access',
    'Electrical riser work conflicts with pipe insulation.',
    'agree access windows and responsible supervisors',
  ],
  [
    'clash-resolution',
    'Clash Resolution Note',
    'MEP Coordination',
    'Record a coordinated clash solution',
    'Cable ladder clashes with a chilled-water branch.',
    'document the agreed reroute and drawing revision',
  ],
  [
    'mep-action',
    'MEP Coordination Meeting Action',
    'MEP Coordination',
    'Create an accountable coordination action',
    'Builder\'s work opening location is unresolved.',
    'assign owner, date and required drawing',
  ],
  [
    'hvac-power',
    'HVAC Power Supply Confirmation',
    'MEP Coordination',
    'Confirm an electrical-mechanical interface',
    'AHU-12 requires final load confirmation.',
    'confirm load, isolator and cable schedule reference',
  ],
  [
    'damper-interface',
    'Fire Damper Integration Clarification',
    'MEP Coordination',
    'Clarify fire damper controls',
    'Fire alarm and BMS responsibilities differ.',
    'confirm command, feedback and test responsibility',
  ],
  [
    'bms-follow',
    'BMS Interface Follow-up',
    'MEP Coordination',
    'Follow up controls integration',
    'Three panel points are missing from the BMS list.',
    'update point list and confirm testing date',
  ],
  [
    'pump-ready',
    'Pump Room Readiness Note',
    'MEP Coordination',
    'Confirm pump-room testing readiness',
    'Power, controls and pipe flushing are nearly complete.',
    'list remaining prerequisites and owners',
  ],
  [
    'tc-coordinate',
    'Testing and Commissioning Coordination',
    'MEP Coordination',
    'Coordinate integrated testing',
    'The integrated test requires five disciplines.',
    'confirm prerequisites, attendance and sequence',
  ],
];
