import { EmailTemplate } from './work-tools.types';

type EmailSeed = readonly [
  id: string,
  title: string,
  category: string,
  subject: string,
  issue: string,
  request: string,
];

const EMAIL_SEEDS: EmailSeed[] = [
  [
    'delay-notice',
    'Formal Delay Notification',
    'Delay',
    'Notice of programme delay',
    'The approved equipment delivery has moved by seven days.',
    'confirm the revised date and recovery plan',
  ],
  [
    'delay-mitigation',
    'Delay Mitigation Plan',
    'Delay',
    'Mitigation plan for delayed containment works',
    'Containment progress is below the approved look-ahead.',
    'review the attached resequencing and resource plan',
  ],
  [
    'delay-material',
    'Material Delivery Delay',
    'Delay',
    'Material delivery delay and site impact',
    'The fire-rated cable batch has not been dispatched.',
    'provide a firm dispatch date and partial-delivery option',
  ],
  [
    'delay-access',
    'Access Issue Delay',
    'Delay',
    'Access restriction affecting planned works',
    'The electrical room remains unavailable to the installation team.',
    'release access or confirm an alternative work window',
  ],
  [
    'delay-design',
    'Design Clarification Delay',
    'Delay',
    'Design clarification affecting progress',
    'The unresolved routing detail prevents installation in Corridor 3.',
    'issue the confirmed detail by the stated decision date',
  ],
  [
    'inspection-request-2',
    'Detailed Inspection Request',
    'Inspection',
    'Inspection request - completed installation',
    'The identified work is complete and internally checked.',
    'confirm attendance for the proposed inspection time',
  ],
  [
    'inspection-reschedule-2',
    'Inspection Reschedule',
    'Inspection',
    'Request to reschedule inspection',
    'The required access platform will be available tomorrow.',
    'move the inspection to the proposed replacement slot',
  ],
  [
    'inspection-cancel',
    'Inspection Cancellation',
    'Inspection',
    'Cancellation of inspection request',
    'A prerequisite test record is not yet complete.',
    "cancel today's inspection and await a revised request",
  ],
  [
    'inspection-ready-2',
    'Inspection Readiness',
    'Inspection',
    'Confirmation of inspection readiness',
    'All checklist items and supporting records are complete.',
    'proceed with inspection at the confirmed location',
  ],
  [
    'inspection-reject',
    'Inspection Rejection Response',
    'Inspection',
    'Response to rejected inspection',
    'The identified labels and seals have been corrected.',
    'review the evidence and arrange reinspection',
  ],
  [
    'approval-standard',
    'Technical Approval Request',
    'Approval',
    'Approval request for coordinated proposal',
    'The revised proposal resolves the recorded interface issue.',
    'approve the attached revision for construction',
  ],
  [
    'approval-revised',
    'Revised Submittal Approval',
    'Approval',
    'Revised submittal - approval requested',
    'All review comments are addressed in the response sheet.',
    'confirm approval of the revised submission',
  ],
  [
    'approval-urgent',
    'Urgent Approval Request',
    'Approval',
    'Urgent approval required to protect delivery',
    'Manufacturing release depends on this approval.',
    'complete review by the stated decision deadline',
  ],
  [
    'approval-follow',
    'Approval Follow-up',
    'Approval',
    'Follow-up on outstanding approval',
    'The review period has passed and procurement is now affected.',
    'confirm current status and final response date',
  ],
  [
    'approval-conditional',
    'Conditional Approval Response',
    'Approval',
    'Response to conditional approval',
    'The conditions have been incorporated into the latest revision.',
    'confirm whether construction may proceed',
  ],
  [
    'proc-material',
    'Material Status Follow-up',
    'Procurement',
    'Material manufacturing and delivery status',
    'The latest supplier update does not include a dispatch date.',
    'provide milestones, inspection and delivery dates',
  ],
  [
    'proc-document',
    'Missing Vendor Document',
    'Procurement',
    'Outstanding vendor document request',
    'The technical document register remains incomplete.',
    'submit the listed drawings and calculations',
  ],
  [
    'proc-certificate',
    'Certificate Request',
    'Procurement',
    'Traceable material certificate required',
    'The delivered batch cannot be matched to its certificate.',
    'provide batch-linked compliance evidence',
  ],
  [
    'proc-fat',
    'FAT Arrangement',
    'Procurement',
    'Factory acceptance test arrangement',
    'The equipment is approaching factory test readiness.',
    'confirm date, agenda and witness requirements',
  ],
  [
    'proc-escalate',
    'Delivery Escalation',
    'Procurement',
    'Escalation of missed delivery commitment',
    'The second committed delivery date was missed.',
    'submit a management-approved recovery plan',
  ],
  [
    'consultant-reply',
    'Consultant Comment Reply',
    'Consultant / Client',
    'Response to consultant technical comment',
    'The requested calculation and marked-up detail are attached.',
    'review the response and close the comment',
  ],
  [
    'consultant-clarify-2',
    'Consultant Clarification Request',
    'Consultant / Client',
    'Clarification required for conflicting requirement',
    'The specification and drawing show different interface locations.',
    'confirm the governing requirement',
  ],
  [
    'consultant-resubmit',
    'Document Resubmission',
    'Consultant / Client',
    'Resubmission of revised technical document',
    'The document was revised against every recorded comment.',
    'review Revision 03 and update the status',
  ],
  [
    'client-update',
    'Client Progress Update',
    'Consultant / Client',
    'Client update on critical works',
    'Progress remains controlled but one delivery risk is open.',
    'note the mitigation and upcoming decision',
  ],
  [
    'observation-response',
    'Site Observation Response',
    'Consultant / Client',
    'Response to consultant site observation',
    'The observed deficiency has been isolated and corrected.',
    'review the evidence and confirm closure',
  ],
  [
    'contract-instruction',
    'Contractor Work Instruction',
    'Contractor / Subcontractor',
    'Instruction to correct installation',
    'The installed support arrangement differs from the approved detail.',
    'correct the affected area before continuing',
  ],
  [
    'contract-warning',
    'Subcontractor Warning Letter',
    'Contractor / Subcontractor',
    'Warning regarding repeated underperformance',
    'Daily production targets have been missed repeatedly.',
    'submit an immediate recovery plan',
  ],
  [
    'contract-manpower',
    'Manpower Increase Request',
    'Contractor / Subcontractor',
    'Request for additional skilled manpower',
    'Current resources cannot achieve the look-ahead sequence.',
    'mobilize the stated trade resources',
  ],
  [
    'contract-corrective',
    'Corrective Action Request',
    'Contractor / Subcontractor',
    'Corrective action required',
    'The same quality issue has occurred in multiple areas.',
    'identify root cause and preventive control',
  ],
  [
    'contract-accelerate',
    'Progress Acceleration Request',
    'Contractor / Subcontractor',
    'Acceleration required for critical activity',
    'The activity now threatens the next milestone.',
    'confirm shift, resource and supervision changes',
  ],
  [
    'commission-result',
    'Test Result Submission',
    'Commissioning / Handover',
    'Submission of signed test results',
    'The functional test was completed without open defects.',
    'review the attached record and accept the result',
  ],
  [
    'commission-ready',
    'Commissioning Readiness',
    'Commissioning / Handover',
    'Readiness for commissioning activity',
    'All prerequisites except one interface sign-off are complete.',
    'close the interface action before the test window',
  ],
  [
    'commission-punch',
    'Punch List Closure',
    'Commissioning / Handover',
    'Commissioning punch-list closure',
    'The listed defects were corrected and retested.',
    'accept the evidence and close the items',
  ],
  [
    'commission-om',
    'O&M Manual Follow-up',
    'Commissioning / Handover',
    'Outstanding O&M manual documents',
    'The final manuals lack approved settings and certificates.',
    'submit the complete indexed revision',
  ],
  [
    'commission-handover',
    'Handover Document Submission',
    'Commissioning / Handover',
    'Submission of handover dossier',
    'As-builts, tests, manuals and training records are compiled.',
    'review the dossier and identify any final gap',
  ],
  [
    'meeting-invite-2',
    'Technical Coordination Invitation',
    'Meeting',
    'Coordination meeting - open interfaces',
    'Several cross-discipline interfaces require decisions.',
    'confirm attendance and prepare the listed inputs',
  ],
  [
    'meeting-minutes-2',
    'Meeting Minutes Distribution',
    'Meeting',
    'Minutes and action register',
    'The agreed actions and owners are recorded.',
    'review and raise corrections within two working days',
  ],
  [
    'safety-warning',
    'Safety Non-compliance Warning',
    'HSE',
    'Immediate correction of safety non-compliance',
    'An access route was obstructed by temporary services.',
    'remove the hazard and confirm preventive action',
  ],
  [
    'handover-training',
    'Operator Training Arrangement',
    'Commissioning / Handover',
    'Operator training schedule',
    'System training is required before handover.',
    'confirm attendees, trainer and proposed dates',
  ],
  [
    'project-decision',
    'Decision Required from Client',
    'Consultant / Client',
    'Client decision required to protect milestone',
    'Two compliant options remain open with different programme impacts.',
    'select the preferred option by the decision date',
  ],
];

export const EXPANDED_EMAIL_TEMPLATES: EmailTemplate[] = EMAIL_SEEDS.map(
  ([id, title, category, subject, issue, request]) => ({
    id: `expanded-email-${id}`,
    title,
    category,
    subject,
    shortVersion: `Subject: ${subject}\n\nDear Team,\n\n${issue} Please ${request}.\n\nRegards,`,
    professionalVersion: `Subject: ${subject}\n\nDear Team,\n\n${issue} Please ${request}, including the responsible person and committed date. This response is required to maintain the coordinated project sequence.\n\nKind regards,`,
    politeVersion: `Subject: ${subject}\n\nDear Team,\n\nCould you please ${request}? ${issue} Your timely support will help us maintain the agreed project sequence.\n\nKind regards,`,
    technicalVersion: `Subject: ${subject}\n\nDear Team,\n\n${issue} Please ${request} with the applicable drawing, specification, inspection or programme reference. Identify any technical constraint, accountable owner and close-out date.\n\nKind regards,`,
    turkishExplanation: `Bu e-posta, ${title.toLocaleLowerCase('tr-TR')} için teknik durumu ve beklenen cevabı profesyonel biçimde açıklar.`,
    tags: [
      category.toLowerCase(),
      'engineering email',
      'project communication',
    ],
  })
);
