import type { LucideIcon } from 'lucide-react';
import {
  Activity,
  AlertCircle,
  AlertTriangle,
  Archive,
  ArrowLeft,
  ArrowRight,
  Award,
  BarChart3,
  Bell,
  BookMarked,
  BookOpen,
  Bot,
  Brain,
  Building,
  Building2,
  Check,
  CheckCircle,
  CheckCircle2,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  Circle,
  Clipboard,
  ClipboardCheck,
  Clock,
  Copy,
  Cpu,
  Crown,
  Download,
  Edit2,
  ExternalLink,
  Factory,
  FileCheck,
  FileCheck2,
  FileCode,
  FileText,
  Filter,
  Flame,
  FlaskConical,
  Gauge,
  Gem,
  Globe,
  HardDrive,
  Headphones,
  History,
  Info,
  KeyRound,
  Landmark,
  Languages,
  Layers,
  Library,
  ListChecks,
  Lock,
  LockKeyhole,
  LogOut,
  Mail,
  Map,
  Menu,
  MessageSquare,
  MessageSquareText,
  Mic,
  Mic2,
  Monitor,
  Pause,
  PenLine,
  PenTool,
  Play,
  Plus,
  RefreshCw,
  RotateCcw,
  Save,
  Search,
  Send,
  Settings,
  Shield,
  ShieldAlert,
  ShieldCheck,
  Smartphone,
  Sparkles,
  Star,
  Target,
  Trash2,
  TrendingUp,
  TriangleAlert,
  Trophy,
  UploadCloud,
  User,
  UserRound,
  Users,
  Volume2,
  WandSparkles,
  WifiOff,
  X,
  XCircle,
  Zap,
} from 'lucide-react';

export const IconRegistry: Record<string, LucideIcon> = {
  'chevron-down': ChevronDown,
  'chevron-right': ChevronRight,
  'chevron-left': ChevronLeft,
  menu: Menu,
  close: X,
  'arrow-right': ArrowRight,
  'arrow-left': ArrowLeft,
  download: Download,
  upload: UploadCloud,
  refresh: RefreshCw,
  trash: Trash2,
  plus: Plus,
  copy: Copy,
  check: Check,
  'check-circle': CheckCircle2,
  'check-circle-filled': CheckCircle,
  circle: Circle,
  archive: Archive,
  save: Save,
  edit: Edit2,
  'pen-line': PenLine,
  search: Search,
  filter: Filter,
  settings: Settings,
  user: User,
  'user-round': UserRound,
  users: Users,
  building: Building2,
  'building-alt': Building,
  'shield-check': ShieldCheck,
  'shield-alert': ShieldAlert,
  shield: Shield,
  'lock-keyhole': LockKeyhole,
  lock: Lock,
  key: KeyRound,
  'alert-triangle': AlertTriangle,
  'alert-circle': AlertCircle,
  info: Info,
  'wifi-off': WifiOff,
  activity: Activity,
  flame: Flame,
  sparkles: Sparkles,
  zap: Zap,
  award: Award,
  trophy: Trophy,
  gem: Gem,
  star: Star,
  bookmark: BookMarked,
  'book-open': BookOpen,
  'file-text': FileText,
  'file-check': FileCheck,
  'file-check-2': FileCheck2,
  'file-code': FileCode,
  clipboard: Clipboard,
  'clipboard-check': ClipboardCheck,
  'list-checks': ListChecks,
  message: MessageSquare,
  'message-text': MessageSquareText,
  mic: Mic2,
  'mic-alt': Mic,
  volume: Volume2,
  headphones: Headphones,
  'rotate-ccw': RotateCcw,
  pause: Pause,
  play: Play,
  history: History,
  clock: Clock,
  layers: Layers,
  target: Target,
  gauge: Gauge,
  'bar-chart': BarChart3,
  'trending-up': TrendingUp,
  cpu: Cpu,
  factory: Factory,
  flask: FlaskConical,
  bot: Bot,
  brain: Brain,
  monitor: Monitor,
  languages: Languages,
  library: Library,
  globe: Globe,
  map: Map,
  'hard-drive': HardDrive,
  logout: LogOut,
  bell: Bell,
  mail: Mail,
  send: Send,
  'external-link': ExternalLink,
  wand: WandSparkles,
  smartphone: Smartphone,
  triangle: TriangleAlert,
  'x-circle': XCircle,
};

export const DisciplineIcons: Record<string, LucideIcon> = {
  architecture: Landmark,
  chemical: FlaskConical,
  civil: Building2,
  electrical: Zap,
  electronics: Cpu,
  hse: ShieldCheck,
  industrial: Factory,
  mechanical: Settings,
  mechatronics: Bot,
  software: Monitor,
  general: Library,
};

export const RankIcons: Record<string, LucideIcon> = {
  grandmaster: Crown,
  diamond: Gem,
  platinum: Trophy,
  gold: Award,
  silver: Award,
};

export const SkillIcons: Record<string, LucideIcon> = {
  vocabulary: BookMarked,
  grammar: Languages,
  reading: BookOpen,
  writing: PenTool,
  listening: Headphones,
  speaking: MessageSquare,
};

export function getIcon(name: string): LucideIcon | undefined {
  return IconRegistry[name];
}

export function getDisciplineIcon(discipline: string): LucideIcon {
  return DisciplineIcons[discipline] ?? Library;
}

export function getRankIcon(rank: string): LucideIcon {
  return RankIcons[rank.toLowerCase()] ?? Award;
}

export function getSkillIcon(skill: string): LucideIcon {
  return SkillIcons[skill.toLowerCase()] ?? BookOpen;
}
