import type { WritingMission } from './writing.types';

const starterRubric = {
  clarity: 'The message states one clear fact and one clear action.',
  technicalAccuracy: 'The location, equipment, and status are correct.',
  grammar: 'The answer uses simple complete sentences and correct basic tense.',
  professionalTone: 'The message is polite and factual.',
  conciseness: 'The message is short and avoids repetition.',
  completeness: 'The message includes the status and next action.',
  actionOrientation: 'The requested action is easy to identify.',
  structure: 'The message follows greeting, status, action, and closing.',
  technicalVocabulary: 'Basic site terms are used correctly.',
};

export const STARTER_WRITING_MISSIONS: WritingMission[] = [
  {
    id: 'writing_a1_simple_site_update',
    title: 'Simple Site Update',
    description: 'Write two simple sentences about completed electrical work.',
    discipline: 'Electrical Engineering',
    cefrLevel: 'A1',
    difficulty: 'Beginner',
    estimatedMinutes: 6,
    initialDraft: 'We install cable tray today. Work finish.',
    corrections: [
      {
        id: 'writing_a1_tense',
        type: 'grammar',
        text: 'Use the past tense for completed work.',
        original: 'We install cable tray today.',
        fix: 'We installed the cable tray today.',
      },
      {
        id: 'writing_a1_complete',
        type: 'grammar',
        text: 'Use a complete sentence.',
        original: 'Work finish.',
        fix: 'The work is complete.',
      },
      {
        id: 'writing_a1_style',
        type: 'style',
        text: 'Add a clear next action for the supervisor.',
        original: 'The work is complete.',
        fix: 'The work is complete and ready for the supervisor’s check.',
      },
    ],
    xpReward: 25,
    coinReward: 8,
    eloReward: 4,
    scenario: 'The team completed a short cable tray section.',
    task: 'Write a clear two-sentence update.',
    expectedStructure: [
      'Work area',
      'Completed work',
      'Current status',
      'Next action',
    ],
    targetVocabulary: [
      'installed',
      'cable tray',
      'complete',
      'work area',
      'supervisor',
    ],
    grammarFocus: ['simple past', 'be verb'],
    assessmentRubric: starterRubric,
    sampleExcellentAnswer:
      'We installed the cable tray in Corridor Two today. The work is complete and ready for the supervisor’s check.',
    sampleWeakAnswer: 'Tray done today. Everything is good now.',
    feedbackHints: [
      'Use a subject and verb.',
      'State what is complete.',
      'Add the location or next action.',
    ],
  },
  {
    id: 'writing_a2_inspection_request',
    title: 'Basic Inspection Request',
    description: 'Write a short and polite request for a site inspection.',
    discipline: 'QA/QC',
    cefrLevel: 'A2',
    difficulty: 'Beginner',
    estimatedMinutes: 8,
    initialDraft:
      'Cable tray work complete in Corridor Two. Please inspect tomorrow morning.',
    corrections: [
      {
        id: 'writing_a2_article',
        type: 'grammar',
        text: 'Add the article and auxiliary verb.',
        original: 'Cable tray work complete',
        fix: 'The cable tray work is complete',
      },
      {
        id: 'writing_a2_polite',
        type: 'style',
        text: 'Use a polite professional request.',
        original: 'Please inspect tomorrow morning.',
        fix: 'Please arrange the inspection tomorrow morning.',
      },
      {
        id: 'writing_a2_structure',
        type: 'style',
        text: 'State the location before the inspection request.',
        original: 'Please arrange the inspection tomorrow morning.',
        fix: 'Please arrange the Corridor Two inspection tomorrow morning.',
      },
    ],
    xpReward: 35,
    coinReward: 10,
    eloReward: 6,
    scenario: 'Cable tray installation is ready for inspection.',
    task: 'Request an inspection and state the location and time.',
    expectedStructure: [
      'Greeting',
      'Work status',
      'Location',
      'Inspection request',
    ],
    targetVocabulary: [
      'complete',
      'inspection',
      'Corridor Two',
      'arrange',
      'tomorrow morning',
    ],
    grammarFocus: ['present simple', 'polite requests'],
    assessmentRubric: starterRubric,
    sampleExcellentAnswer:
      'The cable tray work in Corridor Two is complete. Please arrange the inspection tomorrow morning.',
    sampleWeakAnswer: 'Tray okay. Come check.',
    feedbackHints: [
      'Name the location.',
      'Use a polite request.',
      'State that the work is complete.',
    ],
  },
];
